import { useEffect, useState } from 'react'
import { Button } from '../../../shared/ui/Button'
import { PageTitle } from '../../../shared/ui/PageTitle'
import { TopBar } from '../../../shared/ui/TopBar'
import { WorkbenchLayout } from '../../../shared/ui/WorkbenchLayout'
import { gatewayHeaders, readJson } from '../../../shared/data/gatewayRequest'

type Milestone = { id: string; title: string; done: boolean; target_date: string | null }
type Plan = { goal_id: string; revision: number; parent_id: string | null; horizon: string; milestones: Milestone[]; links: { kind: string; id: string }[]; unit: string; target_value: number | null }
type View = { goal: { id: string; title: string; status: string }; plan: Plan; children: string[]; checkins: { id: string; value: number; observed_at: string; notes: string; unit: string; source: string }[]; velocity: { value_per_day: number; unit: string } | null; linked_sources: { kind: string; id: string; title: string | null; status: string | null; availability: string }[]; milestones_complete_ratio: number | null }
export default function GoalPlanPage({ endpoint = '/api/capabilities/identity/goal-plans' }: { endpoint?: string }) {
  const [rows, setRows] = useState<View[]>([])
  const [view, setView] = useState<View | null>(null)
  const [plan, setPlan] = useState<Plan | null>(null)
  const [request, setRequest] = useState(() => crypto.randomUUID())
  const [checkRequest, setCheckRequest] = useState(() => crypto.randomUUID())
  const [value, setValue] = useState('')
  const [observedAt, setObservedAt] = useState('')
  const [notes, setNotes] = useState('')
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [loaded, setLoaded] = useState(false)
  const call = async <T,>(path = '', body?: unknown): Promise<T> => readJson<T>(await fetch(endpoint + path, { method: body ? 'POST' : 'GET', headers: { ...gatewayHeaders, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) }))
  const choose = (row: View) => { setView(row); setPlan(row.plan); window.location.hash = '#/capabilities/identity/goal-plans?goal=' + row.goal.id }
  const load = async () => { const next = await call<View[]>(); setRows(next); setLoaded(true); const id = new URLSearchParams(window.location.hash.split('?')[1] || '').get('goal'); const selected = next.find(row => row.goal.id === id); if (selected) choose(selected) }
  const perform = async (action: () => Promise<void>) => { setBusy(true); setError(''); try { await action() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  useEffect(() => { void perform(load) }, [endpoint])
  return <WorkbenchLayout topBar={<TopBar keepCornerPadding left={<PageTitle>Goal hierarchy and observations</PageTitle>} />}>
  <section className="mx-auto flex w-full max-w-[64rem] flex-col gap-l px-l py-2xl text-on-surface"><p>Milestones and measurements are human-reported. Automation status does not determine human attainment.</p>
    {error && <p role="alert" className="text-danger">{error}</p>}{!loaded && <p role="status">Loading goal plans…</p>}<Button disabled={busy} onClick={() => void perform(load)}>Reload goal plans</Button>
    <a className="block underline" href="#/capabilities/identity/goals">Create or schedule a life goal</a>{loaded && !rows.length && <p>No human goals yet.</p>}
    <nav aria-label="Human goals">{rows.map(row => <button className="block underline" key={row.goal.id} onClick={() => choose(row)}>{row.goal.title}</button>)}</nav>
    {plan && view && <><form className="space-y-m rounded-lg bg-surface-container p-l" onSubmit={e => { e.preventDefault(); void perform(async () => { const { revision, ...fields } = plan; await call('/configure', { ...fields, expected_revision: revision, request_id: request }); setRequest(crypto.randomUUID()); await load() }) }}>
      <h2 data-type="title-l">{view.goal.title}</h2><label className="block" htmlFor="plan-parent">Parent goal</label><select id="plan-parent" value={plan.parent_id || ''} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary appearance-none" onChange={e => setPlan({ ...plan, parent_id: e.target.value || null })}><option value="">No parent</option>{rows.filter(row => row.goal.id !== plan.goal_id).map(row => <option key={row.goal.id} value={row.goal.id}>{row.goal.title}</option>)}</select>
      <label className="block" htmlFor="plan-horizon">Goal horizon</label><select id="plan-horizon" value={plan.horizon} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary appearance-none" onChange={e => setPlan({ ...plan, horizon: e.target.value })}>{['short_term', 'long_term', 'lifetime'].map(item => <option key={item}>{item}</option>)}</select>
      <label className="block" htmlFor="plan-unit">Metric unit</label><input id="plan-unit" value={plan.unit} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setPlan({ ...plan, unit: e.target.value })} required />
      <label className="block" htmlFor="plan-target">Target metric (optional)</label><input id="plan-target" type="number" step="any" value={plan.target_value ?? ''} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setPlan({ ...plan, target_value: e.target.value === '' ? null : Number(e.target.value) })} />
      <h3 data-type="title-m">Milestones</h3>{plan.milestones.map((item, index) => <fieldset className="space-y-s rounded-lg bg-surface-high p-m" key={item.id}><legend>Milestone {index + 1}</legend><label htmlFor={'milestone-title-' + index}>Milestone title {index + 1}</label><input id={'milestone-title-' + index} value={item.title} required className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setPlan({ ...plan, milestones: plan.milestones.map((row, i) => i === index ? { ...row, title: e.target.value } : row) })} /><label><input type="checkbox" checked={item.done} className="size-4 shrink-0 accent-primary" onChange={e => setPlan({ ...plan, milestones: plan.milestones.map((row, i) => i === index ? { ...row, done: e.target.checked } : row) })} /> Milestone {index + 1} complete</label><label htmlFor={'milestone-date-' + index}>Milestone date {index + 1}</label><input id={'milestone-date-' + index} type="date" value={item.target_date || ''} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setPlan({ ...plan, milestones: plan.milestones.map((row, i) => i === index ? { ...row, target_date: e.target.value || null } : row) })} /><Button variant="secondary" onClick={() => setPlan({ ...plan, milestones: plan.milestones.filter((_, i) => i !== index) })}>Remove milestone {index + 1}</Button></fieldset>)}
      <Button variant="secondary" disabled={plan.milestones.length >= 100} onClick={() => setPlan({ ...plan, milestones: [...plan.milestones, { id: crypto.randomUUID(), title: '', done: false, target_date: null }] })}>Add milestone</Button>
      <h3 data-type="title-m">Actual local source links</h3>{plan.links.map((link, index) => <fieldset className="space-y-s rounded-lg bg-surface-high p-m" key={index}><legend>Source {index + 1}</legend><label htmlFor={'source-kind-' + index}>Source kind {index + 1}</label><select id={'source-kind-' + index} value={link.kind} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary appearance-none" onChange={e => setPlan({ ...plan, links: plan.links.map((row, i) => i === index ? { ...row, kind: e.target.value } : row) })}>{['task', 'loop', 'session'].map(kind => <option key={kind}>{kind}</option>)}</select><label htmlFor={'source-id-' + index}>Local source ID {index + 1}</label><input id={'source-id-' + index} value={link.id} required className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setPlan({ ...plan, links: plan.links.map((row, i) => i === index ? { ...row, id: e.target.value } : row) })} /><Button variant="secondary" onClick={() => setPlan({ ...plan, links: plan.links.filter((_, i) => i !== index) })}>Remove source {index + 1}</Button></fieldset>)}
      <Button variant="secondary" disabled={plan.links.length >= 100} onClick={() => setPlan({ ...plan, links: [...plan.links, { kind: 'task', id: '' }] })}>Link local source</Button><Button type="submit" disabled={busy}>Save goal plan</Button>
    </form>
    <section aria-label="Goal plan summary"><p>Human goal status: {view.goal.status}</p><p>Milestones reported complete: {view.milestones_complete_ratio === null ? 'Unknown' : Math.round(view.milestones_complete_ratio * 100) + '%'}</p><p>Observed velocity: {view.velocity ? view.velocity.value_per_day.toFixed(3) + ' ' + view.velocity.unit + '/day' : 'Unknown — at least two observation times needed'}</p>{view.children.map(id => <a className="block underline" key={id} href={'#/capabilities/identity/goal-plans?goal=' + id} onClick={() => { const child = rows.find(row => row.goal.id === id); if (child) choose(child) }}>{rows.find(row => row.goal.id === id)?.goal.title || id}</a>)}{view.linked_sources.map(row => <p key={row.kind + row.id}>{row.kind}: {row.title || row.id} · {row.availability} · {row.status || 'unknown'}</p>)}</section>
    <form className="space-y-m rounded-lg bg-surface-container p-l" onSubmit={e => { e.preventDefault(); void perform(async () => { await call('/checkins', { goal_id: plan.goal_id, value: Number(value), observed_at: observedAt, notes, request_id: checkRequest }); setCheckRequest(crypto.randomUUID()); setValue(''); setNotes(''); await load() }) }}><h2 data-type="title-l">Report a metric observation</h2><label className="block" htmlFor="metric-value">Observed value</label><input id="metric-value" type="number" step="any" required value={value} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setValue(e.target.value)} /><label className="block" htmlFor="metric-time">Observed time with timezone</label><input id="metric-time" required placeholder="2026-10-01T10:00:00Z" value={observedAt} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setObservedAt(e.target.value)} /><label className="block" htmlFor="metric-notes">Observation notes</label><textarea id="metric-notes" value={notes} className="w-full min-w-0 resize-y rounded-md border border-outline-variant/30 bg-surface-container p-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setNotes(e.target.value)} /><Button type="submit" disabled={busy}>Record observation</Button></form>
    <section aria-label="Metric history"><h2 data-type="title-l">Human-reported observations</h2>{view.checkins.map(row => <p key={row.id}>{row.observed_at} · {row.value} {row.unit} · {row.notes}</p>)}</section></>}
  </section></WorkbenchLayout>
}
