import { useEffect, useState } from 'react'
import { Button } from '../../../shared/ui/Button'
import { PageTitle } from '../../../shared/ui/PageTitle'
import { TopBar } from '../../../shared/ui/TopBar'
import { WorkbenchLayout } from '../../../shared/ui/WorkbenchLayout'
import { gatewayHeaders, readJson } from '../../../shared/data/gatewayRequest'

type Tool = { name: string; provider: string; description: string; parameters: unknown; requires_approval: boolean }
type Recipe = { id: string; title: string; revision: number }
type Run = { id: string; status: string; next_index: number; session_key: string; defer_reason?: string; steps: { id: string; status: string; output?: unknown; error?: string }[]; permission?: { request_id: string; tool: string; arguments: unknown; risk: string } }
export default function GuardedRecipesPage({ endpoint = '/api/capabilities/identity/guarded-recipes' }: { endpoint?: string }) {
  const [session, setSession] = useState('dashboard:')
  const [tools, setTools] = useState<Tool[]>([])
  const [rows, setRows] = useState<Recipe[]>([])
  const [title, setTitle] = useState('')
  const [steps, setSteps] = useState([{ id: 'first', tool: '', arguments: '{}' }])
  const [history, setHistory] = useState<Recipe[]>([])
  const [run, setRun] = useState<Run | null>(null)
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const call = async <T,>(path = '', body?: unknown): Promise<T> => readJson<T>(await fetch(endpoint + path, { method: body ? 'POST' : 'GET', headers: { ...gatewayHeaders, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) }))
  const perform = async (action: () => Promise<void>) => { setBusy(true); setError(''); try { await action() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  const selectRun = (next: Run) => { setRun(next); setSession(next.session_key); window.location.hash = '#/capabilities/identity/guarded-recipes?run=' + next.id }
  useEffect(() => { void perform(async () => { setRows(await call<Recipe[]>()); const id = new URLSearchParams(window.location.hash.split('?')[1] || '').get('run'); if (id) selectRun(await call<Run>('/runs/' + id)) }) }, [endpoint])
  return <WorkbenchLayout topBar={<TopBar keepCornerPadding left={<PageTitle>Guarded recipes</PageTitle>} />}>
  <section className="mx-auto flex w-full max-w-[56rem] flex-col gap-l px-l py-2xl text-on-surface"><p>Use tools from an existing private native session. Each step uses that session’s current permissions and approval engine. Busy sessions defer; no model call is required to dispatch a tool.</p>
    {error && <p role="alert">{error}</p>}<label className="block" htmlFor="guarded-session">Existing session key</label><input id="guarded-session" value={session} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => { setSession(e.target.value); setTools([]) }} /><Button disabled={busy} onClick={() => void perform(async () => { const catalog = await call<{ tools: Tool[] }>('/catalog?session_key=' + encodeURIComponent(session)); setTools(catalog.tools) })}>Load session tools</Button>
    <form className="space-y-m rounded-lg bg-surface-container p-l" onSubmit={e => { e.preventDefault(); void perform(async () => { await call('/save', { session_key: session, title, steps: steps.map(step => ({ ...step, arguments: JSON.parse(step.arguments) })), request_id: crypto.randomUUID() }); setRows(await call<Recipe[]>()); setTitle('') }) }}><label className="block" htmlFor="guarded-title">Recipe title</label><input id="guarded-title" required value={title} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setTitle(e.target.value)} />
      {steps.map((step, index) => <fieldset className="space-y-s rounded-lg bg-surface-high p-m" key={index}><legend>Step {index + 1}</legend><label htmlFor={'guarded-tool-' + index}>Tool {index + 1}</label><select id={'guarded-tool-' + index} required value={step.tool} className="h-10 w-full min-w-0 rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary appearance-none" onChange={e => setSteps(steps.map((row, i) => i === index ? { ...row, tool: e.target.value } : row))}><option value="">Choose current tool</option>{tools.map(tool => <option key={tool.name} value={tool.name}>{tool.provider}: {tool.name}{tool.requires_approval ? ' · approval' : ''}</option>)}</select><label className="block" htmlFor={'guarded-args-' + index}>Arguments {index + 1}</label><textarea id={'guarded-args-' + index} required value={step.arguments} className="w-full min-w-0 resize-y rounded-md border border-outline-variant/30 bg-surface-container p-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" onChange={e => setSteps(steps.map((row, i) => i === index ? { ...row, arguments: e.target.value } : row))} /><details><summary>Current tool schema</summary><pre>{JSON.stringify(tools.find(tool => tool.name === step.tool)?.parameters, null, 2)}</pre></details></fieldset>)}
      <Button disabled={busy || steps.length >= 5} onClick={() => setSteps([...steps, { id: 'step' + (steps.length + 1), tool: '', arguments: '{}' }])}>Add step</Button><Button type="submit" disabled={busy || !tools.length}>Save guarded recipe</Button></form>
    <section aria-label="Saved guarded recipes">{rows.map(row => <article key={row.id}><span>{row.title} · revision {row.revision}</span><Button disabled={busy} onClick={() => void perform(async () => selectRun(await call<Run>('/begin', { session_key: session, recipe_id: row.id, revision: row.revision, request_id: crypto.randomUUID() })))}>Bind {row.title}</Button><Button disabled={busy} onClick={() => void perform(async () => setHistory(await call<Recipe[]>('/history/' + row.id)))}>History {row.title}</Button></article>)}</section>
    {history.map(version => <Button key={version.id + version.revision} disabled={busy} onClick={() => void perform(async () => { await call('/restore', { session_key: session, id: version.id, revision: version.revision, expected_revision: rows.find(row => row.id === version.id)!.revision, request_id: crypto.randomUUID() }); setRows(await call<Recipe[]>()); setHistory(await call<Recipe[]>('/history/' + version.id)) })}>Restore {version.title} revision {version.revision}</Button>)}
    {run && <section aria-label="Guarded run"><p>Status: {run.status}</p><p>{run.defer_reason}</p><Button disabled={busy || !['ready', 'deferred'].includes(run.status)} onClick={() => void perform(async () => selectRun(await call<Run>('/advance', { run_id: run.id, expected_index: run.next_index })))}>Dispatch next step</Button><Button disabled={busy} onClick={() => void perform(async () => selectRun(await call<Run>('/runs/' + run.id)))}>Refresh run</Button><Button disabled={busy} onClick={() => void perform(async () => selectRun(await call<Run>('/cancel', { run_id: run.id })))}>Cancel guarded run</Button>
      {run.permission && <article aria-label="Actual permission request"><h2 data-type="title-l">Session approval: {run.permission.tool}</h2><p>Risk: {run.permission.risk}</p><pre>{JSON.stringify(run.permission.arguments, null, 2)}</pre>{['approve', 'reject'].map(decision => <Button disabled={busy} key={decision} onClick={() => void perform(async () => selectRun(await call<Run>('/decide', { run_id: run.id, request_id: run.permission!.request_id, decision, session_key: run.session_key })))}>{decision === 'approve' ? 'Approve actual tool call' : 'Reject actual tool call'}</Button>)}</article>}
      {run.steps.map(step => <article key={step.id}><p>{step.id}: {step.status}</p>{step.error && <p>{step.error}</p>}<pre>{step.output !== undefined ? JSON.stringify(step.output, null, 2) : ''}</pre></article>)}
    </section>}
  </section></WorkbenchLayout>
}
