"""Outbound export of Gideon entities into external harness formats (AGENT-PACKS §5).

This is the OPPOSITE direction from the pack importer and from the read-only inbound
adapters: here we *write into another tool's directory*. That makes four rails
load-bearing, and every one of them fails CLOSED:

1. **Explicit dest confirmation.** :func:`export_entities` refuses unless the caller passes
   ``confirm_dest=True``. Nothing is ever "auto-installed" into another tool's config
   (§5 bullet 3). :func:`default_dest_dir` only *suggests* the canonical location.
2. **Containment.** A rendered file's relative path is validated twice — once when a
   renderer derives it from an entity name (:func:`_slug`), once again against the resolved
   destination root (:func:`_resolve_target`). ``../``, absolute paths and path separators
   in a slug are refused, so an entity name can never steer a write outside ``dest_dir``.
3. **Content redaction (§2.2).** Every rendered file's text is scanned with
   :func:`packs.build._scan_component` — the SAME two detectors (``security.redact`` +
   ``guardrails.scan_outbound``) the pack exporter uses, imported rather than forked. A hit
   BLOCKS the whole export before any file is written; a credential is never rewritten into
   someone else's prose and never lands on disk.
4. **No clobber.** We only ever replace a file we wrote ourselves, identified by the
   :data:`PROVENANCE_MARKER` trailer. A user's own agent definition at the same path is
   refused, never overwritten.

The rendering contract is one-shot: **an export surface, not a sync system** (§5). Drift
after the write is the recipient tool's problem, which is exactly why the render must be
deterministic — the same entities render byte-identical bytes on every run, so a
re-export is a no-op diff. No timestamps, no machine paths, no dict-iteration order
reaches the output; roster order is sorted. ``tests/fixtures/external_formats_golden/``
pins that promise per format.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any, Union

from gideon.engine.agents.marketplace import AgentDefinition

PROVENANCE_MARKER = "<!-- generated by gideon: outbound entity export -->"

INSTALL_KIND_PER_AGENT = "per-agent"
INSTALL_KIND_ROSTER = "roster"
INSTALL_KIND_PLUGIN = "plugin"

_SLUG_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,62}$")


@dataclass(frozen=True)
class ExportSkill:
    """A skill to export near-verbatim — it is already the standard skill-catalog shape."""

    slug: str
    text: str


Entity = Union[AgentDefinition, ExportSkill]


@dataclass(frozen=True)
class RenderedFile:
    """One file a renderer produced: a POSIX-relative path under ``dest_dir`` plus text."""

    relpath: str
    text: str


@dataclass(frozen=True)
class ExternalFormat:
    """The §5 contract, field-for-field.

    ``installKind`` keeps the plan's spelling deliberately — this is a declared contract
    name, not a local variable. ``dest`` is the *canonical documented* location (a template
    for the per-entity kinds); the actual write target is always the caller's confirmed
    directory, never this string.
    """

    name: str
    installKind: str  # noqa: N815 — the §5 contract name
    dest: str
    render: Callable[[Sequence[Entity]], list[RenderedFile]]


class ExportRefused(Exception):
    """Base class — an export that did not happen, and said why."""


class DestNotConfirmed(ExportRefused):
    """The caller did not explicitly confirm the destination directory."""


class ExportPathRefused(ExportRefused):
    """A rendered path would escape ``dest_dir`` (or a slug is not a safe file name)."""


class ExportClobberRefused(ExportRefused):
    """The destination holds a file we did not write. We never overwrite one."""


@dataclass(frozen=True)
class BlockedRender:
    """One rendered file the content layer refused to let leave."""

    relpath: str
    reason: str
    categories: tuple[str, ...] = ()


class ExportBlocked(ExportRefused):
    """§2.2 content layer found a credential in rendered output. Nothing was written."""

    def __init__(self, blocked: list[BlockedRender]):
        self.blocked = blocked
        detail = "; ".join(f"{b.relpath}: {b.reason}" for b in blocked)
        super().__init__(f"export blocked by content redaction: {detail}")


@dataclass
class ExportResult:
    """What an export actually did — the absolute paths written, in render order."""

    format_name: str
    dest_dir: Path
    written: list[Path] = field(default_factory=list)


def _slug(name: str) -> str:
    """Validate an entity name as a file-name component. Raises rather than sanitising.

    Sanitising a hostile name (``../evil`` → ``evil``) writes a file the user never named,
    at a path they cannot predict. Refusing is the only honest answer, and it is the FIRST
    of two independent containment checks (:func:`_resolve_target` is the second).
    """
    slug = (name or "").strip()
    if not _SLUG_RE.match(slug):
        raise ExportPathRefused(
            f"unsafe entity name for a destination file: {name!r} "
            "(expected ^[a-z0-9][a-z0-9._-]{0,62}$ — no separators, no '..', not absolute)"
        )
    return slug


def _yaml_scalar(value: str) -> str:
    """Emit a single-line YAML scalar, quoted only when it must be.

    Frontmatter is the part an external tool parses; a description carrying ``:`` or a
    leading ``#`` would break its loader (i.e. the file would not load at all).
    """
    text = " ".join(str(value).split())
    if not text:
        return '""'
    needs_quote = text[0] in "#&*!|>%@`'\"[]{}," or ": " in text or text.endswith(":")
    if needs_quote:
        return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'
    return text


def _body(defn: AgentDefinition, *, skills_heading: str = "## Skills") -> str:
    """The persona body: operating rules, then voice, then declared skills.

    ``skills_heading`` demotes one level inside the roster format, where each agent already
    owns an ``##`` heading and a second ``##`` would read as a sibling section.

    ``mcp_servers`` is deliberately NOT rendered. It is a free-form dict whose values can
    carry env values or headers — the one field on an AgentDefinition that could plausibly
    hold a credential — and a foreign tool cannot consume our MCP shape anyway. Excluding
    it structurally beats redacting it after the fact.
    """
    parts: list[str] = []
    if defn.system_prompt.strip():
        parts.append(defn.system_prompt.strip())
    if defn.voice.strip():
        parts.append(defn.voice.strip())
    skills = [s.strip() for s in defn.skills if isinstance(s, str) and s.strip()]
    if skills:
        seen: dict[str, None] = dict.fromkeys(skills)
        lines = [skills_heading, ""]
        lines += [f"- {s}" for s in seen]
        parts.append("\n".join(lines))
    return "\n\n".join(parts)


def _document(front: list[str], body: str) -> str:
    """Assemble frontmatter + body + provenance trailer with a fixed byte layout."""
    out = ["---", *front, "---", ""]
    if body:
        out += [body, ""]
    out.append(PROVENANCE_MARKER)
    return "\n".join(out) + "\n"


def _agents_only(entities: Sequence[Entity], fmt_name: str) -> list[AgentDefinition]:
    bad = [e for e in entities if not isinstance(e, AgentDefinition)]
    if bad:
        raise ExportRefused(
            f"format {fmt_name!r} renders agents only; got "
            f"{', '.join(type(e).__name__ for e in bad)}"
        )
    if not entities:
        raise ExportRefused(f"format {fmt_name!r}: nothing to export")
    return list(entities)  # type: ignore[arg-type]


def render_claude_code_agents(entities: Sequence[Entity]) -> list[RenderedFile]:
    """One markdown file per agent, in the external per-agent agent-definition shape.

    Frontmatter carries ``name`` and ``description`` (the two keys the format requires to
    load) plus ``model`` when the agent pins one. It deliberately does NOT emit a ``tools:``
    key: an AgentDefinition has no tool-allowlist field, so any value we wrote there would
    be invented — and an invented allowlist would silently narrow the exported agent's
    abilities. Omitting the key is the format's documented "inherit the caller's tools"
    default. Declared skills go in the body instead, where an unknown key cannot break the
    recipient's frontmatter parse.
    """
    out: list[RenderedFile] = []
    for defn in _agents_only(entities, "claude-code-agents"):
        slug = _slug(defn.name)
        front = [f"name: {_yaml_scalar(defn.name)}"]
        front.append(f"description: {_yaml_scalar(defn.description or defn.name)}")
        if defn.model.strip():
            front.append(f"model: {_yaml_scalar(defn.model)}")
        out.append(RenderedFile(f"{slug}.md", _document(front, _body(defn))))
    return out


def render_cursor_rules(entities: Sequence[Entity]) -> list[RenderedFile]:
    """The whole roster as ONE rules file (§5: cursor-rules is roster-kind).

    Agents are sorted by slug, so the same roster renders identically no matter what order
    the caller happened to enumerate it in.
    """
    agents = sorted(_agents_only(entities, "cursor-rules"), key=lambda d: _slug(d.name))
    front = [
        f"description: {_yaml_scalar(f'Gideon agent roster ({len(agents)} agents)')}",
        "globs:",
        "alwaysApply: false",
    ]
    sections: list[str] = []
    for defn in agents:
        block = [f"## {defn.name}", ""]
        if defn.description.strip():
            block += [" ".join(defn.description.split()), ""]
        body = _body(defn, skills_heading="### Skills")
        if body:
            block += [body, ""]
        sections.append("\n".join(block).rstrip())
    body = "\n\n".join(sections)
    return [RenderedFile("gideon-roster.mdc", _document(front, body))]


def render_skill_md(entities: Sequence[Entity]) -> list[RenderedFile]:
    """A ``skills/<slug>/SKILL.md`` per entity.

    An :class:`ExportSkill` ships near-verbatim — it already IS the standard shape, so
    re-rendering it would only risk mangling it. We append the provenance trailer (and a
    trailing newline) and nothing else, which keeps the write idempotent.
    """
    if not entities:
        raise ExportRefused("format 'skill-md': nothing to export")
    out: list[RenderedFile] = []
    for entity in entities:
        if isinstance(entity, ExportSkill):
            slug = _slug(entity.slug)
            text = entity.text if entity.text.endswith("\n") else entity.text + "\n"
            if PROVENANCE_MARKER not in text:
                text = f"{text}\n{PROVENANCE_MARKER}\n"
            out.append(RenderedFile(f"skills/{slug}/SKILL.md", text))
        elif isinstance(entity, AgentDefinition):
            slug = _slug(entity.name)
            front = [
                f"name: {_yaml_scalar(entity.name)}",
                f"description: {_yaml_scalar(entity.description or entity.name)}",
            ]
            out.append(
                RenderedFile(f"skills/{slug}/SKILL.md", _document(front, _body(entity)))
            )
        else:
            raise ExportRefused(
                f"format 'skill-md': unsupported entity {type(entity).__name__}"
            )
    return out


CLAUDE_CODE_AGENTS = ExternalFormat(
    name="claude-code-agents",
    installKind=INSTALL_KIND_PER_AGENT,
    dest="~/.claude/agents/{slug}.md",
    render=render_claude_code_agents,
)

CURSOR_RULES = ExternalFormat(
    name="cursor-rules",
    installKind=INSTALL_KIND_ROSTER,
    dest=".cursor/rules/gideon-roster.mdc",
    render=render_cursor_rules,
)

SKILL_MD = ExternalFormat(
    name="skill-md",
    installKind=INSTALL_KIND_PLUGIN,
    dest="<dir>/skills/{slug}/SKILL.md",
    render=render_skill_md,
)

EXTERNAL_FORMATS: dict[str, ExternalFormat] = {
    fmt.name: fmt for fmt in (CLAUDE_CODE_AGENTS, CURSOR_RULES, SKILL_MD)
}


def format_names() -> list[str]:
    """Declared format names, in presentation order."""
    return list(EXTERNAL_FORMATS)


def get_format(name: str) -> ExternalFormat:
    """Look up a format by name, or raise naming the valid set."""
    try:
        return EXTERNAL_FORMATS[name]
    except KeyError:
        raise ExportRefused(
            f"unknown external format {name!r} (known: {', '.join(EXTERNAL_FORMATS)})"
        ) from None


def default_dest_dir(fmt: ExternalFormat) -> Path | None:
    """The canonical destination directory a UI may PREFILL, or ``None``.

    Home-anchored formats resolve against ``Path.home()``; project-relative ones (Cursor
    rules, a skills plugin dir) have no machine-independent default, so they return
    ``None`` and the caller must supply a directory. This is the single resolver a test
    monkeypatches — nothing else in this module reads ``Path.home()``, so a test can never
    reach a real ``~/.claude``. Suggesting a directory is NOT confirming it:
    :func:`export_entities` still demands ``confirm_dest=True``.
    """
    if not fmt.dest.startswith("~/"):
        return None
    return Path.home() / PurePosixPath(fmt.dest[2:]).parent


def _resolve_target(dest_dir: Path, relpath: str) -> Path:
    """Second containment check: the resolved target must live under ``dest_dir``."""
    pure = PurePosixPath(relpath)
    if not relpath or pure.is_absolute() or "\\" in relpath:
        raise ExportPathRefused(f"rendered path must be relative POSIX: {relpath!r}")
    if any(part in ("", ".", "..") for part in pure.parts):
        raise ExportPathRefused(f"rendered path may not traverse: {relpath!r}")
    if str(pure) != relpath:
        raise ExportPathRefused(f"rendered path must be normalised: {relpath!r}")
    base = dest_dir.resolve()
    target = (base / pure).resolve()
    if target != base and base not in target.parents:
        raise ExportPathRefused(f"rendered path escapes {base}: {relpath!r}")
    return target


def _is_ours(path: Path) -> bool:
    """True when an existing file carries our provenance trailer (so replacing it is safe)."""
    try:
        return PROVENANCE_MARKER in path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def scan_rendered(files: Sequence[RenderedFile]) -> list[BlockedRender]:
    """Run the §2.2 CONTENT layer over rendered output.

    Imports :func:`packs.build._scan_component` on purpose: the §2.2 rules are SHARED, not
    forked. Whatever blocks a pack component blocks an outbound render, and a rule added
    there applies here the same day.
    """
    from gideon.extensions.packs.build import _scan_component

    blocked: list[BlockedRender] = []
    for rf in files:
        reason, categories = _scan_component(rf.text.encode("utf-8"))
        if reason:
            blocked.append(BlockedRender(rf.relpath, reason, tuple(categories)))
    return blocked


def export_entities(
    fmt: ExternalFormat,
    entities: Sequence[Entity],
    dest_dir: Path | str,
    *,
    confirm_dest: bool = False,
    overwrite: bool = False,
) -> ExportResult:
    """Render ``entities`` through ``fmt`` and write them under ``dest_dir``.

    The order is deliberate and all-or-nothing: render → containment-check every path →
    scan every rendered text → check every clobber → only then write. A blocked credential
    or one foreign file aborts the whole export, so a partial write can never leave the
    recipient tool holding half a roster.

    ``confirm_dest`` must be ``True``: we are writing into a directory another tool owns,
    and §5 forbids auto-installing there. ``overwrite=False`` refuses any pre-existing
    target; ``overwrite=True`` replaces only files bearing :data:`PROVENANCE_MARKER` — a
    file we did not write is refused either way.
    """
    if not confirm_dest:
        raise DestNotConfirmed(
            f"export to {dest_dir} requires explicit destination confirmation "
            "(confirm_dest=True) — an external tool's directory is never written implicitly"
        )
    root = Path(dest_dir).expanduser()
    if root.exists() and not root.is_dir():
        raise ExportPathRefused(f"destination is not a directory: {root}")
    root.mkdir(parents=True, exist_ok=True)

    files = fmt.render(entities)
    targets = [(_resolve_target(root, rf.relpath), rf) for rf in files]

    blocked = scan_rendered(files)
    if blocked:
        raise ExportBlocked(blocked)

    for target, rf in targets:
        if target.exists() and not (overwrite and _is_ours(target)):
            hint = (
                "not written by gideon"
                if not _is_ours(target)
                else "pass overwrite=True"
            )
            raise ExportClobberRefused(f"refusing to overwrite {target} ({hint})")

    result = ExportResult(fmt.name, root)
    for target, rf in targets:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rf.text, encoding="utf-8")
        result.written.append(target)
    return result


def export_preview(fmt: ExternalFormat, entities: Sequence[Entity]) -> dict[str, Any]:
    """Look before you write: what an export WOULD produce, without touching the disk.

    Same rails as the write path minus the write, so a UI can show the file list and any
    §2.2 block before asking the user to confirm a destination.
    """
    files = fmt.render(entities)
    blocked = scan_rendered(files)
    return {
        "format": fmt.name,
        "installKind": fmt.installKind,
        "dest": fmt.dest,
        "files": [
            {"path": rf.relpath, "bytes": len(rf.text.encode("utf-8"))} for rf in files
        ],
        "blocked": [
            {"path": b.relpath, "reason": b.reason, "categories": list(b.categories)}
            for b in blocked
        ],
    }
