import { useEffect,useState } from 'react'
import { Button } from '../../../shared/ui/Button'
import ModelViewer from './ModelViewer'
type Ref={slug:string;version:number}
type Receipt={revision:number;model_ref:Ref;source_ref:Ref}
type Assembly={id:string;revision:number;title:string;parts:unknown[];clips:{name:string}[];diagnostics:{mesh_count:number;triangle_count:number;volume_estimate:number;bounds:{min:number[];max:number[]};findings:{code:string;part_ids:string[];message:string}[]};exports:Receipt[]}
const initial={parts:[{id:'base',name:'Base',shape:'box',size:[1,1,1],position:[0,0,0],rotation:[0,0,0],color:'#5599cc',parent_id:null,joint:null}],clips:[]}
const cls='w-full rounded-lg border border-outline bg-surface p-2 text-on-surface'
export default function AssemblyPage({apiBase='/api/capabilities/music/assemblies',modelBase='/api/capabilities/music/models3d/artifacts'}:{apiBase?:string;modelBase?:string}){
 const [rows,setRows]=useState<Assembly[]>([]),[item,setItem]=useState<Assembly|null>(null),[history,setHistory]=useState<Assembly[]>([]),[title,setTitle]=useState(''),[schema,setSchema]=useState(JSON.stringify(initial,null,2)),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState(false),[clip,setClip]=useState(''),[reduced,setReduced]=useState(false)
 async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw new Error(value.message||value.error);return value}
 async function show(value:Assembly){setItem(value);setTitle(value.title);setSchema(JSON.stringify({parts:value.parts,clips:value.clips},null,2));setDirty(false);setPreview(false);setHistory((await request('/'+value.id+'/history')).items)}
 async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{request('?limit=100').then(value=>setRows(value.items)).catch(err=>setError(err.message))},[apiBase])
 async function refresh(){if(!item)return;await show((await request('/'+item.id)).item)}
 const receipt=item?.exports.find(row=>row.revision===item.revision)
 return <section className="mx-auto flex w-full max-w-5xl flex-col gap-4 overflow-auto p-4 text-on-surface"><h1>Procedural assemblies</h1><a href="#/capabilities/music">Repertoire</a><p>Author box, sphere and cylinder parts. Positions and sizes use consistent model units; rotations use radians. Joint clips use degrees. Findings describe geometry, not a physics certification.</p>{error&&<p role="alert">{error}</p>}
 <nav aria-label="Assemblies">{rows.map(row=><Button key={row.id} variant="secondary" onClick={()=>void act(async()=>show((await request('/'+row.id)).item))}>{row.title}</Button>)}</nav>
 {item&&<Button variant="secondary" onClick={()=>{setItem(null);setTitle('');setSchema(JSON.stringify(initial,null,2));setDirty(false);setPreview(false);setHistory([])}}>New assembly</Button>}
 <form className="flex flex-col gap-3" onSubmit={event=>{event.preventDefault();void act(async()=>{const parsed=JSON.parse(schema);const value=(await request(item?'/'+item.id:'',item?'PATCH':'POST',{...parsed,title,...(item?{revision:item.revision}:{})})).item;await show(value);setRows(previous=>[...previous.filter(row=>row.id!==value.id),value])})}}><label>Assembly title<input className={cls} value={title} onChange={event=>{setTitle(event.target.value);setDirty(true)}} required/></label><label>Parts and clips JSON<textarea className={cls+' min-h-80 font-mono'} value={schema} onChange={event=>{setSchema(event.target.value);setDirty(true);setPreview(false)}}/></label><Button type="submit" disabled={busy||!title.trim()}>{item?'Save assembly':'Create assembly'}</Button></form>
 {item&&<><p>Assembly revision {item.revision}</p><h2>Geometry findings</h2><p>{item.diagnostics.mesh_count} parts · {item.diagnostics.triangle_count} triangles · estimated volume {item.diagnostics.volume_estimate.toFixed(3)}</p><p>Bounds {item.diagnostics.bounds.min.join(', ')} to {item.diagnostics.bounds.max.join(', ')}</p>{item.diagnostics.findings.length===0?<p>No current geometry findings.</p>:<ul>{item.diagnostics.findings.map((finding,index)=><li key={index}>{finding.code}: {finding.message} ({finding.part_ids.join(', ')})</li>)}</ul>}
 <div className="flex gap-2">{(['ground','clamp_clips'] as const).map(operation=><Button key={operation} variant="secondary" disabled={busy||dirty} onClick={()=>void act(async()=>show((await request('/'+item.id+'/refine','POST',{revision:item.revision,operations:[operation]})).item))}>{operation==='ground'?'Place on ground':'Clamp clip ranges'}</Button>)}<Button disabled={busy||dirty} onClick={()=>void act(async()=>{await request('/'+item.id+'/export','POST',{revision:item.revision});await refresh()})}>Export assembly</Button></div>{dirty&&<p>Save changes before refinement or export.</p>}
 {receipt&&<><a href={`${modelBase}/${receipt.model_ref.slug}/${receipt.model_ref.version}/raw`} download={`${item.title}.glb`}>Download assembly GLB</a><a href={`${apiBase}/artifacts/${receipt.source_ref.slug}/${receipt.source_ref.version}/source`} download={`${item.title}.js`}>Download runnable Three.js source</a><Button variant="secondary" onClick={()=>setPreview(value=>!value)}>{preview?'Hide model preview':'Preview exported model'}</Button>{preview&&<><label>Assembly animation<select className={cls} value={clip} onChange={event=>setClip(event.target.value)}><option value="">Static pose</option>{item.clips.map(row=><option key={row.name}>{row.name}</option>)}</select></label><label><input type="checkbox" checked={reduced} onChange={event=>setReduced(event.target.checked)}/>Reduce motion</label><ModelViewer artifactRef={receipt.model_ref} artifactBase={modelBase} animationName={clip} reducedMotion={reduced}/></>}</>}
 <h2>Revision history</h2><ol>{history.map(row=><li key={row.revision}>Revision {row.revision}: {row.title} · {row.diagnostics.findings.length} findings</li>)}</ol></>}
 </section>
}
