import { spawn,type ChildProcess } from 'node:child_process'
import { resolve } from 'node:path'
import { afterAll,beforeAll,expect,it } from 'vitest'
import { fireEvent,render,screen,waitFor } from '@testing-library/react'
import DeckPage from './DeckPage'
let server:ChildProcess,apiBase:string,image:{slug:string,version:number}
beforeAll(async()=>{
 const root=resolve(process.cwd(),'../..')
 server=spawn(process.env.GIDEON_TEST_PYTHON||'python3',['checks/runtime/capabilities/music/serve_decks.py'],{cwd:root,env:{...process.env,PYTHONPATH:resolve(root,'runtime')},stdio:['ignore','pipe','pipe']})
 const result=await new Promise<any>((done,reject)=>{
  let output='',errors=''
  server.stderr!.on('data',chunk=>{errors+=String(chunk)})
  server.once('error',reject)
  server.once('exit',code=>reject(new Error(`Deck HTTP exited ${code}: ${errors}`)))
  server.stdout!.on('data',chunk=>{output+=String(chunk);const line=output.split('\n').find(value=>value.startsWith('{'));if(line)done(JSON.parse(line))})
 })
 apiBase=`http://127.0.0.1:${result.port}/api/capabilities/music/decks`;image=result.image
})
afterAll(()=>server?.kill('SIGTERM'))
it('authors a physical deck, selects pinned artwork and downloads real persisted PDF',async()=>{
 const view=render(<DeckPage apiBase={apiBase}/>)
 fireEvent.change(screen.getByLabelText('New deck name'),{target:{value:'Garden cards'}})
 fireEvent.click(screen.getByRole('button',{name:'Create deck'}))
 await screen.findByText('Garden cards · revision 1')
 expect(screen.getByText('0/55 cards with artwork · 0 authored prompts')).toBeInTheDocument()
 expect(screen.getByLabelText('width_mm')).toHaveValue(63.5)
 expect(screen.getByLabelText('height_mm')).toHaveValue(88.9)
 fireEvent.change(screen.getByLabelText('Deck style_notes'),{target:{value:'Botanical ink'}})
 fireEvent.change(screen.getByLabelText('Face orientation'),{target:{value:'one_way'}})
 fireEvent.click(screen.getByRole('button',{name:'Save deck design'}))
 await screen.findByText('Garden cards · revision 2')
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save card'})).not.toBeDisabled())
 fireEvent.change(screen.getByLabelText('Card name'),{target:{value:'Oak Ace'}})
 fireEvent.change(screen.getByLabelText('Card prompt'),{target:{value:'An oak tree'}})
 fireEvent.change(screen.getByLabelText('Artwork artifact slug'),{target:{value:image.slug}})
 fireEvent.click(screen.getByRole('button',{name:'Save card'}))
 await screen.findByText('Garden cards · revision 3')
 expect(screen.getByText('1/55 cards with artwork · 1 authored prompts')).toBeInTheDocument()
 expect(screen.getByRole('img',{name:'Oak Ace artwork'})).toHaveAttribute('src',`${apiBase}/artifacts/${image.slug}/${image.version}/raw`)
 await waitFor(()=>expect(screen.getByRole('button',{name:'Export print deck'})).not.toBeDisabled())
 fireEvent.click(screen.getByRole('button',{name:'Export print deck'}))
 const link=await screen.findByRole('link',{name:'Download card PDF'})
 const href=link.getAttribute('href')!
 const response=await fetch(href)
 expect(response.status).toBe(200)
 expect(response.headers.get('Content-Type')).toContain('application/pdf')
 const bytes=new Uint8Array(await response.arrayBuffer())
 expect(new TextDecoder().decode(bytes.slice(0,5))).toBe('%PDF-')
 const manifest=await(await fetch(screen.getByRole('link',{name:'Download deck manifest'}).getAttribute('href')!)).json()
 expect(manifest.cards).toHaveLength(55)
 expect(manifest.cards[0].artifact_ref).toEqual(image)
 expect(manifest.style_notes).toBe('Botanical ink')
 expect(manifest.orientation).toBe('one_way')
 view.unmount()
 render(<DeckPage apiBase={apiBase}/>)
 fireEvent.click(await screen.findByRole('button',{name:'Garden cards'}))
 await screen.findByText('Garden cards · revision 3')
 expect(screen.getByRole('link',{name:'Download card PDF'})).toHaveAttribute('href',href)
})
it('queues actual media work without claiming artwork, rejects unrelated adoption and invalid geometry',async()=>{
 render(<DeckPage apiBase={apiBase}/>)
 fireEvent.click(await screen.findByRole('button',{name:'Garden cards'}))
 await screen.findByText('Garden cards · revision 3')
 await waitFor(()=>expect(screen.getByRole('button',{name:'Queue card artwork'})).not.toBeDisabled())
 fireEvent.click(screen.getByRole('button',{name:'Queue card artwork'}))
 await screen.findByText(/spades-A: queued/)
 expect(screen.getByText('1/55 cards with artwork · 1 authored prompts')).toBeInTheDocument()
 fireEvent.change(screen.getByLabelText('Completed media job ID'),{target:{value:'not-a-linked-job'}})
 await waitFor(()=>expect(screen.getByRole('button',{name:'Adopt completed artwork'})).not.toBeDisabled())
 fireEvent.click(screen.getByRole('button',{name:'Adopt completed artwork'}))
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Job does not belong to this card'))
 fireEvent.change(screen.getByLabelText('width_mm'),{target:{value:1}})
 fireEvent.click(screen.getByRole('button',{name:'Save deck design'}))
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Invalid physical card dimensions'))
 const deck=(await(await fetch(apiBase)).json()).items[0]
 expect(deck.revision).toBe(3)
 expect(deck.width_mm).toBe(63.5)
 expect(deck.completion.artwork).toBe(1)
})
