import { Select, TextInput } from '../../../shared/ui/forms'
import { BUSY_REASON } from '../../../shared/ui/unavailable'
import { useEffect,useState } from 'react'
import {Button} from '../../../shared/ui/Button'
export default function DeckAssist({apiBase,item,onApplied}:{apiBase:string,item:any,onApplied:(item:any)=>void}){
  const [providers,setProviders]=useState<any[]>([]),[provider,setProvider]=useState(''),[proposals,setProposals]=useState<any[]>([]),[sample,setSample]=useState(''),[sampleVersion,setSampleVersion]=useState(1),[universe,setUniverse]=useState(''),[universeRevision,setUniverseRevision]=useState(1),[keys,setKeys]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  async function request(path:string,body?:unknown){const response=await fetch(apiBase+path,{method:body===undefined?'GET':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);return result}
  async function load(){const [models,rows]=await Promise.all([request('/assist/providers'),request('/'+item.id+'/assist')]);setProviders(models.items);setProvider(current=>current||models.items[0]?.name||'');setProposals(rows.items)}
  useEffect(()=>{load().catch(e=>setError(e.message))},[item.id])
  async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const selected=providers.find(row=>row.name===provider)
  return <fieldset disabled={busy} className="space-y-3"><legend>Model-assisted card design</legend><p>Model proposals are reviewed before applying. Universe casting uses a pinned saved canon revision; it cannot invent new canon identities.</p>{error&&<p role="alert">{error}</p>}<label>Design model<Select value={String(provider)} onChange={(nextValue) => setProvider(nextValue)} options={[({ value: "", label: "Choose configured model" }), ...providers.map(row => ({ value: String(row.name), label: String(row.name) + " \u00B7 " + String(row.model) }))]}/></label>{!providers.length&&<p>No configured model is available for design assistance.</p>}
  <label>Analysis image slug<TextInput value={sample} onChange={(nextValue) => setSample(nextValue)}/></label><label>Analysis image version<TextInput type="number" min={1} value={String(sampleVersion)} onChange={(nextValue) => setSampleVersion(Number(nextValue))}/></label><Button disabled={!selected?.vision} onClick={()=>run(async()=>{await request('/'+item.id+'/assist/analyze',{revision:item.revision,request_id:crypto.randomUUID(),provider_name:provider,sample_ref:{slug:sample,version:sampleVersion}})})} disabledReason={busy ? BUSY_REASON : !selected?.vision ? "Choose a vision-capable provider before analyzing a card sample." : undefined}>Analyze card sample</Button>
  <label>Universe ID<TextInput value={universe} onChange={(nextValue) => setUniverse(nextValue)}/></label><label>Universe revision<TextInput type="number" min={1} value={String(universeRevision)} onChange={(nextValue) => setUniverseRevision(Number(nextValue))}/></label><label>Card keys separated by commas<TextInput value={keys} onChange={(nextValue) => setKeys(nextValue)}/></label><p>Available keys: {item.cards.map((row:any)=>row.key).join(', ')}</p><Button disabled={!provider} onClick={()=>run(async()=>{await request('/'+item.id+'/assist/prompts',{revision:item.revision,request_id:crypto.randomUUID(),provider_name:provider,card_keys:keys.split(',').map(value=>value.trim()).filter(Boolean),universe_ref:universe?{id:universe,revision:universeRevision}:null})})} disabledReason={busy ? BUSY_REASON : !provider ? "Select a provider before generating card prompts and casting." : undefined}>Generate card prompts and casting</Button>
  <Button onClick={()=>run(load)}>Refresh design proposals</Button>{proposals.map((row,index)=><article key={row.id}><h3>{row.kind} · {row.status}</h3><p>Deck revision {row.snapshot_revision} · {row.provider} · {row.model}</p>{row.error&&<p>{row.error}</p>}{row.result&&<pre>{JSON.stringify(row.result,null,2)}</pre>}<Button ariaLabel={`Apply ${row.kind} proposal ${index + 1} for ${item.name || 'deck'} revision ${row.snapshot_revision}`} disabled={row.status!=='succeeded'||row.applied_revision!==null||row.snapshot_revision!==item.revision} onClick={()=>run(async()=>{const result=await request('/'+item.id+'/assist/'+row.id+'/apply',{revision:item.revision});onApplied(result.item)})} disabledReason={busy ? BUSY_REASON : row.status !== 'succeeded' ? 'The proposal must succeed before it can be applied.' : row.applied_revision !== null ? 'This proposal has already been applied.' : row.snapshot_revision !== item.revision ? 'Generate a proposal for the current deck revision before applying.' : undefined}>Apply proposal</Button>{row.applied_revision!==null&&<p>Applied at revision {row.applied_revision}</p>}</article>)}</fieldset>
}
