import { BUSY_REASON } from '../../../shared/ui/unavailable'
import DeckAssist from './DeckAssist'
import {Button} from '../../../shared/ui/Button'
import {ListScaffold} from '../../../shared/ui/ListScaffold'
import { Checkbox, TextInput, Select, TextArea } from '../../../shared/ui/forms'
import { useEffect,useState } from 'react'
export default function DeckPage({apiBase='/api/capabilities/music/decks'}:{apiBase?:string}){
 const [items,setItems]=useState<any[]>([]),[item,setItem]=useState<any>(null),[name,setName]=useState(''),[kind,setKind]=useState('playing'),[key,setKey]=useState(''),[card,setCard]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[jobs,setJobs]=useState<any[]>([]),[jobId,setJobId]=useState('')
 const [slug,setSlug]=useState(''),[version,setVersion]=useState(1),[refs,setRefs]=useState('[]'),[context,setContext]=useState('null'),[size,setSize]=useState('')
 async function request(path:string,method='GET',body?:unknown){const response=await fetch(apiBase+path,{method,credentials:'include',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);return result}
 async function list(){setItems((await request('')).items)}
 useEffect(()=>{list().catch(e=>setError(e.message))},[])
 function select(value:any,selectedKey?:string){setItem(value);const selected=value.cards.find((row:any)=>row.key===(selectedKey||key))||value.cards[0];setKey(selected.key);setCard({...selected});setSlug(selected.artifact_ref?.slug||'');setVersion(selected.artifact_ref?.version||1);setRefs(JSON.stringify(value.sample_refs));setContext(JSON.stringify(value.context_ref))}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await list()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const receipt=item?.exports.find((row:any)=>row.revision===item.revision)
 return <ListScaffold title="Card deck designer" bodyClassName="mx-auto w-full max-w-5xl space-y-l px-l py-xl"><p data-type="body-m" className="max-w-[48rem] text-on-surface-low">Playing decks contain 54 faces and a shared back; tarot decks contain 78 faces and a shared back. Print exports are individual physical card pages with crop marks, not duplex printer imposition.</p>{error&&<p role="alert">{error}</p>}
 <label>New deck name<TextInput value={name} onChange={(nextValue) => setName(nextValue)}/></label><label>Deck kind<Select value={String(kind)} onChange={(nextValue) => setKind(nextValue)} options={[({ value: "playing", label: "Playing" }), ({ value: "tarot", label: "Tarot" })]}/></label><Button disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={()=>run(async()=>select((await request('','POST',{name,kind})).item))}>Create deck</Button>
 <nav>{items.map(row=><Button key={row.id} onClick={()=>run(async()=>select((await request('/'+row.id)).item))}>{row.name}{row.archived?' (archived)':''}</Button>)}</nav>
 {item&&<><h2>{item.name} · revision {item.revision}</h2><p>{item.completion.artwork}/{item.completion.total} cards with artwork · {item.completion.prompted} authored prompts</p><fieldset disabled={busy}><legend>Deck design</legend>{['name','description','style_notes','layout_prompt','negative_prompt'].map(field=><label key={field}>{field}<TextInput ariaLabel={'Deck ' + field} value={item[field]} onChange={(nextValue) => setItem({ ...item, [field]: nextValue })}/></label>)}<label>Face orientation<Select value={String(item.orientation)} onChange={(nextValue) => setItem({ ...item, orientation: nextValue })} options={[({ value: "two_way", label: "Two-way indices" }), ({ value: "one_way", label: "One-way indices" })]}/></label>
 {['width_mm','height_mm','bleed_mm','safe_mm'].map(field=><label key={field}>{field}<TextInput ariaLabel={field} type="number" step="0.01" value={String(item[field])} onChange={(nextValue) => setItem({ ...item, [field]: Number(nextValue) })}/></label>)}<label className="flex items-center gap-s"><Checkbox ariaLabel="Archived" checked={item.archived} onChange={archived=>setItem({...item,archived})}/>Archived</label><label>Style sample references JSON<TextArea value={refs} onChange={(nextValue) => setRefs(nextValue)} className="min-h-24"/></label><label>Context reference JSON<TextArea value={context} onChange={(nextValue) => setContext(nextValue)} className="min-h-24"/></label><Button onClick={()=>run(async()=>{const data:any={revision:item.revision,sample_refs:JSON.parse(refs),context_ref:JSON.parse(context)};for(const field of ['name','description','style_notes','layout_prompt','negative_prompt','orientation','width_mm','height_mm','bleed_mm','safe_mm','archived'])data[field]=item[field];select((await request('/'+item.id,'PATCH',data)).item)})}>Save deck design</Button></fieldset>
 <label>Selected card<Select value={String(key)} onChange={(nextValue) => select(item, nextValue)} options={[...item.cards.map((row: any) => ({ value: String(row.key), label: String(row.name) }))]}/></label>{card&&<fieldset disabled={busy}><legend>Card artwork</legend><p>{card.group} · {card.rank}</p>{['name','prompt','negative_prompt'].map(field=><label key={field}>{field}<TextInput ariaLabel={'Card ' + field} value={card[field]} onChange={(nextValue) => setCard({ ...card, [field]: nextValue })}/></label>)}<label>Artwork artifact slug<TextInput value={slug} onChange={(nextValue) => setSlug(nextValue)}/></label><label>Artwork version<TextInput type="number" min={1} value={String(version)} onChange={(nextValue) => setVersion(Number(nextValue))}/></label><Button onClick={()=>run(async()=>select((await request('/'+item.id+'/cards/'+key,'PATCH',{revision:item.revision,name:card.name,prompt:card.prompt,negative_prompt:card.negative_prompt,artifact_ref:slug?{slug,version}:null})).item))}>Save card</Button>
 {card.artifact_ref&&<img alt={card.name+' artwork'} src={`${apiBase}/artifacts/${card.artifact_ref.slug}/${card.artifact_ref.version}/raw`} style={{maxHeight:300,aspectRatio:`${item.width_mm}/${item.height_mm}`,objectFit:'contain'}}/>}<label>Provider image size<TextInput value={size} onChange={(nextValue) => setSize(nextValue)}/></label><Button onClick={()=>run(async()=>setJobs((await request('/'+item.id+'/generate','POST',{revision:item.revision,request_id:crypto.randomUUID(),card_keys:[key],size,controls:{}})).jobs))}>Queue card artwork</Button><p>Rendering uses the configured image provider and media worker. A queued job is not completed artwork.</p>{jobs.map(row=><p key={row.job_id}>{row.card_key}: {row.status} · {row.job_id}</p>)}<label>Completed media job ID<TextInput value={jobId} onChange={(nextValue) => setJobId(nextValue)}/></label><Button onClick={()=>run(async()=>select((await request('/'+item.id+'/cards/'+key+'/adopt','POST',{revision:item.revision,job_id:jobId})).item))}>Adopt completed artwork</Button></fieldset>}
 <DeckAssist apiBase={apiBase} item={item} onApplied={select}/><Button disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={()=>run(async()=>{await request('/'+item.id+'/export','POST',{revision:item.revision});select((await request('/'+item.id)).item)})}>Export print deck</Button>{receipt&&<><a href={`${apiBase}/artifacts/${receipt.pdf_ref.slug}/${receipt.pdf_ref.version}/raw`}>Download card PDF</a><a href={`${apiBase}/artifacts/${receipt.manifest_ref.slug}/${receipt.manifest_ref.version}/raw`}>Download deck manifest</a></>}
 </>}
 </ListScaffold>
}
