import { useEffect,useState } from 'react'
export default function DeckAssist({apiBase,item,onApplied}:{apiBase:string,item:any,onApplied:(item:any)=>void}){
 const [providers,setProviders]=useState<any[]>([]),[provider,setProvider]=useState(''),[proposals,setProposals]=useState<any[]>([]),[sample,setSample]=useState(''),[sampleVersion,setSampleVersion]=useState(1),[universe,setUniverse]=useState(''),[universeRevision,setUniverseRevision]=useState(1),[keys,setKeys]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function request(path:string,body?:unknown){const response=await fetch(apiBase+path,{method:body===undefined?'GET':'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);return result}
 async function load(){const [models,rows]=await Promise.all([request('/assist/providers'),request('/'+item.id+'/assist')]);setProviders(models.items);setProvider(current=>current||models.items[0]?.name||'');setProposals(rows.items)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[item.id])
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const selected=providers.find(row=>row.name===provider)
 return <fieldset disabled={busy} className="space-y-3"><legend>Model-assisted card design</legend><p>Model proposals are reviewed before applying. Universe casting uses a pinned saved canon revision; it cannot invent new canon identities.</p>{error&&<p role="alert">{error}</p>}<label>Design model<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="">Choose configured model</option>{providers.map(row=><option key={row.name} value={row.name}>{row.name} · {row.model}</option>)}</select></label>{!providers.length&&<p>No configured model is available for design assistance.</p>}
 <label>Analysis image slug<input value={sample} onChange={e=>setSample(e.target.value)}/></label><label>Analysis image version<input type="number" min={1} value={sampleVersion} onChange={e=>setSampleVersion(Number(e.target.value))}/></label><button disabled={!selected?.vision} onClick={()=>run(async()=>{await request('/'+item.id+'/assist/analyze',{revision:item.revision,request_id:crypto.randomUUID(),provider_name:provider,sample_ref:{slug:sample,version:sampleVersion}})})}>Analyze card sample</button>
 <label>Universe ID<input value={universe} onChange={e=>setUniverse(e.target.value)}/></label><label>Universe revision<input type="number" min={1} value={universeRevision} onChange={e=>setUniverseRevision(Number(e.target.value))}/></label><label>Card keys separated by commas<input value={keys} onChange={e=>setKeys(e.target.value)}/></label><p>Available keys: {item.cards.map((row:any)=>row.key).join(', ')}</p><button disabled={!provider} onClick={()=>run(async()=>{await request('/'+item.id+'/assist/prompts',{revision:item.revision,request_id:crypto.randomUUID(),provider_name:provider,card_keys:keys.split(',').map(value=>value.trim()).filter(Boolean),universe_ref:universe?{id:universe,revision:universeRevision}:null})})}>Generate card prompts and casting</button>
 <button onClick={()=>run(load)}>Refresh design proposals</button>{proposals.map(row=><article key={row.id}><h3>{row.kind} · {row.status}</h3><p>Deck revision {row.snapshot_revision} · {row.provider} · {row.model}</p>{row.error&&<p>{row.error}</p>}{row.result&&<pre>{JSON.stringify(row.result,null,2)}</pre>}<button disabled={row.status!=='succeeded'||row.applied_revision!==null||row.snapshot_revision!==item.revision} onClick={()=>run(async()=>{const result=await request('/'+item.id+'/assist/'+row.id+'/apply',{revision:item.revision});onApplied(result.item)})}>Apply proposal</button>{row.applied_revision!==null&&<p>Applied at revision {row.applied_revision}</p>}</article>)}</fieldset>
}
