import DeckAssist from './DeckAssist'
import { useEffect,useState } from 'react'
export default function DeckPage({apiBase='/api/capabilities/music/decks'}:{apiBase?:string}){
 const [items,setItems]=useState<any[]>([]),[item,setItem]=useState<any>(null),[name,setName]=useState(''),[kind,setKind]=useState('playing'),[key,setKey]=useState(''),[card,setCard]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[jobs,setJobs]=useState<any[]>([]),[jobId,setJobId]=useState('')
 const [slug,setSlug]=useState(''),[version,setVersion]=useState(1),[refs,setRefs]=useState('[]'),[context,setContext]=useState('null'),[size,setSize]=useState('')
 async function request(path:string,method='GET',body?:unknown){const response=await fetch(apiBase+path,{method,credentials:'include',headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);return result}
 async function list(){setItems((await request('')).items)}
 useEffect(()=>{list().catch(e=>setError(e.message))},[])
 function select(value:any,selectedKey?:string){setItem(value);const selected=value.cards.find((row:any)=>row.key===(selectedKey||key))||value.cards[0];setKey(selected.key);setCard({...selected});setSlug(selected.artifact_ref?.slug||'');setVersion(selected.artifact_ref?.version||1);setRefs(JSON.stringify(value.sample_refs));setContext(JSON.stringify(value.context_ref))}
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await list()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const receipt=item?.exports.find((row:any)=>row.revision===item.revision)
 return <section className="p-4 space-y-4"><h1>Card deck designer</h1><p>Playing decks contain 54 faces and a shared back; tarot decks contain 78 faces and a shared back. Print exports are individual physical card pages with crop marks, not duplex printer imposition.</p>{error&&<p role="alert">{error}</p>}
 <label>New deck name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Deck kind<select value={kind} onChange={e=>setKind(e.target.value)}><option value="playing">Playing</option><option value="tarot">Tarot</option></select></label><button disabled={busy} onClick={()=>run(async()=>select((await request('','POST',{name,kind})).item))}>Create deck</button>
 <nav>{items.map(row=><button key={row.id} onClick={()=>run(async()=>select((await request('/'+row.id)).item))}>{row.name}{row.archived?' (archived)':''}</button>)}</nav>
 {item&&<><h2>{item.name} · revision {item.revision}</h2><p>{item.completion.artwork}/{item.completion.total} cards with artwork · {item.completion.prompted} authored prompts</p><fieldset disabled={busy}><legend>Deck design</legend>{['name','description','style_notes','layout_prompt','negative_prompt'].map(field=><label key={field}>{field}<input aria-label={'Deck '+field} value={item[field]} onChange={e=>setItem({...item,[field]:e.target.value})}/></label>)}<label>Face orientation<select value={item.orientation} onChange={e=>setItem({...item,orientation:e.target.value})}><option value="two_way">Two-way indices</option><option value="one_way">One-way indices</option></select></label>
 {['width_mm','height_mm','bleed_mm','safe_mm'].map(field=><label key={field}>{field}<input aria-label={field} type="number" step="0.01" value={item[field]} onChange={e=>setItem({...item,[field]:Number(e.target.value)})}/></label>)}<label>Archived<input type="checkbox" checked={item.archived} onChange={e=>setItem({...item,archived:e.target.checked})}/></label><label>Style sample references JSON<textarea value={refs} onChange={e=>setRefs(e.target.value)}/></label><label>Context reference JSON<textarea value={context} onChange={e=>setContext(e.target.value)}/></label><button onClick={()=>run(async()=>{const data:any={revision:item.revision,sample_refs:JSON.parse(refs),context_ref:JSON.parse(context)};for(const field of ['name','description','style_notes','layout_prompt','negative_prompt','orientation','width_mm','height_mm','bleed_mm','safe_mm','archived'])data[field]=item[field];select((await request('/'+item.id,'PATCH',data)).item)})}>Save deck design</button></fieldset>
 <label>Selected card<select value={key} onChange={e=>select(item,e.target.value)}>{item.cards.map((row:any)=><option key={row.key} value={row.key}>{row.name}</option>)}</select></label>{card&&<fieldset disabled={busy}><legend>Card artwork</legend><p>{card.group} · {card.rank}</p>{['name','prompt','negative_prompt'].map(field=><label key={field}>{field}<input aria-label={'Card '+field} value={card[field]} onChange={e=>setCard({...card,[field]:e.target.value})}/></label>)}<label>Artwork artifact slug<input value={slug} onChange={e=>setSlug(e.target.value)}/></label><label>Artwork version<input type="number" min={1} value={version} onChange={e=>setVersion(Number(e.target.value))}/></label><button onClick={()=>run(async()=>select((await request('/'+item.id+'/cards/'+key,'PATCH',{revision:item.revision,name:card.name,prompt:card.prompt,negative_prompt:card.negative_prompt,artifact_ref:slug?{slug,version}:null})).item))}>Save card</button>
 {card.artifact_ref&&<img alt={card.name+' artwork'} src={`${apiBase}/artifacts/${card.artifact_ref.slug}/${card.artifact_ref.version}/raw`} style={{maxHeight:300,aspectRatio:`${item.width_mm}/${item.height_mm}`,objectFit:'contain'}}/>}<label>Provider image size<input value={size} onChange={e=>setSize(e.target.value)}/></label><button onClick={()=>run(async()=>setJobs((await request('/'+item.id+'/generate','POST',{revision:item.revision,request_id:crypto.randomUUID(),card_keys:[key],size,controls:{}})).jobs))}>Queue card artwork</button><p>Rendering uses the configured image provider and media worker. A queued job is not completed artwork.</p>{jobs.map(row=><p key={row.job_id}>{row.card_key}: {row.status} · {row.job_id}</p>)}<label>Completed media job ID<input value={jobId} onChange={e=>setJobId(e.target.value)}/></label><button onClick={()=>run(async()=>select((await request('/'+item.id+'/cards/'+key+'/adopt','POST',{revision:item.revision,job_id:jobId})).item))}>Adopt completed artwork</button></fieldset>}
 <DeckAssist apiBase={apiBase} item={item} onApplied={select}/><button disabled={busy} onClick={()=>run(async()=>{await request('/'+item.id+'/export','POST',{revision:item.revision});select((await request('/'+item.id)).item)})}>Export print deck</button>{receipt&&<><a href={`${apiBase}/artifacts/${receipt.pdf_ref.slug}/${receipt.pdf_ref.version}/raw`}>Download card PDF</a><a href={`${apiBase}/artifacts/${receipt.manifest_ref.slug}/${receipt.manifest_ref.version}/raw`}>Download deck manifest</a></>}
 </>}
 </section>
}
