import { useEffect,useState } from 'react'
export default function ListeningPage({apiBase='/api/capabilities/music/listening',artifactBase='/api/artifacts'}:{apiBase?:string,artifactBase?:string}){
 const [events,setEvents]=useState<any[]>([]),[stats,setStats]=useState<any>({}),[playlists,setPlaylists]=useState<any[]>([]),[playlist,setPlaylist]=useState<any>(null)
 const [config,setConfig]=useState<any>(null),[ready,setReady]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<any>(null)
 const [format,setFormat]=useState('spotify_extended'),[account,setAccount]=useState(''),[slug,setSlug]=useState(''),[version,setVersion]=useState(1),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[ids,setIds]=useState('')
 const [client,setClient]=useState(''),[redirect,setRedirect]=useState('http://127.0.0.1:8765/callback'),[authorization,setAuthorization]=useState<any>(null),[callback,setCallback]=useState('')
 async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'include',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);return result}
 async function load(){const [history,summary,lists,connection,availability]=await Promise.all([request(`/history?q=${encodeURIComponent(query)}&offset=${offset}&limit=25`),request('/stats'),request('/playlists'),request('/spotify/config'),request('/spotify/readiness')]);setEvents(history.items);setTotal(history.total);setStats(summary);setPlaylists(lists.items);setConfig(connection.config);setReady(availability)}
 useEffect(()=>{load().catch(e=>setError(e.message))},[query,offset])
 async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await load()}catch(e){setError(String((e as Error).message))}finally{setBusy(false)}}
 return <section className="space-y-4 p-4"><h1>Listening history and playlists</h1><p>Import Spotify privacy exports or synchronize a connected account. API plays have unknown listened duration. JSON files are limited to 1 MiB.</p>{error&&<p role="alert">{error}</p>}
 <fieldset disabled={busy}><legend>Import listening evidence</legend><label>Account label<input value={account} onChange={e=>setAccount(e.target.value)}/></label><label>Export format<select value={format} onChange={e=>setFormat(e.target.value)}>{['spotify_extended','spotify_legacy','spotify_playlists','spotify_api'].map(value=><option key={value}>{value}</option>)}</select></label>
 <label>Upload JSON<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{if(file.size>1048576)throw new Error('JSON exceeds 1 MiB; split the export into smaller files');const content=await file.text();JSON.parse(content);const response=await fetch(artifactBase,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,kind:'json',source:'import',content})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Upload failed');const artifact=body.artifact||body;setSlug(artifact.slug);setVersion(artifact.version)})}}/></label>
 <label>JSON artifact slug<input value={slug} onChange={e=>setSlug(e.target.value)}/></label><label>Artifact version<input type="number" min={1} value={version} onChange={e=>setVersion(Number(e.target.value))}/></label><button onClick={()=>run(async()=>setReceipt(await request('/imports','POST',{request_id:crypto.randomUUID(),account_label:account,format,artifact_ref:{slug,version}})))}>Import evidence</button></fieldset>
 {receipt&&<p role="status">Imported {receipt.added} events; {receipt.duplicates} duplicates; {receipt.skipped} skipped.</p>}
 <p>{stats.event_count||0} events · {stats.ms_played||0} known milliseconds · {stats.unknown_duration_count||0} unknown durations</p><ul>{stats.top_artists?.map((row:any)=><li key={row.artist}>{row.artist}: {row.event_count} plays</li>)}</ul>
 <label>Search listening history<input value={query} onChange={e=>{setQuery(e.target.value);setOffset(0)}}/></label><table><thead><tr><th>Track</th><th>Artist</th><th>Time</th><th>Listened milliseconds</th></tr></thead><tbody>{events.map(row=><tr key={row.id}><td>{row.title}</td><td>{row.artist}</td><td>{row.ended_at||row.played_at} ({row.timestamp_semantics})</td><td>{row.ms_played===null?'Unknown':row.ms_played}</td></tr>)}</tbody></table><button disabled={!offset} onClick={()=>setOffset(offset-25)}>Previous history</button><button disabled={offset+25>=total} onClick={()=>setOffset(offset+25)}>Next history</button>
 <h2>Playlists</h2>{playlists.map(row=><button key={row.playlist_id} onClick={()=>run(async()=>setPlaylist((await request('/playlists/'+row.playlist_id)).item))}>{row.name}</button>)}{playlist&&<><h3>{playlist.current.name}</h3><label>Playlist snapshot<select value={playlist.current.id} onChange={e=>setPlaylist({...playlist,current:playlist.snapshots.find((row:any)=>row.id===e.target.value)})}>{playlist.snapshots.map((row:any)=><option key={row.id} value={row.id}>{row.modified_at||row.id.slice(0,12)}</option>)}</select></label><ol>{playlist.current.tracks.map((row:any,index:number)=><li key={index}>{row.title} — {row.artist}</li>)}</ol></>}
 <h2>Spotify connection</h2>{config&&<fieldset disabled={busy}><label>Enable Spotify<input type="checkbox" checked={config.enabled} onChange={e=>setConfig({...config,enabled:e.target.checked})}/></label><label>Credential name<input value={config.credential_name} onChange={e=>setConfig({...config,credential_name:e.target.value})}/></label><label>Connection label<input value={config.account_label} onChange={e=>setConfig({...config,account_label:e.target.value})}/></label><button onClick={()=>run(async()=>{setConfig((await request('/spotify/config','PATCH',config)).config)})}>Save Spotify connection</button><p>{ready?.ready_to_sync?'Credential available; remote account unverified':'Spotify connection unavailable'}</p><label>Playlist IDs<input value={ids} onChange={e=>setIds(e.target.value)}/></label><button onClick={()=>run(async()=>{const result=await request('/spotify/sync','POST',{request_id:crypto.randomUUID(),playlist_ids:ids.split(',').map(value=>value.trim()).filter(Boolean)});setReceipt(result.import_receipt)})}>Synchronize Spotify</button></fieldset>}
 <fieldset disabled={busy}><legend>Authorize Spotify with PKCE</legend><label>Spotify client ID<input value={client} onChange={e=>setClient(e.target.value)}/></label><label>Registered redirect URI<input value={redirect} onChange={e=>setRedirect(e.target.value)}/></label><button onClick={()=>run(async()=>setAuthorization(await request('/spotify/authorize','POST',{client_id:client,redirect_uri:redirect})))}>Create authorization link</button>{authorization&&<a href={authorization.authorization_url} target="_blank" rel="noreferrer">Authorize on Spotify</a>}<p>After consent, paste the complete redirected URL here to finish the connection.</p><label>Redirected URL<input value={callback} onChange={e=>setCallback(e.target.value)}/></label><button onClick={()=>run(async()=>{const url=new URL(callback);await request('/spotify/complete','POST',{state:url.searchParams.get('state'),code:url.searchParams.get('code')});setCallback('');setAuthorization(null)})}>Complete Spotify authorization</button></fieldset>
 </section>
}
