import { spawn,type ChildProcess } from 'node:child_process'
import { resolve } from 'node:path'
import { afterAll,beforeAll,expect,it } from 'vitest'
import { fireEvent,render,screen,waitFor } from '@testing-library/react'
import ListeningPage from './ListeningPage'
let server:ChildProcess,apiBase:string
let history:{slug:string,version:number},playlists:{slug:string,version:number}
beforeAll(async()=>{
 const root=resolve(process.cwd(),'../..')
 server=spawn(process.env.GIDEON_TEST_PYTHON||'python3',['checks/runtime/capabilities/music/serve_listening.py'],{cwd:root,env:{...process.env,PYTHONPATH:resolve(root,'runtime')},stdio:['ignore','pipe','pipe']})
 const result=await new Promise<any>((done,reject)=>{
  let output='',errors=''
  server.stderr!.on('data',chunk=>{errors+=String(chunk)})
  server.once('error',reject)
  server.once('exit',code=>reject(new Error(`Listening HTTP exited ${code}: ${errors}`)))
  server.stdout!.on('data',chunk=>{output+=String(chunk);const line=output.split('\n').find(value=>value.startsWith('{'));if(line)done(JSON.parse(line))})
 })
 apiBase=`http://127.0.0.1:${result.port}/api/capabilities/music/listening`
 history=result.history;playlists=result.playlists
})
afterAll(()=>server?.kill('SIGTERM'))
it('imports pinned privacy evidence and displays precise counts and ordered duplicate playlist tracks',async()=>{
 render(<ListeningPage apiBase={apiBase}/>)
 await screen.findByLabelText('Credential name')
 fireEvent.change(screen.getByLabelText('Account label'),{target:{value:'UI owner'}})
 fireEvent.change(screen.getByLabelText('JSON artifact slug'),{target:{value:history.slug}})
 fireEvent.click(screen.getByRole('button',{name:'Import evidence'}))
 await screen.findByText('Imported 1 events; 0 duplicates; 1 skipped.')
 await screen.findByText('Measured song')
 expect(screen.getByText('Actual artist')).toBeInTheDocument()
 expect(screen.getByText('12500')).toBeInTheDocument()
 expect(screen.getByText('2026-01-02T03:04:05+00:00 (ended_at)')).toBeInTheDocument()
 await waitFor(()=>expect(screen.getByRole('button',{name:'Import evidence'})).not.toBeDisabled())
 fireEvent.click(screen.getByRole('button',{name:'Import evidence'}))
 await screen.findByText('Imported 0 events; 1 duplicates; 1 skipped.')
 fireEvent.change(screen.getByLabelText('Search listening history'),{target:{value:'No match'}})
 await waitFor(()=>expect(screen.queryByText('Measured song')).not.toBeInTheDocument())
 fireEvent.change(screen.getByLabelText('Search listening history'),{target:{value:''}})
 await screen.findByText('Measured song')
 fireEvent.change(screen.getByLabelText('Export format'),{target:{value:'spotify_playlists'}})
 fireEvent.change(screen.getByLabelText('JSON artifact slug'),{target:{value:playlists.slug}})
 fireEvent.click(screen.getByRole('button',{name:'Import evidence'}))
 const list=await screen.findByRole('button',{name:'Practice'})
 fireEvent.click(list)
 await screen.findByLabelText('Playlist snapshot')
 expect(screen.getAllByText('One — First')).toHaveLength(2)
 expect(screen.getByLabelText('Playlist snapshot')).toHaveTextContent('2026-01-01')
 expect(screen.getByRole('button',{name:'Previous history'})).toBeDisabled()
 expect(screen.getByRole('button',{name:'Next history'})).toBeDisabled()
})
it('persists connection configuration, refuses absent credentials, and builds actual PKCE authorization URL',async()=>{
 render(<ListeningPage apiBase={apiBase}/>)
 await screen.findByLabelText('Credential name')
 fireEvent.change(screen.getByLabelText('Credential name'),{target:{value:'spotify-ui'}})
 fireEvent.change(screen.getByLabelText('Connection label'),{target:{value:'Personal'}})
 fireEvent.click(screen.getByLabelText('Enable Spotify'))
 fireEvent.click(screen.getByRole('button',{name:'Save Spotify connection'}))
 await waitFor(()=>expect(screen.getByRole('button',{name:'Save Spotify connection'})).not.toBeDisabled())
 const saved=await(await fetch(apiBase+'/spotify/config')).json()
 expect(saved.config.credential_name).toBe('spotify-ui')
 expect(saved.config.enabled).toBe(true)
 expect(saved.config.revision).toBe(1)
 fireEvent.click(screen.getByRole('button',{name:'Synchronize Spotify'}))
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Available named OAuth connection required'))
 expect(screen.getByText('Spotify connection unavailable')).toBeInTheDocument()
 fireEvent.change(screen.getByLabelText('Spotify client ID'),{target:{value:'registered-client'}})
 fireEvent.click(screen.getByRole('button',{name:'Create authorization link'}))
 const link=await screen.findByRole('link',{name:'Authorize on Spotify'})
 const url=new URL(link.getAttribute('href')!)
 expect(url.origin).toBe('https://accounts.spotify.com')
 expect(url.searchParams.get('client_id')).toBe('registered-client')
 expect(url.searchParams.get('code_challenge_method')).toBe('S256')
 expect(url.searchParams.get('state')!.length).toBeGreaterThan(40)
 fireEvent.change(screen.getByLabelText('Redirected URL'),{target:{value:'http://127.0.0.1:8765/callback?state=unknown&code=unissued'}})
 fireEvent.click(screen.getByRole('button',{name:'Complete Spotify authorization'}))
 await waitFor(()=>expect(screen.getByRole('alert')).toHaveTextContent('Unknown or consumed OAuth state'))
 const ready=await(await fetch(apiBase+'/spotify/readiness')).json()
 expect(ready.credential_available).toBe(false)
 expect(ready.remote_status).toBe('unverified')
})
