import { Table, THead, Th, Td } from '../../../shared/ui/Table'
import { useEffect,useState } from 'react'
import {Button} from '../../../shared/ui/Button'
import {ListScaffold} from '../../../shared/ui/ListScaffold'
import { Checkbox, TextInput, Select } from '../../../shared/ui/forms'
export default function ListeningPage({apiBase='/api/capabilities/music/listening',artifactBase='/api/artifacts'}:{apiBase?:string,artifactBase?:string}){
  const [events,setEvents]=useState<any[]>([]),[stats,setStats]=useState<any>({}),[playlists,setPlaylists]=useState<any[]>([]),[playlist,setPlaylist]=useState<any>(null)
  const [config,setConfig]=useState<any>(null),[ready,setReady]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState<any>(null)
  const [format,setFormat]=useState('spotify_extended'),[account,setAccount]=useState(''),[slug,setSlug]=useState(''),[version,setVersion]=useState(1),[query,setQuery]=useState(''),[offset,setOffset]=useState(0),[total,setTotal]=useState(0),[ids,setIds]=useState('')
  const [client,setClient]=useState(''),[redirect,setRedirect]=useState('http://127.0.0.1:8765/callback'),[authorization,setAuthorization]=useState<any>(null),[callback,setCallback]=useState('')
  async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'include',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.message||result.error);return result}
  async function load(){const [history,summary,lists,connection,availability]=await Promise.all([request(`/history?q=${encodeURIComponent(query)}&offset=${offset}&limit=25`),request('/stats'),request('/playlists'),request('/spotify/config'),request('/spotify/readiness')]);setEvents(history.items);setTotal(history.total);setStats(summary);setPlaylists(lists.items);setConfig(connection.config);setReady(availability)}
  useEffect(()=>{load().catch(e=>setError(e.message))},[query,offset])
  async function run(action:()=>Promise<void>){setBusy(true);setError('');try{await action();await load()}catch(e){setError(String((e as Error).message))}finally{setBusy(false)}}
  return <ListScaffold title="Listening history and playlists" bodyClassName="mx-auto w-full max-w-5xl space-y-l px-l py-xl"><p data-type="body-m" className="max-w-[48rem] text-on-surface-low">Import Spotify privacy exports or synchronize a connected account. API plays have unknown listened duration. JSON files are limited to 1 MiB.</p>{error&&<p role="alert">{error}</p>}
  <fieldset disabled={busy}><legend>Import listening evidence</legend><label>Account label<TextInput value={account} onChange={(nextValue) => setAccount(nextValue)}/></label><label>Export format<Select value={String(format)} onChange={(nextValue) => setFormat(nextValue)} options={[...['spotify_extended', 'spotify_legacy', 'spotify_playlists', 'spotify_api'].map(value => ({ value: String(value), label: String(value) }))]}/></label>
  <label>Upload JSON<input type="file" accept="application/json,.json" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{if(file.size>1048576)throw new Error('JSON exceeds 1 MiB; split the export into smaller files');const content=await file.text();JSON.parse(content);const response=await fetch(artifactBase,{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,kind:'json',source:'import',content})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Upload failed');const artifact=body.artifact||body;setSlug(artifact.slug);setVersion(artifact.version)})}}/></label>
  <label>JSON artifact slug<TextInput value={slug} onChange={(nextValue) => setSlug(nextValue)}/></label><label>Artifact version<TextInput type="number" min={1} value={String(version)} onChange={(nextValue) => setVersion(Number(nextValue))}/></label><Button onClick={()=>run(async()=>setReceipt(await request('/imports','POST',{request_id:crypto.randomUUID(),account_label:account,format,artifact_ref:{slug,version}})))}>Import evidence</Button></fieldset>
  {receipt&&<p role="status">Imported {receipt.added} events; {receipt.duplicates} duplicates; {receipt.skipped} skipped.</p>}
  <p>{stats.event_count||0} events · {stats.ms_played||0} known milliseconds · {stats.unknown_duration_count||0} unknown durations</p><ul>{stats.top_artists?.map((row:any)=><li key={row.artist}>{row.artist}: {row.event_count} plays</li>)}</ul>
  <label>Search listening history<TextInput value={query} onChange={(nextValue) => { setQuery(nextValue); setOffset(0); }}/></label><Table caption="Listening history"><THead><tr><Th>Track</Th><Th>Artist</Th><Th>Time</Th><Th>Listened milliseconds</Th></tr></THead><tbody>{events.map(row=><tr key={row.id}><Td>{row.title}</Td><Td>{row.artist}</Td><Td>{row.ended_at||row.played_at} ({row.timestamp_semantics})</Td><Td>{row.ms_played===null?'Unknown':row.ms_played}</Td></tr>)}</tbody></Table><Button disabled={!offset} onClick={()=>setOffset(offset-25)} disabledReason={!offset ? "This is the first page; there is no previous page. Explain the separate loading branch where present." : undefined}>Previous history</Button><Button disabled={offset+25>=total} onClick={()=>setOffset(offset+25)} disabledReason={offset+25>=total ? "There is no next page. Explain the separate loading branch where present." : undefined}>Next history</Button>
  <h2>Playlists</h2>{playlists.map(row=><Button key={row.playlist_id} onClick={()=>run(async()=>setPlaylist((await request('/playlists/'+row.playlist_id)).item))}>{row.name}</Button>)}{playlist&&<><h3>{playlist.current.name}</h3><label>Playlist snapshot<Select value={String(playlist.current.id)} onChange={(nextValue) => setPlaylist({ ...playlist, current: playlist.snapshots.find((row: any) => row.id === nextValue) })} options={[...playlist.snapshots.map((row: any) => ({ value: String(row.id), label: String(row.modified_at || row.id.slice(0, 12)) }))]}/></label><ol>{playlist.current.tracks.map((row:any,index:number)=><li key={index}>{row.title} — {row.artist}</li>)}</ol></>}
  <h2 data-type="title-m">Spotify connection</h2>{config&&<fieldset disabled={busy}><label className="flex items-center gap-s"><Checkbox ariaLabel="Enable Spotify" checked={config.enabled} onChange={enabled=>setConfig({...config,enabled})}/>Enable Spotify</label><label>Credential name<TextInput value={config.credential_name} onChange={(nextValue) => setConfig({ ...config, credential_name: nextValue })}/></label><label>Connection label<TextInput value={config.account_label} onChange={(nextValue) => setConfig({ ...config, account_label: nextValue })}/></label><Button onClick={()=>run(async()=>{setConfig((await request('/spotify/config','PATCH',config)).config)})}>Save Spotify connection</Button><p>{ready?.ready_to_sync?'Credential available; remote account unverified':'Spotify connection unavailable'}</p><label>Playlist IDs<TextInput value={ids} onChange={(nextValue) => setIds(nextValue)}/></label><Button onClick={()=>run(async()=>{const result=await request('/spotify/sync','POST',{request_id:crypto.randomUUID(),playlist_ids:ids.split(',').map(value=>value.trim()).filter(Boolean)});setReceipt(result.import_receipt)})}>Synchronize Spotify</Button></fieldset>}
  <fieldset disabled={busy}><legend>Authorize Spotify with PKCE</legend><label>Spotify client ID<TextInput value={client} onChange={(nextValue) => setClient(nextValue)}/></label><label>Registered redirect URI<TextInput value={redirect} onChange={(nextValue) => setRedirect(nextValue)}/></label><Button onClick={()=>run(async()=>setAuthorization(await request('/spotify/authorize','POST',{client_id:client,redirect_uri:redirect})))}>Create authorization link</Button>{authorization&&<a href={authorization.authorization_url} target="_blank" rel="noreferrer">Authorize on Spotify</a>}<p>After consent, paste the complete redirected URL here to finish the connection.</p><label>Redirected URL<TextInput value={callback} onChange={(nextValue) => setCallback(nextValue)}/></label><Button onClick={()=>run(async()=>{const url=new URL(callback);await request('/spotify/complete','POST',{state:url.searchParams.get('state'),code:url.searchParams.get('code')});setCallback('');setAuthorization(null)})}>Complete Spotify authorization</Button></fieldset>
  </ListScaffold>
}
