import { TextInput, Select } from '../../../shared/ui/forms'
import { BUSY_REASON } from '../../../shared/ui/unavailable'
import { useEffect, useState } from 'react'
import {ListScaffold} from '../../../shared/ui/ListScaffold'
import { Button } from '../../../shared/ui/Button'
type Note={id:string;pitch:number;start_seconds:number;duration_seconds:number;velocity:number}
type Score={id:string;title:string;tempo_bpm:number;duration_seconds:number;notes:Note[];revision:number;method:string}
type Track={id:string;title:string;renders:{id:string;artifact_ref:{slug:string;version:number}}[]}
export default function MidiPage({apiBase='/api/capabilities/music/midi',catalogBase='/api/capabilities/music/catalog'}:{apiBase?:string;catalogBase?:string}){
 const [scores,setScores]=useState<Score[]>([]),[tracks,setTracks]=useState<Track[]>([]),[score,setScore]=useState<Score|null>(null),[title,setTitle]=useState(''),[tempo,setTempo]=useState(120),[selection,setSelection]=useState(''),[notes,setNotes]=useState<Note[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[download,setDownload]=useState(''),[offset,setOffset]=useState(0)
 async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const body=await response.json();if(!response.ok)throw new Error(body.message||body.error);return body}
 function show(item:Score){setScore(item);setTitle(item.title);setNotes(item.notes);setDirty(false);setDownload('')}
 useEffect(()=>{request(`?offset=${offset}&limit=25`).then(value=>setScores(value.items)).catch(err=>setError(err.message))},[apiBase,offset])
 useEffect(()=>{fetch(catalogBase+'/tracks?limit=100').then(response=>{if(!response.ok)throw new Error('Cannot load recordings');return response.json()}).then(value=>setTracks(value.items)).catch(err=>setError(err.message))},[catalogBase])
 async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 function change(index:number,key:keyof Note,value:number){setNotes(rows=>rows.map((row,i)=>i===index?{...row,[key]:value}:row));setDirty(true);setDownload('')}
 return <ListScaffold title="Audio to MIDI" bodyClassName="mx-auto flex w-full max-w-5xl flex-col gap-l px-l py-xl">
 <p>Monophonic PCM WAV only: one voice, 16-bit, 8–48 kHz, up to 60 seconds. Review detected notes before export; chords and noisy recordings may be inaccurate.</p>{error&&<p role="alert">{error}</p>}
 <nav aria-label="Transcriptions">{scores.map(row=><Button key={row.id} variant="secondary" onClick={()=>void act(async()=>show((await request('/'+row.id)).item))}>{row.title}</Button>)}<Button disabled={!offset} onClick={()=>setOffset(value=>Math.max(0,value-25))} disabledReason={!offset ? "This is the first page; there is no previous page. Explain the separate loading branch where present." : undefined}>Previous</Button><Button disabled={scores.length<25} onClick={()=>setOffset(value=>value+25)} disabledReason={scores.length<25 ? "There is no next page. Explain the separate loading branch where present." : undefined}>Next</Button></nav>
 {!score?<form className="flex flex-col gap-3" onSubmit={event=>{event.preventDefault();void act(async()=>{const [track_id,render_id]=selection.split(':');const item=(await request('','POST',{request_id:crypto.randomUUID(),track_id,render_id,title,tempo_bpm:tempo})).item;show(item);setScores(rows=>[...rows,item])})}}>
 <label>Transcription title<TextInput required value={title} onChange={(nextValue) => setTitle(nextValue)}/></label><label>Export tempo BPM<TextInput type="number" min={20} max={300} value={String(tempo)} onChange={(nextValue) => setTempo(Number(nextValue))}/></label>
 <label>Source recording<Select value={String(selection)} onChange={(nextValue) => setSelection(nextValue)} options={[({ value: "", label: "Choose an actual recording" }), ...tracks.flatMap(track => track.renders.map(render => ({ value: String(track.id + ':' + render.id), label: String(track.title) + " \u00B7 " + String(render.artifact_ref.slug) })))]}/></label>
 <Button type="submit" disabled={busy||!title.trim()||!selection} disabledReason={busy ? BUSY_REASON : !title.trim() ? 'Enter a score title before transcribing.' : !selection ? 'Select a recording before transcribing.' : undefined}>Transcribe recording</Button></form>:<>
 <Button variant="secondary" onClick={()=>{setScore(null);setTitle('');setNotes([]);setDownload('')}}>New transcription</Button>
 <label>Score title<TextInput value={title} onChange={(nextValue) => { setTitle(nextValue); setDirty(true); setDownload(''); }}/></label><p>Saved revision {score.revision} · {score.duration_seconds.toFixed(2)} seconds · {score.tempo_bpm} BPM</p>
 <svg role="img" aria-label="Piano roll" viewBox="0 0 1000 610" className="min-h-48 w-full border border-outline">{Array.from({length:61},(_,i)=><line key={i} x1="0" x2="1000" y1={i*10} y2={i*10} stroke="currentColor" opacity="0.1"/>)}{notes.map((note,index)=><rect key={note.id} role="button" tabIndex={0} aria-label={`Select note ${index+1}, pitch ${note.pitch}`} x={note.start_seconds/score.duration_seconds*1000} y={(96-note.pitch)*10} width={Math.max(2,note.duration_seconds/score.duration_seconds*1000)} height="9" fill="currentColor" onClick={()=>document.getElementById(`midi-pitch-${note.id}`)?.focus()} onKeyDown={event=>{if(event.key==='Enter')document.getElementById(`midi-pitch-${note.id}`)?.focus()}}/>)}</svg>
 {notes.length===0&&<p>No pitched notes detected. You can add notes manually.</p>}
 {notes.map((note,index)=><fieldset key={note.id} className="grid gap-2 border border-outline p-2 sm:grid-cols-5"><legend>Note {index+1}</legend>{(['pitch','start_seconds','duration_seconds','velocity'] as const).map(key=><label key={key}>Note {index+1} {key}<TextInput id={key === 'pitch' ? `midi-pitch-${note.id}` : undefined} type="number" step={key.includes('seconds') ? '0.01' : '1'} value={String(note[key])} onChange={(nextValue) => change(index, key, Number(nextValue))}/></label>)}<Button variant="secondary" onClick={()=>{setNotes(rows=>rows.filter(row=>row.id!==note.id));setDirty(true);setDownload('')}}>Delete note {index+1}</Button></fieldset>)}
 <Button variant="secondary" disabled={notes.length>=2000} onClick={()=>{setNotes(rows=>[...rows,{id:crypto.randomUUID(),pitch:60,start_seconds:0,duration_seconds:Math.min(.5,score.duration_seconds),velocity:80}]);setDirty(true);setDownload('')}} disabledReason={notes.length>=2000 ? "The MIDI score already has the maximum 2000 notes." : undefined}>Add note</Button>
 <div className="flex gap-2"><Button disabled={busy||!dirty||!title.trim()} disabledReason={busy ? BUSY_REASON : !dirty ? 'There are no unsaved note changes.' : !title.trim() ? 'Enter a score title before saving.' : undefined} onClick={()=>void act(async()=>{const item=(await request('/'+score.id,'PATCH',{revision:score.revision,title,notes})).item;show(item);setScores(rows=>rows.map(row=>row.id===item.id?item:row))})}>Save notes</Button>
 <Button disabled={busy||dirty} disabledReason={busy ? BUSY_REASON : dirty ? 'Save note edits before exporting MIDI.' : undefined} onClick={()=>void act(async()=>{const result=await request('/'+score.id+'/export','POST',{revision:score.revision});setDownload(`/api/artifacts/${result.artifact_ref.slug}/raw?version=${result.artifact_ref.version}`)})}>Export MIDI</Button></div>{dirty&&<p>Save edits before export.</p>}{download&&<a className="text-primary" href={download} download={`${score.title}.mid`}>Download MIDI</a>}
 </>}
 </ListScaffold>
}
