import { BUSY_REASON } from '../../../shared/ui/unavailable'
import { useEffect,useState } from 'react'
import {ListScaffold} from '../../../shared/ui/ListScaffold'
import { Checkbox, TextInput, Select, TextArea } from '../../../shared/ui/forms'
import { Button } from '../../../shared/ui/Button'
import ModelViewer from './ModelViewer'
type Config={enabled:boolean;credential_name:string;model:string;revision:number}
type Job={id:string;status:string;progress:number;model:string;error:string|null;artifact_ref:{slug:string;version:number}|null;request:{title:string;license:string}}
export default function Models3DPage({apiBase='/api/capabilities/music/models3d'}:{apiBase?:string}){
 const [config,setConfig]=useState<Config|null>(null),[ready,setReady]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[title,setTitle]=useState(''),[slug,setSlug]=useState(''),[version,setVersion]=useState(1),[faces,setFaces]=useState(30000),[texture,setTexture]=useState(true),[license,setLicense]=useState('')
 async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw new Error(value.message||value.error);return value}
 async function load(){const value=await request('/readiness');setConfig(value.config);setReady(value.ready_to_submit);setJobs((await request('/jobs')).jobs)}
 async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void act(load)},[apiBase])
 function change(values:Partial<Config>){setConfig(row=>row?{...row,...values}:row);setReady(false)}
 return <ListScaffold title="Image to 3D" bodyClassName="mx-auto flex w-full max-w-4xl flex-col gap-l px-l py-xl"><p data-type="body-m" className="max-w-[48rem] text-on-surface-low">Generate geometry from a saved image with Meshy. Local readiness does not verify remote entitlement, pricing or output quality.</p>{error&&<p role="alert">{error}</p>}
 {config&&<><label className="flex items-center gap-s"><Checkbox ariaLabel="Enable 3D engine" checked={config.enabled} onChange={enabled=>change({enabled})}/>Enable 3D engine</label><label>Named 3D credential<TextInput value={config.credential_name} onChange={(nextValue) => change({ credential_name: nextValue })}/></label><label>3D model<Select value={String(config.model)} onChange={(nextValue) => change({ model: nextValue })} options={[...['meshy-6', 'meshy-6-lite', 'meshy-7.1'].map(model => ({ value: String(model), label: String(model) }))]}/></label><Button disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={()=>void act(async()=>{await request('/config','PATCH',config);await load()})}>Save 3D settings</Button></>}
 <label>Asset title<TextInput value={title} onChange={(nextValue) => setTitle(nextValue)}/></label><label>Image artifact slug<TextInput value={slug} onChange={(nextValue) => setSlug(nextValue)}/></label><label>Image version<TextInput type="number" min={1} value={String(version)} onChange={(nextValue) => setVersion(Number(nextValue))}/></label><label>Target faces<TextInput type="number" min={100} max={300000} value={String(faces)} onChange={(nextValue) => setFaces(Number(nextValue))}/></label><label className="flex items-center gap-s"><Checkbox ariaLabel="Generate texture" checked={texture} onChange={setTexture}/>Generate texture</label><label>License or rights statement<TextArea value={license} onChange={(nextValue) => setLicense(nextValue)} className="min-h-24"/></label>
 <Button disabled={busy||!ready||!title.trim()||!slug.trim()||!license.trim()} disabledReason={busy ? BUSY_REASON : !ready ? 'Enable the engine with an available named credential before generating.' : !title.trim() ? 'Enter an asset title before generating.' : !slug.trim() ? 'Choose an image artifact before generating.' : !license.trim() ? 'Enter a license or rights statement before generating.' : undefined} onClick={()=>void act(async()=>{const result=await request('/jobs','POST',{request_id:crypto.randomUUID(),title,image_ref:{slug,version},target_polycount:faces,should_texture:texture,license});setJobs(rows=>[result.job,...rows])})}>Generate 3D asset</Button>{!ready&&<p>Enable the engine with an available named credential to submit.</p>}
 <Button variant="secondary" disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={()=>void act(load)}>Refresh local jobs</Button>
 <ol>{jobs.map(job=><li key={job.id} className="flex flex-col gap-2 border border-outline p-3"><h2>{job.request.title}</h2><p>{job.status} · {job.progress}% · {job.model}</p><p>{job.request.license}</p>{job.error&&<p>{job.error}</p>}{!['completed','failed','stopped'].includes(job.status)&&<><Button ariaLabel={`Check provider progress for ${job.request.title}`} disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={()=>void act(async()=>{await request('/jobs/'+job.id+'/refresh','POST',{});await load()})}>Check provider progress</Button><Button ariaLabel={`Stop local tracking for ${job.request.title}`} variant="secondary" disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={()=>void act(async()=>{await request('/jobs/'+job.id+'/stop','POST',{});await load()})}>Stop local tracking</Button></>}{job.artifact_ref&&<><ModelViewer artifactRef={job.artifact_ref} artifactBase={apiBase+'/artifacts'}/><a href={`${apiBase}/artifacts/${job.artifact_ref.slug}/${job.artifact_ref.version}/raw`} download={`${job.request.title}.glb`}>Download GLB</a></>}</li>)}</ol>
 </ListScaffold>
}
