import { useEffect,useState } from 'react'
import { Button } from '../../../shared/ui/Button'
import ModelViewer from './ModelViewer'
type Config={enabled:boolean;credential_name:string;model:string;revision:number}
type Job={id:string;status:string;progress:number;model:string;error:string|null;artifact_ref:{slug:string;version:number}|null;request:{title:string;license:string}}
const cls='w-full rounded-lg border border-outline bg-surface p-2 text-on-surface'
export default function Models3DPage({apiBase='/api/capabilities/music/models3d'}:{apiBase?:string}){
 const [config,setConfig]=useState<Config|null>(null),[ready,setReady]=useState(false),[jobs,setJobs]=useState<Job[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[title,setTitle]=useState(''),[slug,setSlug]=useState(''),[version,setVersion]=useState(1),[faces,setFaces]=useState(30000),[texture,setTexture]=useState(true),[license,setLicense]=useState('')
 async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw new Error(value.message||value.error);return value}
 async function load(){const value=await request('/readiness');setConfig(value.config);setReady(value.ready_to_submit);setJobs((await request('/jobs')).jobs)}
 async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{void act(load)},[apiBase])
 function change(values:Partial<Config>){setConfig(row=>row?{...row,...values}:row);setReady(false)}
 return <section className="mx-auto flex w-full max-w-4xl flex-col gap-4 overflow-auto p-4 text-on-surface"><h1>Image to 3D</h1><a href="#/capabilities/music">Repertoire</a><p>Generate geometry from a saved image with Meshy. Local readiness does not verify remote entitlement, pricing or output quality.</p>{error&&<p role="alert">{error}</p>}
 {config&&<><label><input type="checkbox" checked={config.enabled} onChange={event=>change({enabled:event.target.checked})}/>Enable 3D engine</label><label>Named 3D credential<input className={cls} value={config.credential_name} onChange={event=>change({credential_name:event.target.value})}/></label><label>3D model<select className={cls} value={config.model} onChange={event=>change({model:event.target.value})}>{['meshy-6','meshy-6-lite','meshy-7.1'].map(model=><option key={model}>{model}</option>)}</select></label><Button disabled={busy} onClick={()=>void act(async()=>{await request('/config','PATCH',config);await load()})}>Save 3D settings</Button></>}
 <label>Asset title<input className={cls} value={title} onChange={event=>setTitle(event.target.value)}/></label><label>Image artifact slug<input className={cls} value={slug} onChange={event=>setSlug(event.target.value)}/></label><label>Image version<input className={cls} type="number" min={1} value={version} onChange={event=>setVersion(Number(event.target.value))}/></label><label>Target faces<input className={cls} type="number" min={100} max={300000} value={faces} onChange={event=>setFaces(Number(event.target.value))}/></label><label><input type="checkbox" checked={texture} onChange={event=>setTexture(event.target.checked)}/>Generate texture</label><label>License or rights statement<textarea className={cls} value={license} onChange={event=>setLicense(event.target.value)}/></label>
 <Button disabled={busy||!ready||!title.trim()||!slug.trim()||!license.trim()} onClick={()=>void act(async()=>{const result=await request('/jobs','POST',{request_id:crypto.randomUUID(),title,image_ref:{slug,version},target_polycount:faces,should_texture:texture,license});setJobs(rows=>[result.job,...rows])})}>Generate 3D asset</Button>{!ready&&<p>Enable the engine with an available named credential to submit.</p>}
 <Button variant="secondary" disabled={busy} onClick={()=>void act(load)}>Refresh local jobs</Button>
 <ol>{jobs.map(job=><li key={job.id} className="flex flex-col gap-2 border border-outline p-3"><h2>{job.request.title}</h2><p>{job.status} · {job.progress}% · {job.model}</p><p>{job.request.license}</p>{job.error&&<p>{job.error}</p>}{!['completed','failed','stopped'].includes(job.status)&&<><Button disabled={busy} onClick={()=>void act(async()=>{await request('/jobs/'+job.id+'/refresh','POST',{});await load()})}>Check provider progress</Button><Button variant="secondary" disabled={busy} onClick={()=>void act(async()=>{await request('/jobs/'+job.id+'/stop','POST',{});await load()})}>Stop local tracking</Button></>}{job.artifact_ref&&<><ModelViewer artifactRef={job.artifact_ref} artifactBase={apiBase+'/artifacts'}/><a href={`${apiBase}/artifacts/${job.artifact_ref.slug}/${job.artifact_ref.version}/raw`} download={`${job.request.title}.glb`}>Download GLB</a></>}</li>)}</ol>
 </section>
}
