import { useEffect, useState } from 'react'
import { Button } from '../../../shared/ui/Button'
type Ref={slug:string;version:number}
type Scene={id:string;image_ref:Ref;beats:number;start_seconds?:number;duration_seconds?:number}
type Project={id:string;revision:number;title:string;track_id:string;render_id:string;tempo_bpm:number;offset_seconds:number;scenes:Scene[];duration_seconds:number}
type Job={id:string;status:string;project_id:string;revision:number;artifact_ref:Ref|null;error:string|null}
type Track={id:string;title:string;renders:{id:string}[]}
const cls='w-full rounded-lg border border-outline bg-surface p-2 text-on-surface'
const scene=():Scene=>({id:crypto.randomUUID(),image_ref:{slug:'',version:1},beats:4})
export default function VideoPage({apiBase='/api/capabilities/music/videos',catalogBase='/api/capabilities/music/catalog'}:{apiBase?:string;catalogBase?:string}){
 const [projects,setProjects]=useState<Project[]>([]),[tracks,setTracks]=useState<Track[]>([]),[item,setItem]=useState<Project|null>(null),[title,setTitle]=useState(''),[selection,setSelection]=useState(''),[tempo,setTempo]=useState(120),[offset,setOffset]=useState(0),[scenes,setScenes]=useState<Scene[]>([scene()]),[jobs,setJobs]=useState<Job[]>([]),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[error,setError]=useState('')
 async function request(path:string,method='GET',data?:unknown){const response=await fetch(apiBase+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const value=await response.json();if(!response.ok)throw new Error(value.message||value.error);return value}
 function show(value:Project){setItem(value);setTitle(value.title);setSelection(value.track_id+':'+value.render_id);setTempo(value.tempo_bpm);setOffset(value.offset_seconds);setScenes(value.scenes);setDirty(false)}
 async function refresh(){setJobs((await request('/jobs')).jobs)}
 useEffect(()=>{request('?limit=100').then(value=>setProjects(value.items)).catch(err=>setError(err.message));refresh().catch(err=>setError(err.message));fetch(catalogBase+'/tracks?limit=100').then(response=>response.json()).then(value=>setTracks(value.items)).catch(err=>setError(err.message))},[apiBase,catalogBase])
 useEffect(()=>{if(!jobs.some(job=>['queued','running'].includes(job.status)))return;const timer=setInterval(()=>refresh().catch(err=>setError(err.message)),700);return()=>clearInterval(timer)},[jobs,apiBase])
 async function act(action:()=>Promise<void>){setBusy(true);setError('');try{await action()}catch(err){setError((err as Error).message)}finally{setBusy(false)}}
 function change(index:number,values:Partial<Scene>){setScenes(rows=>rows.map((row,i)=>i===index?{...row,...values}:row));setDirty(true)}
 const seconds=scenes.reduce((sum,row)=>sum+row.beats*60/tempo,0)
 return <section className="mx-auto flex w-full max-w-4xl flex-col gap-4 overflow-auto p-4 text-on-surface"><h1>Beat-grid music videos</h1><a className="text-primary" href="#/capabilities/music">Repertoire</a><p>Set the tempo and scene lengths in beats. This uses your authored grid, not automatic beat detection. Output is 640 × 360 at 30 fps, up to 60 seconds.</p>{error&&<p role="alert">{error}</p>}
 <nav aria-label="Video projects">{projects.map(row=><Button key={row.id} variant="secondary" onClick={()=>void act(async()=>show((await request('/'+row.id)).item))}>{row.title}</Button>)}</nav>
 {item&&<Button variant="secondary" onClick={()=>{setItem(null);setTitle('');setScenes([scene()]);setDirty(false)}}>New video project</Button>}
 <form className="flex flex-col gap-3" onSubmit={event=>{event.preventDefault();void act(async()=>{const [track_id,render_id]=selection.split(':');const data={title,track_id,render_id,tempo_bpm:tempo,offset_seconds:offset,scenes:scenes.map(({id,image_ref,beats})=>({id,image_ref,beats})),...(item?{revision:item.revision}:{})};const result=(await request(item?'/'+item.id:'',item?'PATCH':'POST',data)).item;show(result);setProjects(rows=>[...rows.filter(row=>row.id!==result.id),result])})}}>
 <label>Video title<input className={cls} value={title} onChange={event=>{setTitle(event.target.value);setDirty(true)}} required/></label>
 <label>Audio recording<select className={cls} value={selection} onChange={event=>{setSelection(event.target.value);setDirty(true)}}><option value="">Select recording</option>{tracks.flatMap(track=>track.renders.map(render=><option key={render.id} value={track.id+':'+render.id}>{track.title} · {render.id}</option>))}</select></label>
 <label>Grid tempo BPM<input className={cls} type="number" min={20} max={300} value={tempo} onChange={event=>{setTempo(Number(event.target.value));setDirty(true)}}/></label><label>Audio start seconds<input className={cls} type="number" min={0} step="0.01" value={offset} onChange={event=>{setOffset(Number(event.target.value));setDirty(true)}}/></label>
 {scenes.map((row,index)=><fieldset key={row.id} className="grid gap-2 border border-outline p-3"><legend>Scene {index+1}</legend><label>Scene {index+1} image slug<input className={cls} value={row.image_ref.slug} onChange={event=>change(index,{image_ref:{...row.image_ref,slug:event.target.value}})}/></label><label>Scene {index+1} image version<input className={cls} type="number" min={1} value={row.image_ref.version} onChange={event=>change(index,{image_ref:{...row.image_ref,version:Number(event.target.value)}})}/></label><label>Scene {index+1} beats<input className={cls} type="number" min={1} max={64} value={row.beats} onChange={event=>change(index,{beats:Number(event.target.value)})}/></label><p>Scene duration {(row.beats*60/tempo).toFixed(2)} seconds</p><Button variant="secondary" disabled={scenes.length===1} onClick={()=>{setScenes(rows=>rows.filter(value=>value.id!==row.id));setDirty(true)}}>Remove scene {index+1}</Button></fieldset>)}
 <Button variant="secondary" disabled={scenes.length>=16} onClick={()=>{setScenes(rows=>[...rows,scene()]);setDirty(true)}}>Add image scene</Button><p>Total video {seconds.toFixed(2)} seconds</p><Button type="submit" disabled={busy||!title.trim()||!selection}>{item?'Save video project':'Create video project'}</Button></form>
 {item&&<><p>Saved video revision {item.revision}</p><Button disabled={busy||dirty} onClick={()=>void act(async()=>{const result=await request('/jobs','POST',{request_id:crypto.randomUUID(),project_id:item.id,revision:item.revision});setJobs(rows=>[result.job,...rows.filter(row=>row.id!==result.job.id)])})}>Render music video</Button>{dirty&&<p>Save changes before rendering.</p>}</>}
 <Button variant="secondary" onClick={()=>void act(refresh)}>Refresh renders</Button><ol aria-label="Video renders">{jobs.map(job=><li key={job.id} className="flex flex-col gap-2 border border-outline p-3"><p>Render {job.status} · revision {job.revision}</p>{job.error&&<p>{job.error}</p>}{['queued','running'].includes(job.status)&&<Button onClick={()=>void act(async()=>{await request('/jobs/'+job.id+'/cancel','POST',{});await refresh()})}>Cancel render</Button>}{job.artifact_ref&&<><video aria-label="Rendered music video" controls src={`/api/artifacts/${job.artifact_ref.slug}/raw?version=${job.artifact_ref.version}`}/><a href={`/api/artifacts/${job.artifact_ref.slug}/raw?version=${job.artifact_ref.version}`} download>Download music video</a></>}</li>)}</ol>
 </section>
}
