"""Gideon's authenticated Hypermid integration boundary."""

from .adapter import HypermidAdapter
from .client import (
    ConnectionRecord,
    EventSubscription,
    HypermidClient,
    HypermidClientError,
    HypermidConnectionError,
    HypermidOutcomeUnknown,
    HypermidProtocolError,
    HypermidRemoteError,
)
from .contracts import (
    AccessRequest,
    GrantOperation,
    MemoryContractError,
    MemoryHealth,
    MemoryOperation,
    MemoryRecord,
    MutationReceipt,
    MutationRequest,
    RecordDraft,
    RecordKind,
    RecordPage,
    RecordStatus,
    RelocationReceipt,
    RevisionPrecondition,
    SearchMode,
    SearchRequest,
    SearchResponse,
    ServiceResult,
    SourceKind,
    SourceSnapshot,
    SplitReceipt,
    VerificationState,
)
from .foundation import Digest, EffectState, Id
from .lifecycle import (
    HypermidLifecycle,
    LocalEnrollment,
    attach_runtime,
    build_runtime_lifecycle,
    runtime_scope,
    start_runtime,
    stop_runtime,
)
from .memory_client import MemoryClient
from .models import (
    EVENT_CHUNK_BYTES,
    MAX_FRAME_BYTES,
    PROTOCOL,
    ConnectionLimits,
    Cursor,
    EffectStatus,
    Envelope,
    Error,
    EventChunk,
    EventReassembler,
    Principal,
    Scope,
    ServerDescription,
    SessionAccepted,
    SubscriptionSnapshot,
    Trace,
)
from .modules import (
    HypermidModuleSupervisor,
    ModuleHealth,
    ModuleLifecycleError,
    ToolModuleSpec,
    close_session_modules,
    providers_for_session,
)
from .shared_models import (
    AccountIdentity,
    CacheConflict,
    CacheState,
    Durability,
    FileCacheStore,
    FrozenPass,
    ModelCatalog,
    ModelRecord,
    Money,
    PriceRate,
    ProviderRecord,
    ProviderUsage,
    UsageWindow,
)
from .status import HypermidStatus, HypermidStatusStore


def __getattr__(name: str):
    if name == "HypermidOperatorLifecycle":
        from .operator_lifecycle import HypermidOperatorLifecycle

        return HypermidOperatorLifecycle
    raise AttributeError(name)


__all__ = [
    "AccessRequest",
    "ConnectionLimits",
    "ConnectionRecord",
    "Cursor",
    "Digest",
    "EVENT_CHUNK_BYTES",
    "EffectStatus",
    "EffectState",
    "Envelope",
    "Error",
    "EventChunk",
    "EventReassembler",
    "EventSubscription",
    "GrantOperation",
    "HypermidAdapter",
    "HypermidClient",
    "HypermidClientError",
    "HypermidConnectionError",
    "HypermidLifecycle",
    "LocalEnrollment",
    "HypermidModuleSupervisor",
    "HypermidOperatorLifecycle",
    "HypermidOutcomeUnknown",
    "HypermidProtocolError",
    "HypermidRemoteError",
    "HypermidStatus",
    "HypermidStatusStore",
    "Id",
    "MAX_FRAME_BYTES",
    "MemoryClient",
    "MemoryContractError",
    "MemoryHealth",
    "MemoryOperation",
    "MemoryRecord",
    "ModuleHealth",
    "ModuleLifecycleError",
    "MutationReceipt",
    "MutationRequest",
    "PROTOCOL",
    "Principal",
    "RecordDraft",
    "RecordKind",
    "RecordPage",
    "RecordStatus",
    "RelocationReceipt",
    "RevisionPrecondition",
    "Scope",
    "SearchMode",
    "SearchRequest",
    "SearchResponse",
    "ServerDescription",
    "SessionAccepted",
    "ServiceResult",
    "SourceKind",
    "SourceSnapshot",
    "SplitReceipt",
    "SubscriptionSnapshot",
    "Trace",
    "ToolModuleSpec",
    "AccountIdentity",
    "CacheConflict",
    "CacheState",
    "Durability",
    "FileCacheStore",
    "FrozenPass",
    "ModelCatalog",
    "ModelRecord",
    "Money",
    "PriceRate",
    "ProviderRecord",
    "ProviderUsage",
    "UsageWindow",
    "VerificationState",
    "attach_runtime",
    "build_runtime_lifecycle",
    "close_session_modules",
    "providers_for_session",
    "runtime_scope",
    "start_runtime",
    "stop_runtime",
]
