services:
  gideon-web:
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    restart: always

  gideon-gateway:
    restart: always
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
