services:
  gideon-gateway:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.backend
      target: runtime
    image: gideon-gateway:local

  gideon-web:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.web
    image: gideon-web:local

  gideon-slack:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.backend
      target: runtime
    image: gideon-gateway:local
