import { useEffect, useState } from 'react'
import { FileCheck2, Sparkles } from 'lucide-react'
import { gatewayRequest, readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { Field, NumberField, Select, TextArea, TextInput } from '../../../shared/ui/forms'
import { EmptyState, ListScaffold } from '../../../shared/ui/ListScaffold'
import { Surface } from '../../../shared/ui/Surface'

type Step = { id: string; title: string; operation: string; depends_on: string[]; status: string; result?: Record<string, unknown> | null }
type Project = { id: string; revision: number; name: string; treatment: string; status: string; sources: { kind: string; id: string; revision: number; chapters: { content_hash: string }[] }[]; steps: Step[] }
const initial = [{ id: 'verify-sources', title: 'Verify canonical sources', operation: 'source.verify', depends_on: [] }, { id: 'review-treatment', title: 'Review treatment against sources', operation: 'source.verify', depends_on: ['verify-sources'] }]

export default function CreativeDirection({ baseUrl = '', apiRoot = '/api/capabilities/creative/direction' }: { baseUrl?: string; apiRoot?: string }) {
  const root = baseUrl + apiRoot
  const [items, setItems] = useState<Project[]>([]), [name, setName] = useState(''), [treatment, setTreatment] = useState(''), [kind, setKind] = useState('work'), [sourceId, setSourceId] = useState(''), [revision, setRevision] = useState(1), [error, setError] = useState('')
  const load = async () => setItems((await readJson<{ items: Project[] }>(await gatewayRequest(root))).items)
  useEffect(() => { void load().catch(reason => setError(String(reason))) }, [root])
  const create = async () => { setError(''); try { await readJson(await gatewayRequest(root, 'POST', { request_id: crypto.randomUUID(), name, treatment, sources: [{ kind, id: sourceId, revision }], steps: initial })); await load() } catch (reason) { setError(String(reason)) } }
  const act = async (project: Project, action: string, payload: Record<string, unknown>) => { setError(''); try { await readJson(await gatewayRequest(`${root}/${project.id}/${action}`, 'POST', { revision: project.revision, ...payload })); await load() } catch (reason) { setError(String(reason)) } }
  const addSnapshot = (project: Project) => act(project, 'plan', { steps: [...project.steps.map(({ id, title, operation, depends_on }) => ({ id, title, operation, depends_on })), { id: 'snapshot-treatment', title: 'Publish treatment snapshot', operation: 'treatment.snapshot', depends_on: [project.steps[0].id] }] })
  return <ListScaffold title="Creative direction"><section aria-label="Creative direction" className="space-y-xl"><p data-type="body-m" className="max-w-[48rem] text-on-surface-low">Direct production from a reviewed treatment and exact canonical manuscript revisions. Pause before changing remaining work; completed steps and their outputs stay fixed.</p>{error && <p role="alert" className="border-l-2 border-danger/40 pl-s text-danger">{error}</p>}
    <div className="grid min-w-0 gap-l lg:grid-cols-[minmax(17rem,23rem)_minmax(0,1fr)]"><Surface className="h-fit space-y-m p-l"><h2 data-type="title-m">New production plan</h2><Field label="Project name"><TextInput ariaLabel="Direction project name" value={name} onChange={setName} /></Field><Field label="Treatment"><TextArea ariaLabel="Creative treatment" rows={7} value={treatment} onChange={setTreatment} /></Field><Field label="Canonical source"><Select ariaLabel="Direction source kind" value={kind} onChange={setKind} options={[{ value: 'work', label: 'Writing work' }, { value: 'series', label: 'Ordered series' }]} /></Field><Field label="Source ID"><TextInput ariaLabel="Direction source ID" value={sourceId} onChange={setSourceId} /></Field><Field label="Revision"><NumberField ariaLabel="Direction source revision" min={1} value={revision} width="w-full" onChange={setRevision} /></Field><Button className="w-full" disabled={!name || !treatment || !sourceId || revision < 1} onClick={() => void create()}>Create production plan</Button></Surface>
      <section aria-label="Production plans" className="space-y-m">{!items.length ? <Surface className="p-xl"><EmptyState icon={Sparkles} title="No production plans" hint="Create a plan from a reviewed treatment and pinned source revision." /></Surface> : items.map(project => <Surface key={project.id} className="space-y-m p-l"><article aria-label={`Direction project ${project.name}`}><div className="flex items-start gap-s"><FileCheck2 size={18} className="mt-xs shrink-0 text-on-surface-low" /><div><h2 data-type="title-m">{project.name}</h2><p data-type="body-s" className="text-on-surface-low">{project.status} · revision {project.revision} · {project.sources.length} pinned sources</p></div></div><p className="mt-m whitespace-pre-wrap">{project.treatment}</p>{project.sources.map(source => <p key={source.kind + source.id} data-type="body-s" className="mt-s text-on-surface-low">{source.kind} {source.id} revision {source.revision} · {source.chapters.length} manuscript sections</p>)}<ol className="mt-m space-y-xs border-t border-outline-variant/20 pt-m">{project.steps.map(step => <li key={step.id}>{step.title}: {step.status}{typeof step.result?.artifact_id === 'string' && typeof step.result.path === 'string' && <> · <a className="text-primary" href={baseUrl + step.result.path}>Open output</a></>}</li>)}</ol><div className="mt-m flex flex-wrap gap-s">{project.status === 'draft' && <Button onClick={() => void act(project, 'control', { action: 'start' })}>Start production</Button>}{project.status === 'running' && <><Button onClick={() => void act(project, 'advance', {})}>Complete next step</Button><Button variant="secondary" onClick={() => void act(project, 'control', { action: 'pause' })}>Pause production</Button></>}{project.status === 'paused' && <><Button disabled={project.steps.some(step => step.id === 'snapshot-treatment')} onClick={() => void addSnapshot(project)}>Add treatment output</Button><Button onClick={() => void act(project, 'control', { action: 'resume' })}>Resume production</Button></>}</div></article></Surface>)}</section></div>
  </section></ListScaffold>
}
