import { useEffect,useState } from 'react'
import { gatewayRequest,readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
type Step={id:string;title:string;operation:string;depends_on:string[];status:string;result?:Record<string,unknown>|null}
type Project={id:string;revision:number;name:string;treatment:string;status:string;sources:{kind:string;id:string;revision:number;chapters:{content_hash:string}[]}[];steps:Step[]}
const initial=[{id:'verify-sources',title:'Verify canonical sources',operation:'source.verify',depends_on:[]},{id:'review-treatment',title:'Review treatment against sources',operation:'source.verify',depends_on:['verify-sources']}]
export default function CreativeDirection({baseUrl='',apiRoot='/api/capabilities/creative/direction'}:{baseUrl?:string;apiRoot?:string}){
 const root=baseUrl+apiRoot,[items,setItems]=useState<Project[]>([]),[name,setName]=useState(''),[treatment,setTreatment]=useState(''),[kind,setKind]=useState('work'),[sourceId,setSourceId]=useState(''),[revision,setRevision]=useState('1'),[error,setError]=useState('')
 const load=async()=>setItems((await readJson<{items:Project[]}>(await gatewayRequest(root))).items)
 useEffect(()=>{void load().catch(reason=>setError(String(reason)))},[root])
 const create=async()=>{setError('');try{await readJson(await gatewayRequest(root,'POST',{request_id:crypto.randomUUID(),name,treatment,sources:[{kind,id:sourceId,revision:Number(revision)}],steps:initial}));await load()}catch(reason){setError(String(reason))}}
 const act=async(project:Project,action:string,payload:Record<string,unknown>)=>{setError('');try{await readJson(await gatewayRequest(`${root}/${project.id}/${action}`,'POST',{revision:project.revision,...payload}));await load()}catch(reason){setError(String(reason))}}
 const addSnapshot=(project:Project)=>act(project,'plan',{steps:[...project.steps.map(({id,title,operation,depends_on})=>({id,title,operation,depends_on})),{id:'snapshot-treatment',title:'Publish treatment snapshot',operation:'treatment.snapshot',depends_on:[project.steps[0].id]}]})
 return <section aria-label="Creative direction" className="space-y-4"><h2>Creative direction and production plans</h2><p>Direct production from a reviewed treatment and exact canonical manuscript revisions. Pause before changing remaining work; completed steps and their outputs stay fixed.</p>{error&&<p role="alert">{error}</p>}
  <label>Project name<input aria-label="Direction project name" value={name} onChange={event=>setName(event.target.value)}/></label><label>Treatment<textarea aria-label="Creative treatment" value={treatment} onChange={event=>setTreatment(event.target.value)}/></label><label>Canonical source<select aria-label="Direction source kind" value={kind} onChange={event=>setKind(event.target.value)}><option value="work">Writing work</option><option value="series">Ordered series</option></select></label><label>Source ID<input aria-label="Direction source ID" value={sourceId} onChange={event=>setSourceId(event.target.value)}/></label><label>Revision<input aria-label="Direction source revision" type="number" min="1" value={revision} onChange={event=>setRevision(event.target.value)}/></label><Button disabled={!name||!treatment||!sourceId||Number(revision)<1} onClick={()=>void create()}>Create production plan</Button>
  {items.map(project=><article key={project.id} aria-label={`Direction project ${project.name}`}><h3>{project.name}</h3><p>{project.status} · revision {project.revision} · {project.sources.length} pinned sources</p><p>{project.treatment}</p>{project.sources.map(source=><p key={source.kind+source.id}>{source.kind} {source.id} revision {source.revision} · {source.chapters.length} manuscript sections</p>)}<ol>{project.steps.map(step=><li key={step.id}>{step.title}: {step.status}{step.result?.artifact_id&&<> · <a href={baseUrl+String(step.result.path)}>Open output</a></>}</li>)}</ol>
   {project.status==='draft'&&<Button onClick={()=>void act(project,'control',{action:'start'})}>Start production</Button>}{project.status==='running'&&<><Button onClick={()=>void act(project,'advance',{})}>Complete next step</Button><Button onClick={()=>void act(project,'control',{action:'pause'})}>Pause production</Button></>}{project.status==='paused'&&<><Button disabled={project.steps.some(step=>step.id==='snapshot-treatment')} onClick={()=>void addSnapshot(project)}>Add treatment output</Button><Button onClick={()=>void act(project,'control',{action:'resume'})}>Resume production</Button></>}
  </article>)}
 </section>
}
