import { spawn,type ChildProcess } from 'node:child_process'
import { mkdtemp,rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join,resolve } from 'node:path'
import { createInterface } from 'node:readline'
import { afterAll,beforeAll,expect,test } from 'vitest'
import { fireEvent,render,screen,waitFor,within } from '@testing-library/react'
import CreativeDirection from './CreativeDirection'
let server:ChildProcess,origin='',home='',workId='',revision=0
beforeAll(async()=>{home=await mkdtemp(join(tmpdir(),'gideon-direction-ui-'));const root=resolve(process.cwd(),'../..');let diagnostics='';server=spawn(process.env.GIDEON_TEST_PYTHON||'/tmp/gideon-runtime-venv/bin/python',['checks/runtime/capabilities/creative/direction_ui_server.py'],{cwd:root,env:{...process.env,PYTHONPATH:join(root,'runtime'),GIDEON_HOME:home},stdio:['ignore','pipe','pipe']});server.stderr!.on('data',data=>diagnostics+=data.toString());const ready=await new Promise<{port:number;work_id:string;revision:number}>((accept,reject)=>{const lines=createInterface({input:server.stdout!});lines.on('line',line=>{try{accept(JSON.parse(line));lines.close()}catch{}});server.once('error',reject);server.once('exit',code=>reject(new Error(`server exited ${code}: ${diagnostics}`)))});origin=`http://127.0.0.1:${ready.port}`;workId=ready.work_id;revision=ready.revision})
afterAll(async()=>{if(server?.exitCode===null)await new Promise<void>(done=>{server.once('exit',()=>done());server.kill('SIGTERM')});await rm(home,{recursive:true,force:true})})
const change=(name:string,value:string)=>fireEvent.change(screen.getByLabelText(name),{target:{value}})
test('directs a real canonical manuscript through pause plan edit restart and durable output',async()=>{
 render(<CreativeDirection baseUrl={origin}/>);expect(screen.getByRole('region',{name:'Creative direction'})).toHaveTextContent('exact canonical manuscript revisions');expect(screen.getByRole('button',{name:'Create production plan'})).toBeDisabled()
 change('Direction project name','Harbor trailer');change('Creative treatment','Cold blue light crosses the harbor.');change('Direction source ID',workId);change('Direction source revision',String(revision));fireEvent.click(screen.getByRole('button',{name:'Create production plan'}))
 let card=await screen.findByRole('article',{name:'Direction project Harbor trailer'});expect(card).toHaveTextContent(`work ${workId} revision ${revision}`);expect(card).toHaveTextContent('Verify canonical sources: pending');expect(card).toHaveTextContent('Review treatment against sources: pending')
 fireEvent.click(within(card).getByRole('button',{name:'Start production'}));await waitFor(()=>expect(screen.getByText(/running · revision 2/)).toBeInTheDocument());card=screen.getByRole('article',{name:'Direction project Harbor trailer'});fireEvent.click(within(card).getByRole('button',{name:'Complete next step'}));await waitFor(()=>expect(screen.getByText('Verify canonical sources: done')).toBeInTheDocument())
 card=screen.getByRole('article',{name:'Direction project Harbor trailer'});fireEvent.click(within(card).getByRole('button',{name:'Pause production'}));await waitFor(()=>expect(screen.getByText(/paused · revision 4/)).toBeInTheDocument());card=screen.getByRole('article',{name:'Direction project Harbor trailer'});fireEvent.click(within(card).getByRole('button',{name:'Add treatment output'}));await waitFor(()=>expect(screen.getByText('Publish treatment snapshot: pending')).toBeInTheDocument());expect(screen.getByText('Verify canonical sources: done')).toBeInTheDocument()
 card=screen.getByRole('article',{name:'Direction project Harbor trailer'});fireEvent.click(within(card).getByRole('button',{name:'Resume production'}));await waitFor(()=>expect(screen.getByText(/running · revision 6/)).toBeInTheDocument());card=screen.getByRole('article',{name:'Direction project Harbor trailer'});fireEvent.click(within(card).getByRole('button',{name:'Complete next step'}));await waitFor(()=>expect(screen.getByText('Review treatment against sources: done')).toBeInTheDocument());card=screen.getByRole('article',{name:'Direction project Harbor trailer'});fireEvent.click(within(card).getByRole('button',{name:'Complete next step'}));await waitFor(()=>expect(screen.getByText(/completed · revision 8/)).toBeInTheDocument());expect(screen.getByRole('link',{name:'Open output'}).getAttribute('href')).toMatch(new RegExp(`^${origin}/api/artifacts/creative-direction-.+\?version=1$`))
 const saved=await (await fetch(origin+'/api/capabilities/creative/direction')).json();expect(saved.items).toHaveLength(1);expect(saved.items[0].steps.map((step:{status:string})=>step.status)).toEqual(['done','done','done']);expect(saved.items[0].sources[0].chapters[0].content_hash).toMatch(/^[a-f0-9]{64}$/)
})
test('shows real missing source failure without a placeholder project',async()=>{
 const before=await (await fetch(origin+'/api/capabilities/creative/direction')).json();render(<CreativeDirection baseUrl={origin}/>);await waitFor(()=>expect(screen.queryAllByRole('article')).toHaveLength(before.items.length));change('Direction project name','Missing');change('Creative treatment','No substitute.');change('Direction source ID','missing-work');fireEvent.click(screen.getByRole('button',{name:'Create production plan'}));expect(await screen.findByRole('alert')).toHaveTextContent('Work not found');const after=await (await fetch(origin+'/api/capabilities/creative/direction')).json();expect(after.items).toHaveLength(before.items.length)
})
