import { useEffect, useState } from 'react'
import { Download, FileOutput } from 'lucide-react'
import { gatewayRequest, readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { Field, NumberField, Select, TextInput } from '../../../shared/ui/forms'
import { EmptyState, ListScaffold, ListRow } from '../../../shared/ui/ListScaffold'
import { Surface } from '../../../shared/ui/Surface'

type Export = { id: string; source_kind: string; source_id: string; source_revision: number; metadata: { title: string; creator: string; language: string; identifier: string }; selections: { title: string; work_revision: number; artifact_id: string; artifact_version: number; sha256: string }[]; files: Record<'epub' | 'print', { path: string; bytes: number; sha256: string; mime: string }> }

export default function ManuscriptExports({ baseUrl = '', apiRoot = '/api/capabilities/creative/exports' }: { baseUrl?: string; apiRoot?: string }) {
  const root = baseUrl + apiRoot
  const [items, setItems] = useState<Export[]>([]), [kind, setKind] = useState('work'), [sourceId, setSourceId] = useState(''), [revision, setRevision] = useState(1), [title, setTitle] = useState(''), [creator, setCreator] = useState(''), [language, setLanguage] = useState('en'), [identifier, setIdentifier] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const load = async () => setItems((await readJson<{ items: Export[] }>(await gatewayRequest(root))).items)
  useEffect(() => { void load().catch(reason => setError(String(reason))) }, [root])
  const create = async () => { setBusy(true); setError(''); try { await readJson(await gatewayRequest(root, 'POST', { request_id: crypto.randomUUID(), source_kind: kind, source_id: sourceId, source_revision: revision, title, creator, language, identifier })); await load() } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  return <ListScaffold title="Manuscript exports"><section aria-label="Manuscript exports" className="space-y-xl"><p data-type="body-m" className="max-w-[48rem] text-on-surface-low">Exports pin the selected work or ordered series revision and every immutable manuscript artifact. Downloads are regenerated only through a new reviewed export.</p>{error && <p role="alert" className="border-l-2 border-danger/40 pl-s text-danger">{error}</p>}
    <div className="grid min-w-0 gap-l lg:grid-cols-[minmax(17rem,23rem)_minmax(0,1fr)]"><Surface className="h-fit space-y-m p-l"><h2 data-type="title-m">Prepare export</h2><Field label="Manuscript source"><Select ariaLabel="Manuscript source" value={kind} onChange={setKind} options={[{ value: 'work', label: 'Writing work' }, { value: 'series', label: 'Ordered series' }]} /></Field><Field label="Source ID"><TextInput ariaLabel="Export source ID" value={sourceId} onChange={setSourceId} /></Field><Field label="Source revision"><NumberField ariaLabel="Export source revision" min={1} value={revision} width="w-full" onChange={setRevision} /></Field><Field label="Book title"><TextInput ariaLabel="Export title" value={title} onChange={setTitle} /></Field><Field label="Creator"><TextInput ariaLabel="Export creator" value={creator} onChange={setCreator} /></Field><Field label="Language"><TextInput ariaLabel="Export language" value={language} onChange={setLanguage} /></Field><Field label="Publication identifier"><TextInput ariaLabel="Export identifier" value={identifier} onChange={setIdentifier} /></Field><Button className="w-full" disabled={busy || !sourceId || !creator || !language || !identifier || revision < 1} onClick={() => void create()}>Create EPUB and print PDF</Button></Surface>
      <section aria-label="Generated files" className="space-y-s"><h2 data-type="title-m">Generated files</h2>{!items.length ? <Surface className="p-xl"><EmptyState icon={FileOutput} title="No manuscript exports" hint="Create an EPUB and print PDF from a pinned source revision." /></Surface> : items.map((item, index) => <ListRow key={item.id} index={index}><FileOutput size={18} className="shrink-0 text-on-surface-low" /><article className="min-w-0 flex-1" aria-label={`Manuscript export ${item.metadata.title}`}><h3 data-type="label-l">{item.metadata.title}</h3><p data-type="body-s" className="text-on-surface-low">{item.source_kind} {item.source_id} revision {item.source_revision} · {item.selections.length} manuscript sections</p><details className="mt-s"><summary>Artifact details</summary>{item.selections.map((row, position) => <p key={row.artifact_id + position} data-type="caption" className="mt-xs break-all text-on-surface-low">{row.title} · work revision {row.work_revision} · artifact {row.artifact_id} version {row.artifact_version} · SHA-256 {row.sha256}</p>)}</details><div className="mt-m flex flex-wrap gap-m"><a className="inline-flex items-center gap-xs text-primary" href={baseUrl + item.files.epub.path}><Download size={15} />Download EPUB ({item.files.epub.bytes} bytes)</a><a className="inline-flex items-center gap-xs text-primary" href={baseUrl + item.files.print.path}><Download size={15} />Download print PDF ({item.files.print.bytes} bytes)</a></div></article></ListRow>)}</section></div>
  </section></ListScaffold>
}
