import { useEffect, useState } from 'react'
import { gatewayRequest, readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
interface Row { instance_id: string | null; provider_instance: string | null; credential_ref: string | null; subscription_source: string | null; turns: number; input_tokens: number; output_tokens: number; recorded_cost_usd: number; unpriced_turns: number; imported_turns: number; import_formats: string[] }
interface View { rows: Row[]; turns: number; imported_turns: number; unattributed_turns: number; invalid_rows: number; coverage: string }
interface Receipt { imported_records: number; duplicate_records: number; invalid_lines: number; priced: boolean }
export default function Accounting({ baseUrl = '' }: { baseUrl?: string }) {
  const [view, setView] = useState<View>(); const [days, setDays] = useState('30'); const [error, setError] = useState(''); const [format, setFormat] = useState('claude_code_jsonl'); const [file, setFile] = useState<File>(); const [receipt, setReceipt] = useState<Receipt>()
  const load = async () => { setError(''); try { setView(await readJson<View>(await gatewayRequest(`${baseUrl}/api/capabilities/platform/accounting?days=${days}`))) } catch (reason) { setError(String(reason)) } }
  const importUsage = async () => { if (!file) return; setError(''); try { const content = await file.text(); const response = await gatewayRequest(`${baseUrl}/api/capabilities/platform/accounting/import`, 'POST', { format, content, source_name: file.name }); setReceipt(await readJson<Receipt>(response)); await load() } catch (reason) { setError(String(reason)) } }
  useEffect(() => { void load() }, [baseUrl, days])
  return <section aria-label="Instance usage accounting" className="space-y-m"><h2>Instance and subscription binding usage</h2><label>Window<select aria-label="Accounting window" value={days} onChange={event => setDays(event.target.value)}><option value="1">One day</option><option value="30">Thirty days</option><option value="365">One year</option></select></label><Button onClick={() => void load()}>Refresh accounting</Button><fieldset><legend>Import CLI usage history</legend><label>Format<select aria-label="CLI usage format" value={format} onChange={event => setFormat(event.target.value)}><option value="claude_code_jsonl">Claude Code JSONL</option><option value="codex_rollout_jsonl">Codex rollout JSONL</option></select></label><label>History file<input aria-label="CLI usage history file" type="file" accept=".jsonl,application/x-ndjson" onChange={event => setFile(event.target.files?.[0])} /></label><Button disabled={!file} onClick={() => void importUsage()}>Import usage history</Button></fieldset>{error && <p role="alert">{error}</p>}{receipt && <p role="status">Imported {receipt.imported_records} records · {receipt.duplicate_records} duplicates · {receipt.invalid_lines} invalid lines · pricing unknown</p>}<p>{view?.coverage}</p><p>{view?.turns ?? 0} recorded turns · {view?.imported_turns ?? 0} imported · {view?.unattributed_turns ?? 0} provider attribution unknown · {view?.invalid_rows ?? 0} invalid rows</p><table><thead><tr><th>Instance</th><th>Provider instance</th><th>Credential binding</th><th>Subscription source</th><th>Turns</th><th>Input / output tokens</th><th>Recorded cost</th><th>Unpriced turns</th><th>Imported</th></tr></thead><tbody>{view?.rows.map((row, index) => <tr key={index}><td>{row.instance_id || 'Unknown'}</td><td>{row.provider_instance || 'Unknown'}</td><td>{row.credential_ref || 'Unknown'}</td><td>{row.subscription_source || 'Unknown'}</td><td>{row.turns}</td><td>{row.input_tokens} / {row.output_tokens}</td><td>${row.recorded_cost_usd.toFixed(6)}</td><td>{row.unpriced_turns}</td><td>{row.imported_turns}{row.import_formats.length ? ` (${row.import_formats.join(', ')})` : ''}</td></tr>)}</tbody></table></section>
}
