import { useEffect, useState } from 'react'
import { gatewayRequest, readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { Field, Select } from '../../../shared/ui/forms'
import { Surface } from '../../../shared/ui/Surface'
interface Row { instance_id: string | null; provider_instance: string | null; credential_ref: string | null; subscription_source: string | null; turns: number; input_tokens: number; output_tokens: number; recorded_cost_usd: number; unpriced_turns: number; imported_turns: number; import_formats: string[] }
interface View { rows: Row[]; turns: number; imported_turns: number; unattributed_turns: number; invalid_rows: number; coverage: string }
interface Receipt { imported_records: number; duplicate_records: number; invalid_lines: number; priced: boolean }
export default function Accounting({ baseUrl = '' }: { baseUrl?: string }) {
  const [view, setView] = useState<View>(); const [days, setDays] = useState('30'); const [error, setError] = useState(''); const [format, setFormat] = useState('claude_code_jsonl'); const [file, setFile] = useState<File>(); const [receipt, setReceipt] = useState<Receipt>()
  const load = async () => { setError(''); try { setView(await readJson<View>(await gatewayRequest(`${baseUrl}/api/capabilities/platform/accounting?days=${days}`))) } catch (reason) { setError(String(reason)) } }
  const importUsage = async () => { if (!file) return; setError(''); try { const content = await file.text(); const response = await gatewayRequest(`${baseUrl}/api/capabilities/platform/accounting/import`, 'POST', { format, content, source_name: file.name }); setReceipt(await readJson<Receipt>(response)); await load() } catch (reason) { setError(String(reason)) } }
  useEffect(() => { void load() }, [baseUrl, days])
  return <section aria-label="Instance usage accounting" className="grid gap-l"><div className="flex flex-wrap items-start justify-between gap-m"><div><h2 data-type="title-m">Usage accounting</h2><p data-type="body-s" className="mt-1 text-on-surface-low">Review provider attribution and import local CLI usage history without importing credentials.</p></div><div className="flex items-end gap-s"><Field label="Window"><Select ariaLabel="Accounting window" value={days} onChange={setDays} options={[{ value: '1', label: 'One day' }, { value: '30', label: 'Thirty days' }, { value: '365', label: 'One year' }]} /></Field><Button variant="secondary" onClick={() => void load()}>Refresh accounting</Button></div></div>
    <Surface className="grid gap-m p-l"><h3 data-type="headline-s">Import CLI usage history</h3><div className="grid gap-m sm:grid-cols-2"><Field label="Format"><Select ariaLabel="CLI usage format" value={format} onChange={setFormat} options={[{ value: 'claude_code_jsonl', label: 'Claude Code JSONL' }, { value: 'codex_rollout_jsonl', label: 'Codex rollout JSONL' }]} /></Field><Field label="History file"><input aria-label="CLI usage history file" type="file" accept=".jsonl,application/x-ndjson" onChange={event => setFile(event.target.files?.[0])} className="min-h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m py-2 text-sm file:mr-m file:rounded-md file:border-0 file:bg-surface-high file:px-m file:py-s" /></Field></div><div><Button disabled={!file} onClick={() => void importUsage()}>Import usage history</Button></div></Surface>
    {error && <p role="alert" className="rounded-lg bg-danger/10 px-m py-s text-sm text-danger">{error}</p>}{receipt && <p role="status" className="rounded-lg bg-primary/10 px-m py-s text-sm">Imported {receipt.imported_records} records · {receipt.duplicate_records} duplicates · {receipt.invalid_lines} invalid lines · pricing unknown</p>}
    <div className="grid gap-s sm:grid-cols-2"><Surface className="p-m"><p data-type="label-s" className="text-on-surface-low">Coverage</p><p data-type="body-m" className="mt-1">{view?.coverage}</p></Surface><Surface className="p-m"><p data-type="label-s" className="text-on-surface-low">Recorded activity</p><p data-type="body-m" className="mt-1">{view?.turns ?? 0} turns · {view?.imported_turns ?? 0} imported · {view?.unattributed_turns ?? 0} unattributed · {view?.invalid_rows ?? 0} invalid</p></Surface></div>
    <div className="overflow-x-auto rounded-lg border border-outline-variant/25"><table className="w-full min-w-[920px] text-sm"><thead className="bg-surface"><tr><th className="px-m py-s text-left">Instance</th><th className="px-m py-s text-left">Provider instance</th><th className="px-m py-s text-left">Credential binding</th><th className="px-m py-s text-left">Subscription source</th><th className="px-m py-s text-right">Turns</th><th className="px-m py-s text-right">Input / output</th><th className="px-m py-s text-right">Recorded cost</th><th className="px-m py-s text-right">Unpriced</th><th className="px-m py-s text-right">Imported</th></tr></thead><tbody>{view?.rows.map((row, index) => <tr key={index} className="border-t border-outline-variant/20"><td className="px-m py-s">{row.instance_id || 'Unknown'}</td><td className="px-m py-s">{row.provider_instance || 'Unknown'}</td><td className="px-m py-s">{row.credential_ref || 'Unknown'}</td><td className="px-m py-s">{row.subscription_source || 'Unknown'}</td><td className="px-m py-s text-right">{row.turns}</td><td className="px-m py-s text-right">{row.input_tokens} / {row.output_tokens}</td><td className="px-m py-s text-right">${row.recorded_cost_usd.toFixed(6)}</td><td className="px-m py-s text-right">{row.unpriced_turns}</td><td className="px-m py-s text-right">{row.imported_turns}{row.import_formats.length ? ` (${row.import_formats.join(', ')})` : ''}</td></tr>)}</tbody></table></div>
  </section>
}
