import { useEffect, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { Field, Select } from '../../../shared/ui/forms'
import { Surface } from '../../../shared/ui/Surface'
interface State { revision: number; enabled: boolean; listening: boolean; actual_port: number | null; active: number; capacity: number; provider: string; bind: string; port: number; peers: Record<string, string>; credentials: string[]; providers: string[]; runtime_lifecycle: string; runtime_apps: string[]; runtime_recipe: string; runtime: { app: string; recipe: string; status: string; evidence: Record<string, unknown> }; usage: { id: string; peer: string; status: string; input_tokens: number | null; output_tokens: number | null }[] }
export default function InferenceHost({ baseUrl = '' }: { baseUrl?: string }) {
  const [state, setState] = useState<State>(); const [provider, setProvider] = useState(''); const [credential, setCredential] = useState(''); const [runtimeApp, setRuntimeApp] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const url = `${baseUrl}/api/capabilities/platform/inference-host`
  const load = async () => { try { const value = await requestJson<State>(url); setState(value); setProvider(value.provider || value.providers[0] || ''); setCredential(Object.values(value.peers)[0] || value.credentials[0] || ''); setRuntimeApp(value.runtime.app || '') } catch (reason) { setError(String(reason)) } }
  useEffect(() => { void load() }, [baseUrl])
  const act = async (action: string) => { setBusy(true); setError(''); try { setState(await requestJson<State>(url, 'POST', { action, ...(action === 'configure' ? { config: { revision: state?.revision, provider, bind: '127.0.0.1', port: 0, capacity: 1, peers: { operator: credential }, runtime: { app: runtimeApp, recipe: runtimeApp ? state?.runtime_recipe : '' } } } : {}) })) } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  return <section aria-label="Inference host" className="grid gap-l"><div className="flex flex-wrap items-start justify-between gap-m"><div><h2 data-type="title-m">Local inference host</h2><p data-type="body-s" className="mt-1 max-w-[48rem] text-on-surface-low">Configure a loopback listener backed by an existing provider or a supervised runtime on this machine.</p></div><Button variant="secondary" onClick={() => void load()}>Refresh</Button></div>{error && <p role="alert" className="rounded-lg bg-danger/10 px-m py-s text-sm text-danger">{error}</p>}
    <p data-type="body-s">{state?.listening ? `Listening on ${state.bind}:${state.actual_port}` : 'Listener stopped'} · {state?.enabled ? 'Armed for restart' : 'Disarmed'} · {state?.active ?? 0} active</p><p data-type="body-s">Runtime status: {state?.runtime.status ?? 'unconfigured'}</p>
    <div className="grid gap-s sm:grid-cols-3"><Surface className="p-m"><p data-type="label-s" className="text-on-surface-low">Listener</p><p data-type="headline-s" className="mt-1">{state?.listening ? `${state.bind}:${state.actual_port}` : 'Stopped'}</p></Surface><Surface className="p-m"><p data-type="label-s" className="text-on-surface-low">Restart state</p><p data-type="headline-s" className="mt-1">{state?.enabled ? 'Armed' : 'Disarmed'}</p></Surface><Surface className="p-m"><p data-type="label-s" className="text-on-surface-low">Runtime</p><p data-type="headline-s" className="mt-1">{state?.runtime.status ?? 'Unconfigured'}</p></Surface></div>
    <Surface className="grid gap-l p-l"><div className="grid gap-m sm:grid-cols-3"><Field label="Direct provider"><Select ariaLabel="Inference provider" value={provider} onChange={setProvider} options={(state?.providers || []).map(name => ({ value: name, label: name }))} /></Field><Field label="Peer credential"><Select ariaLabel="Peer credential" value={credential} onChange={setCredential} options={(state?.credentials || []).map(name => ({ value: name, label: name }))} /></Field><Field label="Supervised runtime"><Select ariaLabel="Supervised runtime" value={runtimeApp} onChange={setRuntimeApp} options={[{ value: '', label: 'Existing provider only' }, ...(state?.runtime_apps || []).map(name => ({ value: name, label: name }))]} /></Field></div><div className="flex flex-wrap gap-s"><Button disabled={busy || !provider || !credential || state?.enabled} onClick={() => void act('configure')}>Configure loopback listener</Button><Button variant="secondary" disabled={busy || !state?.runtime.app || state.enabled} onClick={() => void act('provision')}>Provision runtime</Button><Button variant="secondary" disabled={busy || !state?.provider || state.enabled} onClick={() => void act('start')}>Start inference listener</Button><Button variant="secondary" disabled={busy || !state?.runtime.app} onClick={() => void act('readiness')}>Check runtime readiness</Button><Button variant="danger" disabled={busy || (!state?.enabled && state?.runtime.status === 'stopped')} onClick={() => void act('stop')}>Stop and disarm</Button><Button variant="secondary" onClick={() => void load()}>Refresh listener</Button></div><p data-type="caption" className="text-on-surface-low">{state?.runtime_lifecycle}</p></Surface>
    {!!state?.usage.length && <div className="overflow-x-auto rounded-lg border border-outline-variant/25"><table className="w-full min-w-[560px] text-sm"><thead className="bg-surface"><tr><th className="px-m py-s text-left">Peer</th><th className="px-m py-s text-left">Outcome</th><th className="px-m py-s text-right">Input / output tokens</th></tr></thead><tbody>{state.usage.map(row => <tr key={row.id} className="border-t border-outline-variant/20"><td className="px-m py-s">{row.peer}</td><td className="px-m py-s">{row.status}</td><td className="px-m py-s text-right tabular-nums">{row.input_tokens ?? 'Unknown'} / {row.output_tokens ?? 'Unknown'}</td></tr>)}</tbody></table></div>}
  </section>
}
