import { useEffect, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
interface State { revision: number; enabled: boolean; listening: boolean; actual_port: number | null; active: number; capacity: number; provider: string; bind: string; port: number; peers: Record<string, string>; credentials: string[]; providers: string[]; runtime_lifecycle: string; runtime_apps: string[]; runtime_recipe: string; runtime: { app: string; recipe: string; status: string; evidence: Record<string, unknown> }; usage: { id: string; peer: string; status: string; input_tokens: number | null; output_tokens: number | null }[] }
export default function InferenceHost({ baseUrl = '' }: { baseUrl?: string }) {
  const [state, setState] = useState<State>(); const [provider, setProvider] = useState(''); const [credential, setCredential] = useState(''); const [runtimeApp, setRuntimeApp] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const url = `${baseUrl}/api/capabilities/platform/inference-host`
  const load = async () => { try { const value = await requestJson<State>(url); setState(value); setProvider(value.provider || value.providers[0] || ''); setCredential(Object.values(value.peers)[0] || value.credentials[0] || ''); setRuntimeApp(value.runtime.app || '') } catch (reason) { setError(String(reason)) } }
  useEffect(() => { void load() }, [baseUrl])
  const act = async (action: string) => { setBusy(true); setError(''); try { setState(await requestJson<State>(url, 'POST', { action, ...(action === 'configure' ? { config: { revision: state?.revision, provider, bind: '127.0.0.1', port: 0, capacity: 1, peers: { operator: credential }, runtime: { app: runtimeApp, recipe: runtimeApp ? state?.runtime_recipe : '' } } } : {}) })) } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  return <section aria-label="Inference host" className="space-y-m"><h2>Private inference listener</h2><p>{state?.runtime_lifecycle}</p>{error && <p role="alert">{error}</p>}<p>{state?.listening ? `Listening on ${state.bind}:${state.actual_port}` : 'Listener stopped'} · {state?.enabled ? 'Armed for restart' : 'Disarmed'} · {state?.active ?? 0} active</p><p>Runtime status: {state?.runtime.status ?? 'unconfigured'}</p><label>Direct provider<select aria-label="Inference provider" value={provider} onChange={event => setProvider(event.target.value)}>{state?.providers.map(name => <option key={name}>{name}</option>)}</select></label><label>Peer credential<select aria-label="Peer credential" value={credential} onChange={event => setCredential(event.target.value)}>{state?.credentials.map(name => <option key={name}>{name}</option>)}</select></label><label>Supervised runtime<select aria-label="Supervised runtime" value={runtimeApp} onChange={event => setRuntimeApp(event.target.value)}><option value="">Existing provider only</option>{state?.runtime_apps.map(name => <option key={name}>{name}</option>)}</select></label><Button disabled={busy || !provider || !credential || state?.enabled} onClick={() => void act('configure')}>Configure loopback listener</Button><Button disabled={busy || !state?.runtime.app || state.enabled} onClick={() => void act('provision')}>Provision runtime</Button><Button disabled={busy || !state?.provider || state.enabled} onClick={() => void act('start')}>Start inference listener</Button><Button disabled={busy || !state?.runtime.app} onClick={() => void act('readiness')}>Check runtime readiness</Button><Button disabled={busy || (!state?.enabled && state?.runtime.status === 'stopped')} onClick={() => void act('stop')}>Stop and disarm</Button><Button onClick={() => void load()}>Refresh listener</Button><table><thead><tr><th>Peer</th><th>Outcome</th><th>Input / output tokens</th></tr></thead><tbody>{state?.usage.map(row => <tr key={row.id}><td>{row.peer}</td><td>{row.status}</td><td>{row.input_tokens ?? 'Unknown'} / {row.output_tokens ?? 'Unknown'}</td></tr>)}</tbody></table></section>
}
