import { useEffect, useState } from 'react'
import { gatewayRequest, readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
interface Row { kind: string; id: string; label: string; href: string; unit?: string; observations: unknown[]; change?: Record<string, number> | null; milestones_complete_ratio?: number | null; summary?: { completed_days: number; unrecorded_days: number } }
interface Narrative { slug: string; version: number; versions: number[]; document: { note: string; snapshot: View } }
interface View { fingerprint: string; limitation: string; rows: Row[]; coverage: { possibly_truncated: boolean }; narratives: { slug: string; name: string; version: number }[] }
export default function Insights({ baseUrl = '' }: { baseUrl?: string }) {
  const [view, setView] = useState<View>(); const [note, setNote] = useState(''); const [saved, setSaved] = useState<Narrative>(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const url = `${baseUrl}/api/capabilities/platform/insights`
  const load = async () => { try { setView(await readJson<View>(await gatewayRequest(url))); setError('') } catch (reason) { setError(String(reason)) } }
  useEffect(() => { void load() }, [baseUrl])
  const save = async () => { setBusy(true); try { const result = await readJson<Narrative>(await gatewayRequest(url, 'POST', { fingerprint: view?.fingerprint, note, ...(saved ? { slug: saved.slug, version: saved.versions.at(-1) } : {}) })); setSaved(result); await load() } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const open = async (slug: string, version?: number) => { try { const value = await readJson<Narrative>(await gatewayRequest(`${url}?slug=${encodeURIComponent(slug)}${version ? `&version=${version}` : ''}`)); setSaved(value); setNote(value.document.note); setError('') } catch (reason) { setError(String(reason)) } }
  return <section aria-label="Personal scorecards" className="space-y-m"><h2>Personal insights and scorecards</h2><p>{view?.limitation}</p>{view?.coverage.possibly_truncated && <p>Source limits reached; this scorecard may be incomplete.</p>}{error && <p role="alert">{error}</p>}<Button onClick={() => void load()}>Refresh scorecard</Button><table><thead><tr><th>Source</th><th>Observations</th><th>Recorded change</th></tr></thead><tbody>{view?.rows.map(row => <tr key={row.id}><td><a href={row.href}>{row.label}</a> ({row.kind})</td><td>{row.observations.length}</td><td>{row.change ? `${JSON.stringify(row.change)} ${row.unit}` : row.summary ? `${row.summary.completed_days} completed; ${row.summary.unrecorded_days} unrecorded days` : row.milestones_complete_ratio != null ? `${Math.round(row.milestones_complete_ratio * 100)}% milestones` : 'Unknown'}</td></tr>)}</tbody></table><label>Your narrative note<textarea aria-label="Narrative note" maxLength={8000} value={note} onChange={event => setNote(event.target.value)} /></label><Button disabled={!view || busy} onClick={() => void save()}>Save scorecard version</Button><Button onClick={() => { setSaved(undefined); setNote('') }}>New narrative</Button>{view?.narratives.map(row => <Button key={row.slug} onClick={() => void open(row.slug)}>{row.name} · v{row.version}</Button>)}{saved && <div><p>Saved version {saved.version}</p><a href={`#/artifacts/${saved.slug}`}>Open scorecard artifact</a><label>History<select aria-label="Narrative version" value={saved.version} onChange={event => void open(saved.slug, Number(event.target.value))}>{saved.versions.map(version => <option key={version} value={version}>{version}</option>)}</select></label><pre aria-label="Saved source snapshot">{JSON.stringify(saved.document.snapshot.rows, null, 2)}</pre></div>}</section>
}
