import { Select, TextInput } from '../../../shared/ui/forms'
import { BUSY_REASON } from '../../../shared/ui/unavailable'
import { useEffect, useState } from 'react'
import { gatewayRequest, readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
interface Record { id: string; repo: string; number: number; revision: number; status: string; error: string | null; source: { head_sha: string; fingerprint: string }; proposal: { event: string; body: string; reason: string } | null }
interface View { records: Record[]; credentials: string[] }
export default function PrScreening({ baseUrl = '' }: { baseUrl?: string }) {
  const [view, setView] = useState<View>(); const [repo, setRepo] = useState(''); const [number, setNumber] = useState(''); const [credential, setCredential] = useState(''); const [screenProvider, setScreenProvider] = useState(''); const [reviewProvider, setReviewProvider] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const url = `${baseUrl}/api/capabilities/platform/pr-screening`
  const load = async () => setView(await readJson<View>(await gatewayRequest(url)))
  useEffect(() => { void load().catch(reason => setError(String(reason))) }, [baseUrl])
  const mutate = async (record?: Record, action?: string) => {
    setBusy(true); setError('')
    try { await readJson(await gatewayRequest(record ? `${url}/${record.id}` : url, 'POST', record ? { action, revision: record.revision } : { repo, number: Number(number), credential, screen_provider: screenProvider, review_provider: reviewProvider })); await load() } catch (reason) { setError(String(reason)) } finally { setBusy(false) }
  }
  return <section aria-label="Pull request screening" className="grid gap-l"><h2 data-type="title-m">External pull request screening</h2><p>Capture complete GitHub content, screen it with direct API models, then explicitly authorize a comment or change request. Approval and merge are unavailable.</p>{error && <p role="alert">{error}</p>}
    <label data-type="label-s" className="grid gap-xs">Repository<TextInput className="min-h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" ariaLabel="PR repository" value={repo} onChange={value => setRepo(value)} placeholder="owner/repository" /></label>
    <label data-type="label-s" className="grid gap-xs">Number<TextInput className="min-h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" ariaLabel="PR number" type="number" value={String(number)} onChange={value => setNumber(value)} /></label>
    <label data-type="label-s" className="grid gap-xs">Credential<Select className="min-h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" ariaLabel="PR credential" value={credential} onChange={value => setCredential(value)} options={[{ value: "", label: ["Select named credential"].join('') }, ...(view?.credentials.map(name => ({ value: [name].join(''), label: [name].join('') })) ?? [])]} /></label>
    <label data-type="label-s" className="grid gap-xs">Screening provider<TextInput className="min-h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" ariaLabel="PR screening provider" value={screenProvider} onChange={value => setScreenProvider(value)} /></label><label data-type="label-s" className="grid gap-xs">Review provider<TextInput className="min-h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" ariaLabel="PR review provider" value={reviewProvider} onChange={value => setReviewProvider(value)} /></label>
    <Button disabled={busy || !repo || !number || !credential || !screenProvider || !reviewProvider} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void mutate()}>Capture pull request</Button>
    {view?.records.map(record => <article className="grid gap-s rounded-lg border border-outline-variant/20 bg-surface-container p-l" key={record.id} aria-label={`PR ${record.repo} ${record.number}`}><h3 data-type="headline-s">{record.repo} #{record.number}</h3><p role="status">{record.status}</p><p>Head: {record.source.head_sha}</p>{record.error && <p>{record.error}</p>}{record.proposal && <><p>{record.proposal.event}: {record.proposal.reason}</p><pre className="whitespace-pre-wrap">{record.proposal.body}</pre></>}<Button disabled={busy || !['captured', 'blocked'].includes(record.status)} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void mutate(record, 'screen')} ariaLabel={`Screen pull request ${record.repo} #${record.number}`}>Screen pull request</Button><Button disabled={busy || !['awaiting_authorization', 'uncertain', 'submitting'].includes(record.status)} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void mutate(record, 'authorize')}>{['uncertain', 'submitting'].includes(record.status) ? 'Reconcile existing review' : 'Authorize GitHub review'}</Button></article>)}
  </section>
}
