import { Select, TextArea, TextInput } from '../../../shared/ui/forms'
import { unavailableWhen } from '../../../shared/ui/unavailable'
import NativeMediaPage from './NativeMediaPage'
import { useEffect, useState } from 'react'
export type Dataset = { id: string; revision: number; title: string; base_model: string; entries: { artifact_id: string; version: number; caption: string }[] }
async function api(path: string, method = 'GET', body?: unknown) {
  const response = await fetch('/api/capabilities/media' + path, { method, ...(body ? { headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}) }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Dataset request failed'); return result
}
export function DatasetEntries({ entries, change }: { entries: Dataset['entries']; change: (entries: Dataset['entries']) => void }) {
  return <ol>{entries.map((entry, index) => <li key={index} className="rounded-lg bg-surface-container p-m"><p>{entry.artifact_id} · version {entry.version}</p><label>Caption<TextArea maxLength={2000} value={String(entry.caption)} onChange={nextValue => change(entries.map((item, at) => at === index ? { ...item, caption: nextValue } : item))} /></label><button onClick={() => change(entries.filter((_, at) => at !== index))}>Remove image</button></li>)}</ol>
}
export default function DatasetsPage({ onJob }: { onJob?: (id: string) => void } = {}) {
  const [items, setItems] = useState<Dataset[]>([]), [current, setCurrent] = useState<Dataset | null>(null), [title, setTitle] = useState(''), [baseModel, setBaseModel] = useState(''), [entries, setEntries] = useState<Dataset['entries']>([]), [artifactId, setArtifactId] = useState(''), [version, setVersion] = useState(1), [history, setHistory] = useState<Dataset[]>([]), [readiness, setReadiness] = useState<{ available: boolean; reason: string } | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [steps, setSteps] = useState(100), [rank, setRank] = useState(4), [rate, setRate] = useState(.0001), [seed, setSeed] = useState(0)
  useEffect(() => { Promise.all([api('/datasets'), api('/training')]).then(([list, ready]) => { setItems(list.items); setReadiness(ready) }).catch(reason => setError(String(reason))) }, [])
  const choose = async (id: string) => { if (busy) return; if (!id) { setCurrent(null); setTitle(''); setBaseModel(''); setEntries([]); setHistory([]); return }; setBusy(true); try { const item = await api('/datasets/'+id); setCurrent(item); setTitle(item.title); setBaseModel(item.base_model); setEntries(item.entries); setHistory((await api('/datasets/'+id+'/history')).items); setError('') } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const save = async () => { if (busy || !entries.length) return; setBusy(true); try { const body = { title, base_model: baseModel, entries, request_id: crypto.randomUUID(), ...(current ? { revision: current.revision } : {}) }; const saved = await api('/datasets'+(current ? '/'+current.id : ''), current ? 'PUT' : 'POST', body); setCurrent(saved); setItems((await api('/datasets')).items); setHistory((await api('/datasets/'+saved.id+'/history')).items); setError('') } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const train = async () => { if (busy || dirty || !current || !readiness?.available) return; setBusy(true); try { const job = await api('/jobs', 'POST', { operation: 'lora_train', request_id: crypto.randomUUID(), input: { dataset_id: current.id, dataset_revision: current.revision, steps, rank, learning_rate: rate, seed } }); if (onJob) onJob(job.id); else location.hash = '#/capabilities/media?view=jobs' } catch (reason) { setError(String(reason)) } finally { setBusy(false) } }
  const dirty = current ? title !== current.title || baseModel !== current.base_model || JSON.stringify(entries) !== JSON.stringify(current.entries) : !!(title || baseModel || entries.length)
  return <NativeMediaPage title="LoRA datasets and training" actions={<><a href="#/capabilities/media?view=library">Library</a><a href="#/capabilities/media?view=jobs">Jobs</a></>}>
    <p>Datasets retain pinned image references and authored captions. Each save preserves its prior revision. Training requires a separately installed and admitted Diffusers runtime; checkpoints are retained for retry.</p>
    {error && <p role="alert">{error}</p>}<label>Dataset<Select disabled={busy || dirty} value={String(current?.id || '')} onChange={nextValue => { if (busy || dirty) return; void choose(nextValue) }} options={[{ value: String(""), label: "New dataset" }, ...(items.map(item => ({ value: String(item.id), label: String(item.title) + " · revision " + String(item.revision) })) ?? [])]} /></label>
    <label>Title<TextInput maxLength={120} value={String(title)} onChange={nextValue => setTitle(nextValue)} /></label><label>Base model owner/name<TextInput value={String(baseModel)} onChange={nextValue => setBaseModel(nextValue)} /></label>
    <label>Image artifact<TextInput value={String(artifactId)} onChange={nextValue => setArtifactId(nextValue)} /></label><label>Image version<TextInput type="number" min="1" value={String(version)} onChange={nextValue => setVersion(Number(nextValue))} /></label><button {...unavailableWhen(!artifactId || entries.length >= 100, !artifactId ? 'Enter an image artifact first' : 'A dataset can contain at most 100 images')} onClick={() => { if (!artifactId || entries.length >= 100) return; setEntries(old => [...old, { artifact_id: artifactId, version, caption: '' }]); setArtifactId('') }}>Add image</button>
    <button disabled={busy} onClick={() => void choose(current?.id || '')}>Discard changes</button><DatasetEntries entries={entries} change={setEntries} /><button {...unavailableWhen(!entries.length, 'Add an image before saving a dataset revision', { busy })} onClick={() => void save()}>Save dataset revision</button>{dirty && <p role="status">Unsaved changes</p>}
    {current && <><p>Saved revision {current.revision}</p><h2>Revision exports</h2>{history.map(item => <p key={item.revision}><a href={'/api/capabilities/media/datasets/'+item.id+'/revisions/'+item.revision+'/export'}>Download revision {item.revision} ZIP</a></p>)}</>}
    <h2>Checkpoint training</h2><p role="status">{readiness?.reason || 'Loading trainer readiness…'}</p>
    <label>Steps<TextInput type="number" min="1" max="50000" value={String(steps)} onChange={nextValue => setSteps(Number(nextValue))} /></label><label>Rank<TextInput type="number" min="1" max="128" value={String(rank)} onChange={nextValue => setRank(Number(nextValue))} /></label><label>Learning rate<TextInput type="number" step="any" min="0.0000001" max="0.01" value={String(rate)} onChange={nextValue => setRate(Number(nextValue))} /></label><label>Seed<TextInput type="number" min="0" max="4294967295" value={String(seed)} onChange={nextValue => setSeed(Number(nextValue))} /></label>
    <button {...unavailableWhen(dirty || !current || !readiness?.available, dirty ? 'Save or discard dataset changes before training' : !current ? 'Save a dataset before training' : readiness?.reason || 'Trainer readiness is not available yet', { busy })} onClick={() => void train()}>Queue training</button><p>File presence does not verify GPU readiness or successful training. Training jobs retain local diagnostics and checkpoints; retries resume the latest checkpoint when present.</p>
  </NativeMediaPage>
}
