import NativeMediaPage from './NativeMediaPage'
import { useEffect, useState } from 'react'
import { Button } from '../../../shared/ui/Button'
type Scene = { prompt: string; duration_seconds: number; mode: 'establish' | 'continue' | 'reuse'; allow_fallback: boolean; artifact_id?: string; version?: number }
type Plan = { title: string; width: number; height: number; fps: number; aspect_ratio: string; scenes: Scene[] }
type Episode = Plan & { id: string; revision: number }
type SceneState = { position: number; status: string; fallback?: boolean; predecessor?: { artifact_id: string; version: number }; result?: { artifact_id: string; version: number }; error?: string }
export const newEpisode = (): Plan => ({ title: '', width: 1280, height: 720, fps: 24, aspect_ratio: '16:9', scenes: [] })
export function changeSceneMode(scene: Scene, mode: Scene['mode']): Scene { const { artifact_id: _id, version: _version, ...common } = scene; return mode === 'reuse' ? { ...common, mode, artifact_id: '', version: 1 } : { ...common, mode } }
export function SceneRows({ scenes }: { scenes: SceneState[] }) {
  return <ol>{scenes.map(scene => <li key={scene.position}>Scene {scene.position + 1}: {scene.status}{scene.predecessor && <span> · predecessor {scene.predecessor.artifact_id} v{scene.predecessor.version}</span>}{scene.fallback && <strong> · fresh establishment fallback</strong>}{scene.result && <a href={'/api/artifacts/' + encodeURIComponent(scene.result.artifact_id) + '/raw?version=' + scene.result.version}>Open clip</a>}{scene.error && <p role="alert">{scene.error}</p>}</li>)}</ol>
}
export function EpisodeScenes({ jobId }: { jobId: string }) {
  const [scenes, setScenes] = useState<SceneState[]>([]), [error, setError] = useState('')
  useEffect(() => { let live = true; const load = () => { void api('/api/capabilities/media/jobs/' + encodeURIComponent(jobId) + '/scenes').then(value => { if (live) { setScenes(value.items); setError('') } }).catch(e => { if (live) setError(e.message) }) }; load(); const timer = setInterval(load, 2000); return () => { live = false; clearInterval(timer) } }, [jobId])
  return <section><h3>Scene progress and lineage</h3><SceneRows scenes={scenes} />{error && <p role="alert">{error}</p>}</section>
}
const base = '/api/capabilities/media/episodes'
async function api(path: string, method = 'GET', body?: unknown) { const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); return value }
export default function EpisodePage() {
  const [items, setItems] = useState<Episode[]>([]), [saved, setSaved] = useState<Episode | null>(null), [draft, setDraft] = useState<Plan>(newEpisode), [history, setHistory] = useState<Episode[]>([])
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [job, setJob] = useState('')
  const clean = (value: Episode): Plan => ({ title: value.title, width: value.width, height: value.height, fps: value.fps, aspect_ratio: value.aspect_ratio, scenes: value.scenes })
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved ? clean(saved) : newEpisode())
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); try { await work() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function choose(id: string) { const value = id ? await api(base + '/' + encodeURIComponent(id)) : null; setSaved(value); setDraft(value ? clean(value) : newEpisode()); setHistory(value ? (await api(base + '/' + value.id + '/history')).items : []); setJob('') }
  useEffect(() => { void action(async () => { setItems((await api(base)).items); const id = new URLSearchParams(location.hash.split('?')[1] || '').get('episode'); if (id) await choose(id) }).finally(() => setLoading(false)) }, [])
  function update(index: number, patch: Partial<Scene>) { setDraft({ ...draft, scenes: draft.scenes.map((scene, i) => i === index ? { ...scene, ...patch } : scene) }) }
  return <NativeMediaPage title="Continuous episodes" actions={<a href="#/capabilities/media?view=jobs">Media jobs</a>}><p>Establish a scene, continue from its predecessor, or reuse a pinned clip. Provider support and credentials are required for generation. Completed clips survive retries. Continuation may use only the final frame; fresh establishment fallback requires explicit consent per scene.</p><p>Assembly mutes clip audio. Add soundtracks in the resulting timeline. Any trimmed clip must be saved as a separate artifact before continuing from it.</p>{loading && <p>Loading episodes…</p>}<fieldset disabled={loading || busy}>
    <label>Episode<select disabled={dirty} value={saved?.id || ''} onChange={e => void action(() => choose(e.target.value))}><option value="">New episode</option>{items.map(item => <option key={item.id} value={item.id}>{item.title} · revision {item.revision}</option>)}</select></label><Button disabled={!dirty} onClick={() => setDraft(saved ? clean(saved) : newEpisode())}>Discard changes</Button>
    <label>Title<input maxLength={120} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} /></label>{(['width', 'height', 'fps'] as const).map(key => <label key={key}>{key}<input type="number" value={draft[key]} onChange={e => setDraft({ ...draft, [key]: Number(e.target.value) })} /></label>)}<label>Aspect ratio<input value={draft.aspect_ratio} onChange={e => setDraft({ ...draft, aspect_ratio: e.target.value })} /></label>
    <ol>{draft.scenes.map((scene, index) => <li key={index}><h2>Scene {index + 1}</h2><label>Prompt<textarea value={scene.prompt} maxLength={4000} onChange={e => update(index, { prompt: e.target.value })} /></label><label>Mode<select value={scene.mode} onChange={e => setDraft({ ...draft, scenes: draft.scenes.map((item, i) => i === index ? changeSceneMode(item, e.target.value as Scene['mode']) : item) })}><option value="establish">Establish</option><option value="continue" disabled={index === 0}>Continue</option><option value="reuse">Reuse clip</option></select></label><label>Duration<input type="number" min={.05} max={60} step="any" value={scene.duration_seconds} onChange={e => update(index, { duration_seconds: Number(e.target.value) })} /></label>{scene.mode === 'reuse' && <><label>Artifact ID<input value={scene.artifact_id} onChange={e => update(index, { artifact_id: e.target.value })} /></label><label>Version<input type="number" min={1} value={scene.version} onChange={e => update(index, { version: Number(e.target.value) })} /></label></>}<label><input type="checkbox" checked={scene.allow_fallback} disabled={scene.mode !== 'continue'} onChange={e => update(index, { allow_fallback: e.target.checked })} />Allow fresh establishment if continuation fails</label><Button onClick={() => setDraft({ ...draft, scenes: draft.scenes.filter((_, i) => i !== index) })}>Remove scene</Button></li>)}</ol>
    <Button disabled={draft.scenes.length >= 20} onClick={() => setDraft({ ...draft, scenes: [...draft.scenes, { prompt: '', duration_seconds: 4, mode: draft.scenes.length ? 'continue' : 'establish', allow_fallback: false }] })}>Add scene</Button>
    <Button disabled={!dirty || !draft.title.trim() || !draft.scenes.length} onClick={() => void action(async () => { const value = await api(base + (saved ? '/' + saved.id : ''), saved ? 'PUT' : 'POST', { ...draft, revision: saved?.revision || 0, request_id: crypto.randomUUID() }); setSaved(value); setDraft(clean(value)); setItems((await api(base)).items); setHistory((await api(base + '/' + value.id + '/history')).items) })}>Validate and save</Button>
    <Button disabled={dirty || !saved} onClick={() => void action(async () => { const value = await api('/api/capabilities/media/jobs', 'POST', { operation: 'episode_render', request_id: crypto.randomUUID(), input: { episode_id: saved!.id, revision: saved!.revision } }); setJob(value.id) })}>Render saved episode</Button>
    {saved && <a href={'#/capabilities/media?view=episodes&episode=' + saved.id}>Episode link</a>}<h2>Revision history</h2>{history.map(item => <div key={item.revision}>Revision {item.revision}<Button disabled={dirty} onClick={() => setDraft(clean(item))}>Restore as draft</Button></div>)}</fieldset>{job && <EpisodeScenes jobId={job} />}{error && <p role="alert">{error}</p>}
  </NativeMediaPage>
}
