import { Checkbox, FieldHintProvider, Select, TextArea, TextInput } from '../../../shared/ui/forms'
import { BUSY_REASON } from '../../../shared/ui/unavailable'
import NativeMediaPage from './NativeMediaPage'
import { useEffect, useId, useState } from 'react'
import { Button } from '../../../shared/ui/Button'
type Scene = { prompt: string; duration_seconds: number; mode: 'establish' | 'continue' | 'reuse'; allow_fallback: boolean; artifact_id?: string; version?: number }
type Plan = { title: string; width: number; height: number; fps: number; aspect_ratio: string; scenes: Scene[] }
type Episode = Plan & { id: string; revision: number }
type SceneState = { position: number; status: string; fallback?: boolean; predecessor?: { artifact_id: string; version: number }; result?: { artifact_id: string; version: number }; error?: string }
export const newEpisode = (): Plan => ({ title: '', width: 1280, height: 720, fps: 24, aspect_ratio: '16:9', scenes: [] })
export function changeSceneMode(scene: Scene, mode: Scene['mode']): Scene { const { artifact_id: _id, version: _version, ...common } = scene; return mode === 'reuse' ? { ...common, mode, artifact_id: '', version: 1 } : { ...common, mode } }
export function SceneRows({ scenes }: { scenes: SceneState[] }) {
  return <ol>{scenes.map(scene => <li key={scene.position}>Scene {scene.position + 1}: {scene.status}{scene.predecessor && <span> · predecessor {scene.predecessor.artifact_id} v{scene.predecessor.version}</span>}{scene.fallback && <strong> · fresh establishment fallback</strong>}{scene.result && <a href={'/api/artifacts/' + encodeURIComponent(scene.result.artifact_id) + '/raw?version=' + scene.result.version}>Open clip</a>}{scene.error && <p role="alert">{scene.error}</p>}</li>)}</ol>
}
export function EpisodeScenes({ jobId }: { jobId: string }) {
  const [scenes, setScenes] = useState<SceneState[]>([]), [error, setError] = useState('')
  useEffect(() => { let live = true; const load = () => { void api('/api/capabilities/media/jobs/' + encodeURIComponent(jobId) + '/scenes').then(value => { if (live) { setScenes(value.items); setError('') } }).catch(e => { if (live) setError(e.message) }) }; load(); const timer = setInterval(load, 2000); return () => { live = false; clearInterval(timer) } }, [jobId])
  return <section><h3>Scene progress and lineage</h3><SceneRows scenes={scenes} />{error && <p role="alert">{error}</p>}</section>
}
const base = '/api/capabilities/media/episodes'
async function api(path: string, method = 'GET', body?: unknown) { const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); return value }
export default function EpisodePage({ episodeId }: { episodeId?: string } = {}) {
  const controlId = useId()
  const [items, setItems] = useState<Episode[]>([]), [saved, setSaved] = useState<Episode | null>(null), [draft, setDraft] = useState<Plan>(newEpisode), [history, setHistory] = useState<Episode[]>([])
  const [busy, setBusy] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [job, setJob] = useState('')
  const clean = (value: Episode): Plan => ({ title: value.title, width: value.width, height: value.height, fps: value.fps, aspect_ratio: value.aspect_ratio, scenes: value.scenes })
  const dirty = JSON.stringify(draft) !== JSON.stringify(saved ? clean(saved) : newEpisode())
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); try { await work() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function choose(id: string) { const value = id ? await api(base + '/' + encodeURIComponent(id)) : null; setSaved(value); setDraft(value ? clean(value) : newEpisode()); setHistory(value ? (await api(base + '/' + value.id + '/history')).items : []); setJob('') }
  useEffect(() => { void action(async () => { setItems((await api(base)).items); const id = episodeId ?? new URLSearchParams(location.hash.split('?')[1] || '').get('episode'); if (id) await choose(id) }).finally(() => setLoading(false)) }, [episodeId])
  function update(index: number, patch: Partial<Scene>) { setDraft({ ...draft, scenes: draft.scenes.map((scene, i) => i === index ? { ...scene, ...patch } : scene) }) }
  return <NativeMediaPage title="Continuous episodes" actions={<a href="#/capabilities/media?view=jobs">Media jobs</a>}><p>Establish a scene, continue from its predecessor, or reuse a pinned clip. Provider support and credentials are required for generation. Completed clips survive retries. Continuation may use only the final frame; fresh establishment fallback requires explicit consent per scene.</p><p>Assembly mutes clip audio. Add soundtracks in the resulting timeline. Any trimmed clip must be saved as a separate artifact before continuing from it.</p>{loading && <p>Loading episodes…</p>}<fieldset disabled={loading || busy}>
    <label>Episode<Select readOnly={dirty} readOnlyReason={dirty ? 'Save or discard draft changes before choosing another episode.' : undefined} value={String(saved?.id || '')} onChange={nextValue => { if (dirty || loading || busy) return; void action(() => choose(nextValue)) }} options={[{ value: String(""), label: "New episode" }, ...(items.map(item => ({ value: String(item.id), label: String(item.title) + " · revision " + String(item.revision) })) ?? [])]} /></label>{dirty && <p id={`${controlId}-selection`}>Save or discard draft changes before choosing another episode.</p>}<Button disabled={!dirty} onClick={() => setDraft(saved ? clean(saved) : newEpisode())} disabledReason={loading ? 'Loading episodes…' : busy ? BUSY_REASON : !dirty ? 'There are no unsaved changes to discard.' : undefined}>Discard changes</Button>
    <label>Title<TextInput maxLength={120} value={String(draft.title)} onChange={nextValue => setDraft({ ...draft, title: nextValue })} /></label>{(['width', 'height', 'fps'] as const).map(key => <label key={key}>{key}<TextInput type="number" value={String(draft[key])} onChange={nextValue => setDraft({ ...draft, [key]: Number(nextValue) })} /></label>)}<label>Aspect ratio<TextInput value={String(draft.aspect_ratio)} onChange={nextValue => setDraft({ ...draft, aspect_ratio: nextValue })} /></label>
    <ol>{draft.scenes.map((scene, index) => <li key={index}><h2>Scene {index + 1}</h2><label>Prompt<TextArea value={String(scene.prompt)} maxLength={4000} onChange={nextValue => update(index, { prompt: nextValue })} /></label><label>Mode<FieldHintProvider value={index === 0 ? `${controlId}-mode-${index}` : undefined}><Select value={String(scene.mode)} onChange={nextValue => { if (index === 0 && nextValue === 'continue') return; setDraft({ ...draft, scenes: draft.scenes.map((item, i) => i === index ? changeSceneMode(item, nextValue as Scene['mode']) : item) }) }} options={[{ value: String("establish"), label: "Establish" }, { value: String("continue"), label: "Continue", disabled: index === 0 }, { value: String("reuse"), label: "Reuse clip" }]} /></FieldHintProvider></label>{index === 0 && <p id={`${controlId}-mode-${index}`}>The first scene has no previous scene to continue.</p>}<label>Duration<TextInput type="number" min={.05} max={60} step="any" value={String(scene.duration_seconds)} onChange={nextValue => update(index, { duration_seconds: Number(nextValue) })} /></label>{scene.mode === 'reuse' && <><label>Artifact ID<TextInput value={String(scene.artifact_id)} onChange={nextValue => update(index, { artifact_id: nextValue })} /></label><label>Version<TextInput type="number" min={1} value={String(scene.version)} onChange={nextValue => update(index, { version: Number(nextValue) })} /></label></>}<label><Checkbox checked={scene.allow_fallback} readOnly={scene.mode !== 'continue'} readOnlyReason={scene.mode !== 'continue' ? 'Choose Continue mode to enable fallback.' : undefined} onChange={nextValue => { if (busy || loading || scene.mode !== 'continue') return; update(index, { allow_fallback: nextValue }) }} ariaLabel={"Allow fresh establishment if continuation fails"} />Allow fresh establishment if continuation fails</label>{scene.mode !== 'continue' && <p id={`${controlId}-fallback-${index}`}>Choose Continue mode to enable fallback.</p>}<Button onClick={() => setDraft({ ...draft, scenes: draft.scenes.filter((_, i) => i !== index) })}>Remove scene</Button></li>)}</ol>
    <Button disabled={draft.scenes.length >= 20} onClick={() => setDraft({ ...draft, scenes: [...draft.scenes, { prompt: '', duration_seconds: 4, mode: draft.scenes.length ? 'continue' : 'establish', allow_fallback: false }] })} disabledReason={loading ? 'Loading episodes…' : busy ? BUSY_REASON : draft.scenes.length >= 20 ? "The episode already has the maximum 20 scenes." : undefined}>Add scene</Button>
    <Button disabled={!dirty || !draft.title.trim() || !draft.scenes.length} onClick={() => void action(async () => { const value = await api(base + (saved ? '/' + saved.id : ''), saved ? 'PUT' : 'POST', { ...draft, revision: saved?.revision || 0, request_id: crypto.randomUUID() }); setSaved(value); setDraft(clean(value)); setItems((await api(base)).items); setHistory((await api(base + '/' + value.id + '/history')).items) })} disabledReason={loading ? 'Loading episodes…' : busy ? BUSY_REASON : !dirty ? 'Make a draft change before saving.' : !draft.title.trim() ? 'Enter an episode title before saving.' : !draft.scenes.length ? 'Add at least one scene before saving.' : undefined}>Validate and save</Button>
    <Button disabled={dirty || !saved} onClick={() => void action(async () => { const value = await api('/api/capabilities/media/jobs', 'POST', { operation: 'episode_render', request_id: crypto.randomUUID(), input: { episode_id: saved!.id, revision: saved!.revision } }); setJob(value.id) })} disabledReason={loading ? 'Loading episodes…' : busy ? BUSY_REASON : dirty ? 'Save or discard draft changes before rendering.' : !saved ? 'Save an episode before rendering.' : undefined}>Render saved episode</Button>
    {saved && <a href={'#/capabilities/media?view=episodes&episode=' + saved.id}>Episode link</a>}<h2>Revision history</h2>{history.map(item => <div key={item.revision}>Revision {item.revision}<Button ariaLabel={`Restore ${item.title || 'episode'} revision ${item.revision} as draft`} disabled={dirty} onClick={() => setDraft(clean(item))} disabledReason={loading ? 'Loading episodes…' : busy ? BUSY_REASON : dirty ? "Save or discard the current draft before selecting/restoring another episode." : undefined}>Restore as draft</Button></div>)}</fieldset>{job && <EpisodeScenes jobId={job} />}{error && <p role="alert">{error}</p>}
  </NativeMediaPage>
}
