import NativeMediaPage from './NativeMediaPage'
import { useEffect, useState } from 'react'
import { Button } from '../../../shared/ui/Button'
type Frame = { name: string; artifact_id: string; version: number; sha256: string; approved: boolean; animation: string; direction: string }
type LayoutFrame = Frame & { frame: { x: number; y: number; w: number; h: number }; sourceSize: { w: number; h: number }; spriteSourceSize: { x: number; y: number } }
type Manifest = { fps: number; atlas: { artifact_id: string; version: number }; frames: LayoutFrame[] }
export const newFrame = (index: number): Frame => ({ name: 'frame-' + index, artifact_id: '', version: 1, sha256: '', approved: false, animation: 'idle', direction: 'down' })
export function editFrame(frame: Frame, patch: Partial<Frame>): Frame { return { ...frame, ...patch, ...('artifact_id' in patch || 'version' in patch ? { sha256: '', approved: false } : {}) } }
export function generationFrames(text: string, animation: string, direction: string) { return text.split('\n').map(line => line.trim()).filter(Boolean).map((prompt, index) => ({ name: 'frame-' + (index + 1), prompt, animation, direction })) }
export function frameStyle(frame: LayoutFrame, atlas: Manifest['atlas']) { return { width: frame.frame.w, height: frame.frame.h, position: 'absolute' as const, left: frame.spriteSourceSize.x, top: frame.spriteSourceSize.y, backgroundImage: `url("/api/artifacts/${encodeURIComponent(atlas.artifact_id)}/raw?version=${atlas.version}")`, backgroundPosition: `-${frame.frame.x}px -${frame.frame.y}px`, imageRendering: 'pixelated' as const } }
export function AtlasPreview({ manifest }: { manifest: Manifest }) {
  const [track, setTrack] = useState(''), [index, setIndex] = useState(0), [playing, setPlaying] = useState(true)
  const tracks = [...new Set(manifest.frames.map(frame => frame.animation + '/' + frame.direction))]
  const frames = manifest.frames.filter(frame => !track || frame.animation + '/' + frame.direction === track)
  useEffect(() => { setIndex(0); if (!playing || !frames.length) return; const timer = setInterval(() => setIndex(value => (value + 1) % frames.length), 1000 / manifest.fps); return () => clearInterval(timer) }, [track, playing, manifest])
  const frame = frames[index % frames.length]
  return <section><h2>Atlas animation preview</h2><label>Animation / direction<select value={track} onChange={e => setTrack(e.target.value)}><option value="">All frames</option>{tracks.map(value => <option key={value}>{value}</option>)}</select></label><Button onClick={() => setPlaying(!playing)}>{playing ? 'Pause' : 'Play'}</Button>{frame && <><p>{frame.name}</p><div aria-label="Sprite frame" style={{ position: 'relative', width: frame.sourceSize.w, height: frame.sourceSize.h }}><div style={frameStyle(frame, manifest.atlas)} /></div></>}</section>
}
async function api(path: string, method = 'GET', body?: unknown) { const response = await fetch(path, { method, headers: { 'Content-Type': 'application/json' }, body: body === undefined ? undefined : JSON.stringify(body) }); const value = await response.json(); if (!response.ok) throw new Error(value.error); return value }
export default function SpritePage() {
  const [title, setTitle] = useState(''), [frames, setFrames] = useState<Frame[]>([]), [prompts, setPrompts] = useState(''), [direction, setDirection] = useState('down'), [animation, setAnimation] = useState('idle')
  const [reviewed, setReviewed] = useState<Record<string, boolean>>({})
  const [settings, setSettings] = useState({ cell_width: 64, cell_height: 64, columns: 4, padding: 1, trim: true, fps: 8 })
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [jobId, setJobId] = useState(''), [manifest, setManifest] = useState<Manifest | null>(null)
  async function action(work: () => Promise<void>) { setBusy(true); setError(''); try { await work() } catch (e) { setError((e as Error).message) } finally { setBusy(false) } }
  async function load(id: string) { const job = await api('/api/capabilities/media/jobs/' + encodeURIComponent(id)); setTitle(job.input?.title || ''); setReviewed({}); if (job.operation === 'sprite_generate') { const value = await api('/api/capabilities/media/jobs/' + encodeURIComponent(id) + '/frames'); setFrames(value.items.map((frame: Frame) => ({ name: frame.name, artifact_id: frame.artifact_id, version: frame.version, sha256: frame.sha256, approved: false, animation: frame.animation, direction: frame.direction }))); setManifest(null) } else if (job.operation === 'sprite_compile') setManifest(await api('/api/capabilities/media/jobs/' + encodeURIComponent(id) + '/atlas')); else throw new Error('Job is not a sprite job') }
  useEffect(() => { const id = new URLSearchParams(location.hash.split('?')[1] || '').get('job'); if (id) { setJobId(id); void action(() => load(id)) } }, [])
  async function submit(operation: string, input: unknown) { const job = await api('/api/capabilities/media/jobs', 'POST', { operation, request_id: crypto.randomUUID(), input }); setJobId(job.id) }
  return <NativeMediaPage title="Sprite production" actions={<a href="#/capabilities/media?view=jobs">Media jobs</a>}><p>Generate named frames with the selected image provider or inspect existing canonical images. Review pixels and explicitly approve each exact hash before compilation. Trimming preserves alpha and source offsets; frames never resize implicitly. Generation availability does not prove directional or temporal consistency.</p><fieldset disabled={busy}><label>Title<input value={title} maxLength={120} onChange={e => setTitle(e.target.value)} /></label><h2>Generate frames</h2><label>One prompt per line<textarea value={prompts} onChange={e => setPrompts(e.target.value)} /></label><label>Animation<input value={animation} onChange={e => setAnimation(e.target.value)} /></label><label>Direction<input value={direction} onChange={e => setDirection(e.target.value)} /></label><Button disabled={!title.trim() || !prompts.trim()} onClick={() => void action(() => submit('sprite_generate', { title, frames: generationFrames(prompts, animation, direction) }))}>Generate unapproved frames</Button>
    <h2>Inspect and approve</h2>{frames.map((frame, index) => <article key={index}><h3>{frame.name}</h3>{(['name', 'artifact_id', 'version', 'animation', 'direction'] as const).map(key => <label key={key}>{key.replaceAll('_', ' ')}<input type={key === 'version' ? 'number' : 'text'} value={frame[key]} onChange={e => setFrames(frames.map((item, i) => i === index ? editFrame(item, { [key]: key === 'version' ? Number(e.target.value) : e.target.value }) : item))} /></label>)}<Button disabled={!frame.artifact_id} onClick={() => void action(async () => { const value = await api('/api/capabilities/media/sprites/inspect', 'POST', { artifact_id: frame.artifact_id, version: frame.version }); setFrames(frames.map((item, i) => i === index ? { ...item, sha256: value.sha256, approved: false } : item)) })}>Inspect exact version</Button>{frame.sha256 && <><img onLoad={() => setReviewed(previous => ({ ...previous, [frame.artifact_id + ':' + frame.version + ':' + frame.sha256]: true }))} onError={() => { setReviewed(previous => ({ ...previous, [frame.artifact_id + ':' + frame.version + ':' + frame.sha256]: false })); setFrames(previous => previous.map(item => item.artifact_id === frame.artifact_id && item.version === frame.version ? { ...item, approved: false } : item)); setError('Frame image could not be loaded for review') }} alt={frame.name + ' review'} src={'/api/artifacts/' + encodeURIComponent(frame.artifact_id) + '/raw?version=' + frame.version} style={{ maxWidth: 256, imageRendering: 'pixelated' }} /><code>{frame.sha256}</code></>}<label><input type="checkbox" disabled={!frame.sha256 || !reviewed[frame.artifact_id + ':' + frame.version + ':' + frame.sha256]} checked={frame.approved} onChange={e => setFrames(frames.map((item, i) => i === index ? { ...item, approved: e.target.checked } : item))} />Approve these pixels</label><Button onClick={() => setFrames(frames.filter((_, i) => i !== index))}>Remove frame</Button></article>)}<Button disabled={frames.length >= 64} onClick={() => setFrames([...frames, newFrame(frames.length + 1)])}>Add existing frame</Button>
    <h2>Compile atlas</h2>{(['cell_width', 'cell_height', 'columns', 'padding', 'fps'] as const).map(key => <label key={key}>{key.replaceAll('_', ' ')}<input type="number" value={settings[key]} onChange={e => setSettings({ ...settings, [key]: Number(e.target.value) })} /></label>)}<label><input type="checkbox" checked={settings.trim} onChange={e => setSettings({ ...settings, trim: e.target.checked })} />Trim transparent borders</label><Button disabled={!title.trim() || !frames.length || frames.some(frame => !frame.approved)} onClick={() => void action(() => submit('sprite_compile', { title, frames, ...settings }))}>Compile approved atlas</Button>
    <Button disabled={!frames.length} onClick={() => { setFrames([]); setReviewed({}); setManifest(null) }}>Discard frame draft</Button><label>Sprite job ID<input value={jobId} onChange={e => setJobId(e.target.value)} /></label><Button disabled={!jobId || !!frames.length} onClick={() => void action(() => load(jobId))}>Load frames or atlas</Button>{jobId && <a href="#/capabilities/media?view=jobs">Track job status</a>}</fieldset>{manifest && <><AtlasPreview manifest={manifest} /><a href={'/api/artifacts/' + encodeURIComponent(manifest.atlas.artifact_id) + '/raw?version=' + manifest.atlas.version}>Download PNG</a><a href={'/api/capabilities/media/jobs/' + encodeURIComponent(jobId) + '/atlas'}>Download JSON layout</a></>}{error && <p role="alert">{error}</p>}
  </NativeMediaPage>
}
