import { useEffect, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
const nativeControl = 'block h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary'

type Source = { id: string; name: string; kind: string; calendar_id: string; credential_ref: string; timezone: string; revision: number; sync: { state: string; coverage: string; error?: string } }
type Review = { timezone: string; coverage: string; events: { id: string; source_id: string; title: string; start: string; end: string; all_day: boolean; location: string; recurrence_unexpanded: boolean }[] }
const base = '/api/capabilities/communications/calendar'
const empty = { name: '', kind: 'ics', calendar_id: 'primary', credential_ref: '', timezone: 'UTC' }
export function CalendarPanel() {
  const [sources, setSources] = useState<Source[]>([])
  const [form, setForm] = useState(empty)
  const [editing, setEditing] = useState<{ id: string; revision: number } | null>(null)
  const [sourceId, setSourceId] = useState(() => new URLSearchParams(location.hash.split('?')[1] || '').get('calendar_source') || '')
  const [content, setContent] = useState('')
  const year = new Date().getUTCFullYear()
  const [windowStart, setWindowStart] = useState(`${year}-01-01`)
  const [windowEnd, setWindowEnd] = useState(`${year + 1}-01-01`)
  const [day, setDay] = useState(new Date().toISOString().slice(0, 10))
  const [timezone, setTimezone] = useState('UTC')
  const [review, setReview] = useState<Review | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  const selected = sources.find(row => row.id === sourceId)
  const reload = async () => setSources((await requestJson<{ sources: Source[] }>(base + '/sources')).sources)
  const select = (id: string) => { setSourceId(id); const params = new URLSearchParams(location.hash.split('?')[1] || ''); params.set('calendar_source', id); location.hash = '#/capabilities/communications?' + params.toString() }
  const run = async (operation: () => Promise<void>) => { setBusy(true); setError(''); try { await operation() } catch (e) { setError(String(e)) } finally { setBusy(false) } }
  useEffect(() => { let active = true; requestJson<{ sources: Source[] }>(base + '/sources').then(data => { if (active) setSources(data.sources) }).catch(e => { if (active) setError(String(e)) }); return () => { active = false } }, [])
  return <section aria-label="Calendar daily review" className="space-y-l"><h2 data-type="title-m">Calendar daily review</h2><p data-type="body-s" className="text-on-surface-low">Review mirrored events by local day. Snapshot coverage is separate from live calendar access. ICS recurrence, exclusions, additions, overrides and cancellations are expanded within the selected bounded window.</p>{error && <p role="alert" className="rounded-lg bg-danger-container p-m text-on-danger-container">{error}</p>}
    <form className="space-y-m rounded-lg bg-surface-container px-l py-l" onSubmit={e => { e.preventDefault(); void run(async () => { const data = await requestJson<{ source: Source }>(base + '/sources' + (editing ? '/' + editing.id : ''), editing ? 'PUT' : 'POST', editing ? { ...form, revision: editing.revision } : form); await reload(); select(data.source.id); setForm(empty); setEditing(null) }) }}>
      <label className="block">Calendar name<input className={nativeControl} required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></label><label className="block">Calendar kind<select className={nativeControl} disabled={Boolean(editing)} value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value })}><option value="ics">ICS export</option><option value="google">Google Calendar</option><option value="outlook">Outlook</option></select></label>
      <label className="block">Calendar source timezone<input className={nativeControl} required value={form.timezone} onChange={e => setForm({ ...form, timezone: e.target.value })} /></label>{form.kind !== 'ics' && <><label className="block">Remote calendar ID<input className={nativeControl} required value={form.calendar_id} onChange={e => setForm({ ...form, calendar_id: e.target.value })} /></label><label className="block">Calendar credential reference<input className={nativeControl} required value={form.credential_ref} onChange={e => setForm({ ...form, credential_ref: e.target.value })} /></label></>}<Button type="submit" disabled={busy}>{editing ? 'Save calendar changes' : 'Create calendar source'}</Button>{editing && <Button type="button" onClick={() => { setEditing(null); setForm(empty) }}>Cancel calendar edit</Button>}
    </form>
    <label className="block">Calendar source<select className={nativeControl} value={sourceId} onChange={e => select(e.target.value)}><option value="">Select calendar</option>{sources.map(row => <option value={row.id} key={row.id}>{row.name}</option>)}</select></label>
    {selected && <div><Button disabled={busy} onClick={() => { setEditing({ id: selected.id, revision: selected.revision }); setForm({ name: selected.name, kind: selected.kind, calendar_id: selected.calendar_id, credential_ref: selected.credential_ref, timezone: selected.timezone }) }}>Edit calendar source</Button><p>Calendar sync: {selected.sync.state}; {selected.sync.coverage}</p>{selected.sync.error && <p>{selected.sync.error}</p>}{selected.kind === 'ics' ? <><label className="block">ICS recurrence window start<input className={nativeControl} type="date" value={windowStart} onChange={e => setWindowStart(e.target.value)} /></label><label className="block">ICS recurrence window end<input className={nativeControl} type="date" value={windowEnd} onChange={e => setWindowEnd(e.target.value)} /></label><label className="block">ICS export content<textarea className="block min-h-28 w-full resize-y rounded-md border border-outline-variant/30 bg-surface-container px-m py-s text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary" value={content} onChange={e => setContent(e.target.value)} /></label><Button disabled={busy || !content || !windowStart || !windowEnd} onClick={() => void run(async () => { await requestJson(`${base}/sources/${selected.id}/upload`, 'POST', { content, revision: selected.revision, window_start: windowStart + 'T00:00:00+00:00', window_end: windowEnd + 'T00:00:00+00:00' }); setContent(''); await reload() })}>Import calendar export</Button></> : <Button disabled={busy} onClick={() => void run(async () => { try { const start = new Date(day + 'T00:00:00Z'); const end = new Date(start.getTime() + 7 * 86400000); await requestJson(`${base}/sources/${selected.id}/sync`, 'POST', { start: start.toISOString(), end: end.toISOString() }) } finally { await reload() } })}>Sync calendar week</Button>}</div>}
    <label className="block">Review date<input className={nativeControl} type="date" value={day} onChange={e => setDay(e.target.value)} /></label><label className="block">Review timezone<input className={nativeControl} value={timezone} onChange={e => setTimezone(e.target.value)} /></label><Button disabled={busy} onClick={() => void run(async () => setReview(await requestJson<Review>(`${base}/daily?date=${encodeURIComponent(day)}&timezone=${encodeURIComponent(timezone)}`)))}>Review calendar day</Button>
    {review && <div><p>Review coverage: {review.coverage}</p>{review.events.length === 0 && <p>No mirrored events on this date.</p>}{review.events.map(row => <article className="rounded-lg border border-outline-variant/20 bg-surface px-l py-m" key={row.source_id + row.id}><h3 data-type="title-s">{row.title || '(Untitled event)'}</h3><p>{row.all_day ? 'All day' : new Date(row.start).toLocaleString(undefined, { timeZone: review.timezone })} — {row.all_day ? row.end : new Date(row.end).toLocaleString(undefined, { timeZone: review.timezone })}</p><p>{row.location}</p></article>)}</div>}
  </section>
}
