import { TextInput, Field, Select, Checkbox } from '../../../shared/ui/forms'
import { useEffect, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { BUSY_REASON } from '../../../shared/ui/unavailable'
const base = '/api/capabilities/communications/stacker'
type Account = { id: string; handle: string; platform: string; status: string }
type Territory = { name: string; state: string; coverage: string; error?: string; base_cost_sats?: number; reply_cost_sats?: number; cursor?: string; posts: { id: string; title: string; text: string; url: string }[] }
type Action = { territory: string; id: string; kind: string; title: string; text: string; item_id: string; sats: number; state: string; revision: number; registration_changed?: boolean; handoff_url?: string; provider_state?: string; cost_msats?: string; payin_id?: number; error?: string }
const empty = { kind: 'discussion', territory: 'bitcoin', title: '', text: '', item_id: '', sats: 0 }
export function StackerPanel() {
  const [accounts, setAccounts] = useState<Account[]>([])
  const [id, setId] = useState(() => new URLSearchParams(location.hash.split('?')[1] || '').get('stacker_account') || '')
  const [actions, setActions] = useState<Action[]>([])
  const [territories, setTerritories] = useState<Territory[]>([])
  const [territory, setTerritory] = useState('bitcoin')
  const [form, setForm] = useState(empty)
  const [key, setKey] = useState(() => crypto.randomUUID())
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [executeId, setExecuteId] = useState('')
  const run = async (operation: () => Promise<void>) => { setBusy(true); setError(''); try { await operation() } catch (e) { setError(String(e)) } finally { setBusy(false) } }
  const reload = async (accountId = id) => { if (accountId) setActions((await requestJson<{ actions: Action[] }>(`${base}/accounts/${accountId}/actions`)).actions) }
  const loadAccounts = async () => setAccounts((await requestJson<{ accounts: Account[] }>('/api/capabilities/communications/social/accounts')).accounts.filter(row => row.platform === 'stackernews' && row.status === 'active'))
  useEffect(() => { void run(async () => { await loadAccounts(); setTerritories((await requestJson<{ territories: Territory[] }>(base + '/territories')).territories); await reload() }) }, [])
  const read = async (name: string, cursor?: string) => { const result = await requestJson<{ territory: Territory }>(base + '/territories', 'POST', { name, ...(cursor ? { cursor } : {}) }); setTerritories(rows => [...rows.filter(row => row.name !== name), result.territory]) }
  return <section aria-label="Stacker News workflow" className="space-y-l"><h2 data-type="title-m">Stacker News workflow</h2><p data-type="body-s" className="text-on-surface-low">Review territory pages and prepare actions. Discussion/comment submission may immediately post and charge provider fees. Separate wallet payment is unavailable. API-key zaps require browser completion.</p>{error && <p role="alert" className="rounded-lg bg-error-container p-m text-on-error-container">{error}</p>}
    <Field label={"Territory name"}><TextInput value={territory} onChange={nextValue => setTerritory(nextValue)} /></Field><Button disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void run(() => read(territory))}>Read territory</Button>{territories.map(row => <article className="rounded-lg border border-outline-variant/20 bg-surface px-l py-m" key={row.name}><h3 data-type="title-s">~{row.name}</h3><p>Territory: {row.state}; {row.coverage}</p>{row.error && <p>{row.error}</p>}{row.base_cost_sats !== undefined && <p>Snapshot fees: post {row.base_cost_sats} sats; reply {row.reply_cost_sats} sats. Final fees are provider-determined.</p>}{row.posts.map(post => <p key={post.id}><a href={post.url} target="_blank" rel="noopener noreferrer">{post.title || post.id}</a> {post.text}</p>)}{row.cursor && <Button ariaLabel={`Next territory page: ~${row.name}`} disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void run(() => read(row.name, row.cursor))}>Next territory page</Button>}</article>)}
    <Button disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void run(loadAccounts)}>Refresh Stacker registrations</Button><Field label={"Stacker registration"}><Select disabled={busy} value={id} onChange={nextValue => { const value = nextValue; setId(value); setActions([]); setExecuteId(''); const params = new URLSearchParams(location.hash.split('?')[1] || ''); params.set('stacker_account', value); location.hash = '#/capabilities/communications?' + params.toString(); void run(() => reload(value)) }} options={[{ value: "", label: "Select active Stacker registration" }, ...(accounts.map(row => ({ value: row.id, label: "@" + String(row.handle) })))]} /></Field>
    {id && <><Button disabled={busy} disabledReason={busy ? BUSY_REASON : undefined} onClick={() => void run(() => reload())}>Reload Stacker actions</Button><form className="space-y-m rounded-lg bg-surface-container px-l py-l" onSubmit={e => { e.preventDefault(); void run(async () => { await requestJson(`${base}/accounts/${id}/actions`, 'POST', { ...form, request_key: key }); setForm(empty); setKey(crypto.randomUUID()); await reload() }) }}>
      <Field label={"Stacker action kind"}><Select value={form.kind} onChange={nextValue => setForm({ ...form, kind: nextValue, sats: 0 })} options={[...(['discussion', 'comment', 'zap'].map(kind => ({ value: String(kind), label: String(kind) })))]} /></Field>{(['territory', 'title', 'text', 'item_id'] as const).map(field => <Field label={"Action" + " " + String(field)} key={field}><TextInput value={form[field]} onChange={nextValue => setForm({ ...form, [field]: nextValue })} /></Field>)}{form.kind === 'zap' && <Field label={"Zap sats"}><TextInput type="number" min={1} max={1000000} value={String(form.sats)} onChange={nextValue => setForm({ ...form, sats: Number(nextValue) })} /></Field>}<Button type="submit" disabled={busy} disabledReason={busy ? BUSY_REASON : undefined}>Prepare Stacker action</Button>
    </form>{actions.map(action => <article className="rounded-lg border border-outline-variant/20 bg-surface px-l py-m" key={action.id}><h3 data-type="title-s">{action.kind}: {action.title || action.item_id}</h3><p>Action territory: ~{action.territory}; target item: {action.item_id || 'new discussion'}</p><p>{action.text}</p>{action.kind === 'zap' && <p>Requested zap: {action.sats} sats</p>}<p>Stacker action: {action.state}; revision {action.revision}</p>{action.registration_changed && <p>Registration changed; create a new reviewed action.</p>}{action.error && <p>{action.error}</p>}{action.state === 'draft' && <Button ariaLabel={`Confirm Stacker review: ${action.title || action.text.trim().slice(0, 80) || 'untitled action'} in ~${action.territory}`} disabled={busy || action.registration_changed} disabledReason={busy ? BUSY_REASON : action.registration_changed ? 'Registration changed. Create a new reviewed action.' : undefined} onClick={() => void run(async () => { await requestJson(`${base}/accounts/${id}/actions/${action.id}/review`, 'POST', { revision: action.revision, confirm_review: true }); await reload() })}>Confirm Stacker review</Button>}{action.handoff_url && <a href={action.handoff_url} target="_blank" rel="noopener noreferrer">Open reviewed Stacker destination</a>}{action.state === 'reviewed' && action.kind !== 'zap' && !action.registration_changed && <><label className="block"><Checkbox checked={executeId === action.id} onChange={nextValue => setExecuteId(nextValue ? action.id : '')} ariaLabel={"Approve this exact action; provider may post and charge fees"} />Approve this exact action; provider may post and charge fees</label><Button ariaLabel={`Submit reviewed Stacker action: ${action.title || action.text.trim().slice(0, 80) || 'untitled action'} in ~${action.territory}`} disabled={busy || executeId !== action.id} disabledReason={busy ? BUSY_REASON : executeId !== action.id ? 'Approve this exact reviewed action before submitting it.' : undefined} onClick={() => void run(async () => { try { await requestJson(`${base}/accounts/${id}/actions/${action.id}/submit`, 'POST', { revision: action.revision, confirm_execute: true }) } finally { setExecuteId(''); await reload() } })}>Submit reviewed Stacker action</Button></>}{action.payin_id && <><p>PayIn {action.payin_id}: {action.provider_state}; cost {action.cost_msats} msats</p><Button ariaLabel={`Read PayIn status: ${action.title || action.text.trim().slice(0, 80) || 'untitled action'} in ~${action.territory}`} disabled={busy || action.registration_changed} disabledReason={busy ? BUSY_REASON : action.registration_changed ? 'Registration changed. Create a new reviewed action.' : undefined} onClick={() => void run(async () => { await requestJson(`${base}/accounts/${id}/actions/${action.id}/reconcile`, 'POST', {}); await reload() })}>Read PayIn status</Button></>}</article>)}</>}
  </section>
}
