import { useEffect, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
const nativeControl = 'block h-10 w-full rounded-md border border-outline-variant/30 bg-surface-container px-m text-on-surface outline-none transition-colors focus:border-primary/40 focus:ring-2 focus:ring-inset focus:ring-primary'
const base = '/api/capabilities/communications/stacker'
type Account = { id: string; handle: string; platform: string; status: string }
type Territory = { name: string; state: string; coverage: string; error?: string; base_cost_sats?: number; reply_cost_sats?: number; cursor?: string; posts: { id: string; title: string; text: string; url: string }[] }
type Action = { territory: string; id: string; kind: string; title: string; text: string; item_id: string; sats: number; state: string; revision: number; registration_changed?: boolean; handoff_url?: string; provider_state?: string; cost_msats?: string; payin_id?: number; error?: string }
const empty = { kind: 'discussion', territory: 'bitcoin', title: '', text: '', item_id: '', sats: 0 }
export function StackerPanel() {
  const [accounts, setAccounts] = useState<Account[]>([])
  const [id, setId] = useState(() => new URLSearchParams(location.hash.split('?')[1] || '').get('stacker_account') || '')
  const [actions, setActions] = useState<Action[]>([])
  const [territories, setTerritories] = useState<Territory[]>([])
  const [territory, setTerritory] = useState('bitcoin')
  const [form, setForm] = useState(empty)
  const [key, setKey] = useState(() => crypto.randomUUID())
  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [executeId, setExecuteId] = useState('')
  const run = async (operation: () => Promise<void>) => { setBusy(true); setError(''); try { await operation() } catch (e) { setError(String(e)) } finally { setBusy(false) } }
  const reload = async (accountId = id) => { if (accountId) setActions((await requestJson<{ actions: Action[] }>(`${base}/accounts/${accountId}/actions`)).actions) }
  const loadAccounts = async () => setAccounts((await requestJson<{ accounts: Account[] }>('/api/capabilities/communications/social/accounts')).accounts.filter(row => row.platform === 'stackernews' && row.status === 'active'))
  useEffect(() => { void run(async () => { await loadAccounts(); setTerritories((await requestJson<{ territories: Territory[] }>(base + '/territories')).territories); await reload() }) }, [])
  const read = async (name: string, cursor?: string) => { const result = await requestJson<{ territory: Territory }>(base + '/territories', 'POST', { name, ...(cursor ? { cursor } : {}) }); setTerritories(rows => [...rows.filter(row => row.name !== name), result.territory]) }
  return <section aria-label="Stacker News workflow" className="space-y-l"><h2 data-type="title-m">Stacker News workflow</h2><p data-type="body-s" className="text-on-surface-low">Review territory pages and prepare actions. Discussion/comment submission may immediately post and charge provider fees. Separate wallet payment is unavailable. API-key zaps require browser completion.</p>{error && <p role="alert" className="rounded-lg bg-danger-container p-m text-on-danger-container">{error}</p>}
    <label className="block">Territory name<input className={nativeControl} value={territory} onChange={e => setTerritory(e.target.value)} /></label><Button disabled={busy} onClick={() => void run(() => read(territory))}>Read territory</Button>{territories.map(row => <article className="rounded-lg border border-outline-variant/20 bg-surface px-l py-m" key={row.name}><h3 data-type="title-s">~{row.name}</h3><p>Territory: {row.state}; {row.coverage}</p>{row.error && <p>{row.error}</p>}{row.base_cost_sats !== undefined && <p>Snapshot fees: post {row.base_cost_sats} sats; reply {row.reply_cost_sats} sats. Final fees are provider-determined.</p>}{row.posts.map(post => <p key={post.id}><a href={post.url} target="_blank" rel="noopener noreferrer">{post.title || post.id}</a> {post.text}</p>)}{row.cursor && <Button disabled={busy} onClick={() => void run(() => read(row.name, row.cursor))}>Next territory page</Button>}</article>)}
    <Button disabled={busy} onClick={() => void run(loadAccounts)}>Refresh Stacker registrations</Button><label className="block">Stacker registration<select className={nativeControl} disabled={busy} value={id} onChange={e => { const value = e.target.value; setId(value); setActions([]); setExecuteId(''); const params = new URLSearchParams(location.hash.split('?')[1] || ''); params.set('stacker_account', value); location.hash = '#/capabilities/communications?' + params.toString(); void run(() => reload(value)) }}><option value="">Select active Stacker registration</option>{accounts.map(row => <option value={row.id} key={row.id}>@{row.handle}</option>)}</select></label>
    {id && <><Button disabled={busy} onClick={() => void run(() => reload())}>Reload Stacker actions</Button><form className="space-y-m rounded-lg bg-surface-container px-l py-l" onSubmit={e => { e.preventDefault(); void run(async () => { await requestJson(`${base}/accounts/${id}/actions`, 'POST', { ...form, request_key: key }); setForm(empty); setKey(crypto.randomUUID()); await reload() }) }}>
      <label className="block">Stacker action kind<select className={nativeControl} value={form.kind} onChange={e => setForm({ ...form, kind: e.target.value, sats: 0 })}>{['discussion', 'comment', 'zap'].map(kind => <option key={kind}>{kind}</option>)}</select></label>{(['territory', 'title', 'text', 'item_id'] as const).map(field => <label className="block" key={field}>Action {field}<input className={nativeControl} value={form[field]} onChange={e => setForm({ ...form, [field]: e.target.value })} /></label>)}{form.kind === 'zap' && <label className="block">Zap sats<input className={nativeControl} type="number" min={1} max={1000000} value={form.sats} onChange={e => setForm({ ...form, sats: Number(e.target.value) })} /></label>}<Button type="submit" disabled={busy}>Prepare Stacker action</Button>
    </form>{actions.map(action => <article className="rounded-lg border border-outline-variant/20 bg-surface px-l py-m" key={action.id}><h3 data-type="title-s">{action.kind}: {action.title || action.item_id}</h3><p>Action territory: ~{action.territory}; target item: {action.item_id || 'new discussion'}</p><p>{action.text}</p>{action.kind === 'zap' && <p>Requested zap: {action.sats} sats</p>}<p>Stacker action: {action.state}; revision {action.revision}</p>{action.registration_changed && <p>Registration changed; create a new reviewed action.</p>}{action.error && <p>{action.error}</p>}{action.state === 'draft' && <Button disabled={busy || action.registration_changed} onClick={() => void run(async () => { await requestJson(`${base}/accounts/${id}/actions/${action.id}/review`, 'POST', { revision: action.revision, confirm_review: true }); await reload() })}>Confirm Stacker review</Button>}{action.handoff_url && <a href={action.handoff_url} target="_blank" rel="noopener noreferrer">Open reviewed Stacker destination</a>}{action.state === 'reviewed' && action.kind !== 'zap' && !action.registration_changed && <><label className="block"><input type="checkbox" checked={executeId === action.id} onChange={e => setExecuteId(e.target.checked ? action.id : '')} />Approve this exact action; provider may post and charge fees</label><Button disabled={busy || executeId !== action.id} onClick={() => void run(async () => { try { await requestJson(`${base}/accounts/${id}/actions/${action.id}/submit`, 'POST', { revision: action.revision, confirm_execute: true }) } finally { setExecuteId(''); await reload() } })}>Submit reviewed Stacker action</Button></>}{action.payin_id && <><p>PayIn {action.payin_id}: {action.provider_state}; cost {action.cost_msats} msats</p><Button disabled={busy || action.registration_changed} onClick={() => void run(async () => { await requestJson(`${base}/accounts/${id}/actions/${action.id}/reconcile`, 'POST', {}); await reload() })}>Read PayIn status</Button></>}</article>)}</>}
  </section>
}
