import { useEffect,useState } from 'react'
import { gatewayRequest,readJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { Checkbox, Field, TextArea, TextInput } from '../../../shared/ui/forms'
import { Surface } from '../../../shared/ui/Surface'
type Post={id:string;title:string;content?:string;author?:{name:string};submolt?:{name:string}|string}
type Receipt={id:string;kind:string;status:string;detail:{remote_id?:string;title?:string;code?:string}}
export default function Moltbook({baseUrl='',apiRoot='/api/capabilities/experience/moltbook'}:{baseUrl?:string;apiRoot?:string}){
 const root=baseUrl+apiRoot,[credential,setCredential]=useState(''),[configured,setConfigured]=useState(false),[profile,setProfile]=useState<Record<string,unknown>|null>(null),[posts,setPosts]=useState<Post[]>([]),[history,setHistory]=useState<Receipt[]>([]),[submolt,setSubmolt]=useState('general'),[title,setTitle]=useState(''),[content,setContent]=useState(''),[approved,setApproved]=useState(false),[postId,setPostId]=useState(''),[comment,setComment]=useState(''),[commentApproved,setCommentApproved]=useState(false),[error,setError]=useState('')
 const loadHistory=async()=>setHistory((await readJson<{items:Receipt[]}>(await gatewayRequest(root+'/history'))).items)
 const loadConfig=async()=>{const value=await readJson<{configured:boolean;credential_ref?:string}>(await gatewayRequest(root+'/config'));setConfigured(value.configured);setCredential(value.credential_ref||'')}
 useEffect(()=>{void Promise.all([loadConfig(),loadHistory()]).catch(reason=>setError(String(reason)))},[root])
 const run=async(action:()=>Promise<void>)=>{setError('');try{await action()}catch(reason){setError(String(reason))}}
 const save=()=>run(async()=>{await readJson(await gatewayRequest(root+'/config','POST',{credential_ref:credential}));setConfigured(true)})
 const readProfile=()=>run(async()=>setProfile(await readJson<Record<string,unknown>>(await gatewayRequest(root+'/profile'))))
 const feed=()=>run(async()=>{const value=await readJson<{posts?:Post[]}>(await gatewayRequest(root+'/feed?sort=new&limit=15'));setPosts(value.posts||[]);await loadHistory()})
 const publish=()=>run(async()=>{await readJson(await gatewayRequest(root+'/post','POST',{request_id:crypto.randomUUID(),submolt,title,content,approved}));setApproved(false);await loadHistory()})
 const publishComment=()=>run(async()=>{await readJson(await gatewayRequest(root+'/comment','POST',{request_id:crypto.randomUUID(),post_id:postId,content:comment,approved:commentApproved}));setCommentApproved(false);await loadHistory()})
 return <section aria-label="Moltbook adapter" className="space-y-4"><h2 data-type="title-m">Moltbook</h2><p>Connect an existing claimed account with a named credential. Reads are guarded; every post or comment requires explicit approval and receives a durable status.</p>{error&&<p role="alert">{error}</p>}
  <Field label="Named credential"><TextInput ariaLabel="Moltbook credential" value={credential} onChange={setCredential}/></Field><Button disabled={!credential} onClick={()=>void save()}>Save Moltbook connection</Button><p role="status">{configured?'Existing account configured':'No Moltbook account configured'}</p>
  <Button disabled={!configured} onClick={()=>void readProfile()}>Read profile</Button><Button disabled={!configured} onClick={()=>void feed()}>Load new feed</Button>{profile&&<pre aria-label="Moltbook profile">{JSON.stringify(profile,null,2)}</pre>}
  <section aria-label="Moltbook feed"><h3 data-type="title-m">Feed</h3>{posts.length===0&&<p>No posts loaded.</p>}{posts.map(post=><article key={post.id}><h4>{post.title}</h4><p>{post.content}</p><small>{post.author?.name||'Unknown author'}</small></article>)}</section>
  <Surface tone="low" className="p-m"><form className="space-y-m" onSubmit={event=>{event.preventDefault();void publish()}}><h3 data-type="title-m">Publish a post</h3><Field label="Submolt"><TextInput ariaLabel="Moltbook submolt" value={submolt} onChange={setSubmolt}/></Field><Field label="Title"><TextInput ariaLabel="Moltbook post title" value={title} onChange={setTitle}/></Field><Field label="Content"><TextArea ariaLabel="Moltbook post content" value={content} onChange={setContent}/></Field><label className="flex items-center gap-s"><Checkbox ariaLabel="Approve Moltbook post" checked={approved} onChange={setApproved}/>I approve publishing this post</label><Button type="submit" disabled={!configured||!approved||!title||!content}>Publish approved post</Button></form></Surface>
  <Surface tone="low" className="p-m"><form className="space-y-m" onSubmit={event=>{event.preventDefault();void publishComment()}}><h3 data-type="title-m">Publish a comment</h3><Field label="Post ID"><TextInput ariaLabel="Moltbook comment post ID" value={postId} onChange={setPostId}/></Field><Field label="Comment"><TextArea ariaLabel="Moltbook comment content" value={comment} onChange={setComment}/></Field><label className="flex items-center gap-s"><Checkbox ariaLabel="Approve Moltbook comment" checked={commentApproved} onChange={setCommentApproved}/>I approve publishing this comment</label><Button type="submit" disabled={!configured||!commentApproved||!postId||!comment}>Publish approved comment</Button></form></Surface>
  <section aria-label="Moltbook history"><h3 data-type="title-m">Action history</h3>{history.map(row=><p key={row.id}>{row.kind}: {row.status}{row.detail.title?' · '+row.detail.title:''}</p>)}</section>
 </section>
}
