import { useEffect, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'

type Turn = { index: number; transcript: string; reply: string }
type Session = { id: string; call_id: string; state: string; revision: number; max_turns: number; capture_seconds: number; turns: Turn[]; error: string }
type Snapshot = { readiness: { available: boolean; errors: string[]; capture: string; playback: string; stt: string; tts: string; device_qualification: string }; sessions: Session[] }

export default function NativeDuplex({ baseUrl = '/api/capabilities/experience' }: { baseUrl?: string }) {
  const [data, setData] = useState<Snapshot | null>(null), [selected, setSelected] = useState<Session | null>(null), [callId, setCallId] = useState(''), [reply, setReply] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const refresh = async () => { const value = await requestJson<Snapshot>(baseUrl + '/native-duplex'); setData(value); if (selected) setSelected(value.sessions.find(row => row.id === selected.id) || null) }
  useEffect(() => { void refresh().catch(cause => setError(String(cause))) }, [baseUrl])
  async function run(work: () => Promise<unknown>) { setBusy(true); setError(''); try { const value = await work() as Session; if (value?.id) setSelected(value); await refresh() } catch (cause) { setError(String(cause)) } finally { setBusy(false) } }
  return <section aria-label="Native duplex audio" className="space-y-3 rounded-lg border p-4"><h2>Native duplex audio</h2><p>Attach microphone capture and speaker playback to an existing native call request. This does not dial, answer, or hang up a call. External call commands still require their own explicit approval.</p>{error && <p role="alert">{error}</p>}{!data ? <p>Loading native audio readiness…</p> : <><p role="status">{data.readiness.available ? 'Mac audio bridge is locally available; device execution remains unverified.' : 'Native duplex audio unavailable'}</p>{data.readiness.errors.map((value, index) => <p key={index}>{value}</p>)}<dl><dt>Capture</dt><dd>{data.readiness.capture}</dd><dt>Playback</dt><dd>{data.readiness.playback}</dd><dt>Speech recognition</dt><dd>{data.readiness.stt}</dd><dt>Speech synthesis</dt><dd>{data.readiness.tts}</dd></dl><label>Existing native call request ID<input value={callId} onChange={event => setCallId(event.target.value)} /></label><Button disabled={busy || !callId || !data.readiness.available} onClick={() => void run(() => requestJson(baseUrl + '/native-duplex', 'POST', { call_id: callId, request_id: crypto.randomUUID(), max_turns: 10, capture_seconds: 8 }))}>Attach audio session</Button><label>Saved audio session<select value={selected?.id || ''} onChange={event => setSelected(data.sessions.find(row => row.id === event.target.value) || null)}><option value="">Choose a session</option>{data.sessions.map(row => <option key={row.id} value={row.id}>{row.state} · {row.turns.length}/{row.max_turns}</option>)}</select></label>{selected && <article><p role="status">Session {selected.state} · revision {selected.revision}</p>{selected.error && <p role="alert">{selected.error}</p>}<Button disabled={busy || selected.state !== 'ready'} onClick={() => void run(() => requestJson(baseUrl + `/native-duplex/${selected.id}/capture`, 'POST', { revision: selected.revision }))}>Capture and transcribe turn</Button><label>Agent reply<textarea maxLength={10000} value={reply} onChange={event => setReply(event.target.value)} /></label><Button disabled={busy || selected.state !== 'awaiting_reply' || !reply.trim()} onClick={() => void run(async () => { const value = await requestJson(baseUrl + `/native-duplex/${selected.id}/speak`, 'POST', { revision: selected.revision, text: reply }); setReply(''); return value })}>Synthesize and play reply</Button><Button disabled={busy || ['capturing', 'speaking', 'stopped'].includes(selected.state)} onClick={() => void run(() => requestJson(baseUrl + `/native-duplex/${selected.id}/stop`, 'POST', { revision: selected.revision }))}>Stop audio session</Button><ol>{selected.turns.map(turn => <li key={turn.index}><strong>Caller:</strong> {turn.transcript}<br /><strong>Gideon:</strong> {turn.reply || 'Awaiting reply'}</li>)}</ol></article>}<Button disabled={busy} onClick={() => void refresh().catch(cause => setError(String(cause)))}>Refresh audio state</Button></>}</section>
}
