"""Compatibility module for the canonical home-scoped composition store."""

import sys

from gideon.workspace.capabilities.platform import compositions
from gideon.workspace.capabilities.platform.compositions import (
    config_dir as config_dir,
    _STORE_FILENAME as _STORE_FILENAME,
    _SIZES as _SIZES,
    _ADDED_BY as _ADDED_BY,
    _REFRESH_MODES as _REFRESH_MODES,
    PRESET_OVERVIEW_ID as PRESET_OVERVIEW_ID,
    _OVERVIEW_CORE_REFS as _OVERVIEW_CORE_REFS,
    PRESET_MISSION_CONTROL_ID as PRESET_MISSION_CONTROL_ID,
    _MISSION_CONTROL_CORE_REFS as _MISSION_CONTROL_CORE_REFS,
    PresetLockedError as PresetLockedError,
    ViewNotFoundError as ViewNotFoundError,
    TileDataNode as TileDataNode,
    TileRefresh as TileRefresh,
    DashboardTile as DashboardTile,
    DashboardView as DashboardView,
    views_path as views_path,
    _empty_disk as _empty_disk,
    _read_disk as _read_disk,
    _mutate_disk as _mutate_disk,
    _refresh_from_dict as _refresh_from_dict,
    _tile_from_dict as _tile_from_dict,
    _overlay_tiles as _overlay_tiles,
    _overview_preset as _overview_preset,
    _mission_control_preset as _mission_control_preset,
    _presets as _presets,
    _user_view_from_dict as _user_view_from_dict,
    _views_from_data as _views_from_data,
    load_views as load_views,
    list_views as list_views,
    get_view as get_view,
    _is_preset as _is_preset,
    create_view as create_view,
    update_view as update_view,
    delete_view as delete_view,
    _max_tiles as _max_tiles,
    add_tile as add_tile,
    set_tile_refresh as set_tile_refresh,
    find_tile as find_tile,
    resolve_tile as resolve_tile,
    CORE_COMPOSITION_REFS as CORE_COMPOSITION_REFS,
    composition_state as composition_state,
    set_composition as set_composition,
)

__all__ = [
    "config_dir",
    "_STORE_FILENAME",
    "_SIZES",
    "_ADDED_BY",
    "_REFRESH_MODES",
    "PRESET_OVERVIEW_ID",
    "_OVERVIEW_CORE_REFS",
    "PRESET_MISSION_CONTROL_ID",
    "_MISSION_CONTROL_CORE_REFS",
    "PresetLockedError",
    "ViewNotFoundError",
    "TileDataNode",
    "TileRefresh",
    "DashboardTile",
    "DashboardView",
    "views_path",
    "_empty_disk",
    "_read_disk",
    "_mutate_disk",
    "_refresh_from_dict",
    "_tile_from_dict",
    "_overlay_tiles",
    "_overview_preset",
    "_mission_control_preset",
    "_presets",
    "_user_view_from_dict",
    "_views_from_data",
    "load_views",
    "list_views",
    "get_view",
    "_is_preset",
    "create_view",
    "update_view",
    "delete_view",
    "_max_tiles",
    "add_tile",
    "set_tile_refresh",
    "find_tile",
    "resolve_tile",
    "CORE_COMPOSITION_REFS",
    "composition_state",
    "set_composition",
]

# Preserve module identity, including existing config_dir monkeypatch consumers.
sys.modules[__name__] = compositions
