"""image_generate tool (mcp_artifacts) — end-to-end over a fake provider.

The tool is a thin wrapper: resolve the image_gen capability -> generate/edit ->
materialize the result -> save a kind:image binary artifact -> return the slug.
Tested with a fake provider (no real API) so it's free + deterministic.
"""

from __future__ import annotations

import base64

import pytest

from gideon.image_gen.provider import ImageGenModel, ImageGenProvider, ImageResult

_PNG_B64 = base64.b64encode(b"\x89PNG\r\n\x1a\nGENERATED").decode()
_EDIT_B64 = base64.b64encode(b"\x89PNG\r\n\x1a\nEDITED").decode()


class _FakeProvider(ImageGenProvider):
    @property
    def name(self) -> str:
        return "fake"

    @property
    def display_name(self) -> str:
        return "Fake"

    async def is_available(self) -> bool:
        return True

    async def list_models(self):
        return [ImageGenModel(name="fake-1", supports_edit=True)]

    async def generate(self, prompt, *, model="", size="", n=1, **opts):
        return [ImageResult(b64=_PNG_B64, mime="image/png", revised_prompt=f"refined: {prompt}")]

    async def edit(self, prompt, *, source_image, mask="", model="", size="", n=1, **opts):
        # prove the source bytes were threaded through
        with open(source_image, "rb") as fh:
            assert fh.read()  # non-empty source
        return [ImageResult(b64=_EDIT_B64, mime="image/png")]


@pytest.fixture
def _wired(tmp_path, monkeypatch):
    """Point the artifact store at tmp + bind a fake image_gen provider."""
    from gideon.artifacts import native, registry as art_reg
    from gideon.image_gen import registry as ig_reg

    prov = native.NativeArtifactProvider(root=tmp_path)
    monkeypatch.setattr(art_reg, "get_provider", lambda name="native": prov)

    fake = _FakeProvider()
    monkeypatch.setattr(ig_reg, "active_image_gen", lambda: (fake, "fake-1"))
    # session resolution → None (no chat session in test)
    monkeypatch.setattr("gideon.mcp_artifacts._resolve_session_key", lambda: None)
    return prov


class TestImageGenerateTool:
    def test_generate_saves_image_artifact(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner

        out = _call_tool_inner("image_generate", {"prompt": "a red bicycle"})
        assert "Generated image" in out and "slug:" in out
        # the kind:image artifact exists with the generated bytes
        imgs = _wired.list(kind="image")
        assert len(imgs) == 1
        slug = imgs[0].slug
        data, mime = _wired.raw_bytes(slug)
        assert data == base64.b64decode(_PNG_B64)
        assert mime == "image/png"

    def test_generate_surfaces_revised_prompt(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner
        out = _call_tool_inner("image_generate", {"prompt": "a cat"})
        assert "refined: a cat" in out

    def test_generate_returns_embeddable_markdown(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner
        out = _call_tool_inner("image_generate", {"prompt": "a tree"})
        slug = _wired.list(kind="image")[0].slug
        # the result hands the model a ready markdown image PINNED to the version it
        # produced (?version=1), so the chat message stays bound to this image.
        assert "![" in out and f"](/api/artifacts/{slug}/raw?version=1)" in out

    def test_no_model_configured_is_clear_error(self, tmp_path, monkeypatch):
        from gideon.artifacts import native, registry as art_reg
        from gideon.image_gen import registry as ig_reg
        from gideon.mcp_artifacts import _call_tool_inner

        monkeypatch.setattr(art_reg, "get_provider", lambda name="native": native.NativeArtifactProvider(root=tmp_path))
        monkeypatch.setattr(ig_reg, "active_image_gen", lambda: None)
        monkeypatch.setattr("gideon.mcp_artifacts._resolve_session_key", lambda: None)
        out = _call_tool_inner("image_generate", {"prompt": "x"})
        assert "no image-generation model is configured" in out

    def test_empty_prompt_rejected(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner
        out = _call_tool_inner("image_generate", {"prompt": "   "})
        assert out.startswith("Error:")

    def test_edit_bumps_version_on_source_artifact(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner

        # first generate, then edit that artifact in place
        _call_tool_inner("image_generate", {"prompt": "a plain mug"})
        slug = _wired.list(kind="image")[0].slug
        out = _call_tool_inner("image_generate", {"prompt": "add steam", "edit_artifact": slug})
        assert "Edited image artifact" in out and "version 2" in out
        # edit result is pinned to v2
        assert f"](/api/artifacts/{slug}/raw?version=2)" in out
        # live bytes are the edited ones; v1 keeps the original
        assert _wired.raw_bytes(slug)[0] == base64.b64decode(_EDIT_B64)
        assert _wired.raw_bytes(slug, version=1)[0] == base64.b64decode(_PNG_B64)

    def test_edit_nonexistent_artifact_errors(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner
        out = _call_tool_inner("image_generate", {"prompt": "x", "edit_artifact": "nope"})
        assert "not an existing image artifact" in out

    def test_edit_refuses_non_image_artifact(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner
        _wired.create(name="doc", content="# hi", kind="markdown")
        out = _call_tool_inner("image_generate", {"prompt": "x", "edit_artifact": "doc"})
        assert "not an existing image artifact" in out


class TestRegenerateAtSlug:
    """regenerate_image_at_slug: re-run a generation AT a specific slug so a deleted
    image's transcript ref resolves again — recreate at v1 if gone, else append."""

    def test_recreates_deleted_artifact_at_same_slug_v1(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner, regenerate_image_at_slug

        # generate, capture slug, then delete it (simulating the broken-transcript case)
        _call_tool_inner("image_generate", {"prompt": "a red bicycle"})
        slug = _wired.list(kind="image")[0].slug
        assert _wired.delete(slug) is True
        assert _wired.get(slug) is None
        # regenerate at that exact slug
        ok, msg = regenerate_image_at_slug(_wired, slug, "a red bicycle")
        assert ok is True and msg == slug
        # recreated at the SAME slug, version 1 (so a ?version=1 transcript ref resolves)
        art = _wired.get(slug)
        assert art is not None and art.version == 1
        assert _wired.raw_bytes(slug, version=1) is not None

    def test_appends_version_when_artifact_still_exists(self, _wired):
        from gideon.mcp_artifacts import _call_tool_inner, regenerate_image_at_slug

        _call_tool_inner("image_generate", {"prompt": "a blue car"})
        slug = _wired.list(kind="image")[0].slug
        ok, msg = regenerate_image_at_slug(_wired, slug, "a blue car")
        assert ok is True
        assert _wired.get(slug).version == 2  # appended, not duplicated

    def test_no_prompt_fails_cleanly(self, _wired):
        from gideon.mcp_artifacts import regenerate_image_at_slug
        ok, msg = regenerate_image_at_slug(_wired, "some-slug", "   ")
        assert ok is False and "prompt" in msg.lower()


class TestMaterialize:
    def test_materialize_b64(self):
        from gideon.mcp_artifacts import _materialize_image
        r = ImageResult(b64=_PNG_B64, mime="image/png")
        data, mime = _materialize_image(r)
        assert data == base64.b64decode(_PNG_B64) and mime == "image/png"

    def test_materialize_local_path(self, tmp_path):
        from gideon.mcp_artifacts import _materialize_image
        p = tmp_path / "x.png"
        p.write_bytes(b"localbytes")
        r = ImageResult(local_path=str(p), mime="image/png")
        data, mime = _materialize_image(r)
        assert data == b"localbytes"

    def test_materialize_nothing_returns_none(self):
        from gideon.mcp_artifacts import _materialize_image
        assert _materialize_image(ImageResult()) is None
