[package]
name = "hypermid-bus-contracts"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
hypermid-contracts = { path = "../hypermid-contracts" }
serde.workspace = true
thiserror.workspace = true

