import { useEffect, useRef, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { ListScaffold } from '../../../shared/ui/ListScaffold'
import { Field, TextInput } from '../../../shared/ui/forms'

type Link = { id: string; title: string; url: string }
type Bucket = { id: string; name: string; icon: string; links: Link[] }
type Repo = { id: string; url: string; status: string; stage: string; revision: string; report_id?: string; error: string; events: { sequence: number; detail: string; status: string }[] }
const root = '/api/capabilities/knowledge/links'

export default function LinksPage() {
  const [buckets, setBuckets] = useState<Bucket[]>([]), [selected, setSelected] = useState<Bucket | null>(null), [repos, setRepos] = useState<Repo[]>([]), [repo, setRepo] = useState<Repo | null>(null)
  const [bucketName, setBucketName] = useState(''), [title, setTitle] = useState(''), [url, setUrl] = useState(''), [repoUrl, setRepoUrl] = useState('')
  const [report, setReport] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const requestId = useRef(crypto.randomUUID())
  async function load() { const [bucketData, repoData] = await Promise.all([requestJson<{ buckets: Bucket[] }>(root + '/buckets'), requestJson<{ items: Repo[] }>(root + '/repositories')]); setBuckets(bucketData.buckets); setRepos(repoData.items); setSelected(current => current ? bucketData.buckets.find(item => item.id === current.id) ?? null : current); setRepo(current => current ? repoData.items.find(item => item.id === current.id) ?? current : current) }
  useEffect(() => { load().catch(e => setError(e.message)) }, [])
  async function act(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  async function createBucket() { await act(async () => { const bucket = await requestJson<Bucket>(root + '/buckets', 'POST', { name: bucketName, icon: '🔗' }); setBucketName(''); await load(); setSelected(bucket) }) }
  async function addLink() { if (!selected) return; await act(async () => { await requestJson(root + '/links', 'POST', { url, title, bucket_id: selected.id }); setUrl(''); setTitle(''); await load() }) }
  async function moveLink(index: number, direction: number) { if (!selected) return; const ids = selected.links.map(item => item.id); const target = index + direction; if (target < 0 || target >= ids.length) return; [ids[index], ids[target]] = [ids[target], ids[index]]; await act(async () => { await requestJson(`${root}/buckets/${selected.id}/links-reorder`, 'POST', { ids }); await load() }) }
  async function deleteBucket() { if (!selected) return; await act(async () => { await requestJson(`${root}/buckets/${selected.id}/bucket`, 'DELETE'); setSelected(null); await load() }) }
  async function intake() { await act(async () => { const created = await requestJson<Repo>(root + '/repositories', 'POST', { request_id: requestId.current, url: repoUrl }); setRepo(created); requestId.current = crypto.randomUUID(); await load() }) }
  async function restudy() { if (!repo) return; await act(async () => { setRepo(await requestJson<Repo>(`${root}/repositories/${repo.id}/study`, 'POST')); await load() }) }
  async function readReport() { if (!repo) return; await act(async () => setReport((await requestJson<{ content: string }>(`${root}/repositories/${repo.id}/report`)).content)) }
  return <main className="h-full"><ListScaffold title="Links and repository study" bodyClassName="mx-auto px-l py-l"><div className="flex flex-col gap-xl"><p data-type="body-m" className="max-w-[42rem] text-on-surface-var">Keep ordered bookmark buckets and study guarded public repository snapshots in canonical Knowledge.</p>{error && <p role="alert" className="border-l-2 border-danger/40 pl-s text-danger">{error}</p>}
    <div className="grid gap-l lg:grid-cols-2"><section aria-label="Link buckets" className="flex flex-col gap-m rounded-lg bg-surface-container p-l"><h2 data-type="title-m">Link buckets</h2><Field label="Bucket name"><TextInput ariaLabel="Bucket name" value={bucketName} surface="high" onChange={setBucketName} /></Field><Button className="w-fit" disabled={busy || !bucketName.trim()} onClick={() => void createBucket()}>Create bucket</Button><nav aria-label="Buckets" className="flex flex-wrap gap-s">{buckets.map(item => <Button variant={selected?.id===item.id?'primary':'ghost'} key={item.id} disabled={busy} onClick={() => setSelected(item)}>{item.icon} {item.name} · {item.links.length}</Button>)}</nav></section>
    {selected && <section aria-label="Selected bucket" className="flex flex-col gap-m rounded-lg bg-surface-container p-l"><h2 data-type="title-m">{selected.name}</h2><Field label="Link title"><TextInput ariaLabel="Link title" value={title} surface="high" onChange={setTitle} /></Field><Field label="Link URL"><TextInput ariaLabel="Link URL" value={url} surface="high" onChange={setUrl} /></Field><div className="flex flex-wrap gap-s"><Button disabled={busy || !title || !url} onClick={() => void addLink()}>Add link</Button><Button variant="secondary" disabled={busy} onClick={() => void deleteBucket()}>Delete bucket, keep links</Button></div><ol className="flex flex-col gap-s">{selected.links.map((item, index) => <li className="flex flex-wrap items-center gap-s border-t border-outline-variant/20 pt-s" key={item.id}><a className="min-w-0 flex-1 truncate text-primary underline" href={item.url}>{item.title}</a><Button variant="ghost" disabled={busy || index === 0} onClick={() => void moveLink(index, -1)}>Move {item.title} up</Button><Button variant="ghost" disabled={busy || index === selected.links.length - 1} onClick={() => void moveLink(index, 1)}>Move {item.title} down</Button></li>)}</ol></section>}
    <section aria-label="Repository intake" className="flex flex-col gap-m rounded-lg bg-surface-container p-l"><h2 data-type="title-m">Repository intake</h2><Field label="Public repository URL"><TextInput ariaLabel="Public repository URL" value={repoUrl} surface="high" onChange={value => { setRepoUrl(value); requestId.current = crypto.randomUUID() }} /></Field><Button className="w-fit" disabled={busy || !repoUrl} onClick={() => void intake()}>Fetch and study repository</Button><nav aria-label="Repository studies" className="flex flex-wrap gap-s">{repos.map(item => <Button variant={repo?.id===item.id?'primary':'ghost'} key={item.id} disabled={busy} onClick={() => setRepo(item)}>{item.url.split('/').pop()} · {item.status}</Button>)}</nav></section>
    {repo && <section aria-label="Selected repository" className="flex flex-col gap-m rounded-lg bg-surface-container p-l"><h2 data-type="title-m" className="break-all">{repo.url}</h2><p>Status: {repo.status} · {repo.stage}</p>{repo.revision && <p className="break-all text-on-surface-var">Revision: {repo.revision}</p>}{repo.error && <p role="alert" className="text-danger">{repo.error}</p>}<div className="flex flex-wrap gap-s"><Button variant="secondary" disabled={busy || !repo.revision} onClick={() => void restudy()}>Refresh study</Button><Button disabled={busy || !repo.report_id} onClick={() => void readReport()}>Read study report</Button></div><ul>{repo.events.map(event => <li className="border-t border-outline-variant/20 py-s" key={event.sequence}>{event.status} · {event.detail}</li>)}</ul></section>}</div>
    {report && <section aria-label="Repository report" className="rounded-lg bg-surface-container p-l"><h2 data-type="title-m" className="mb-m">Repository report</h2><pre className="whitespace-pre-wrap break-words">{report}</pre></section>}
  </div></ListScaffold></main>
}
