import { useEffect, useRef, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { ListScaffold } from '../../../shared/ui/ListScaffold'
import { Field, TextArea, TextInput } from '../../../shared/ui/forms'

type Vault = { id: string; name: string; spec: { path: string }; enabled: boolean; note_count: number }
type Note = { path: string; title: string; content: string; current_hash: string; tags: string[]; wikilinks: string[]; source_link: string }
const root = '/api/capabilities/knowledge/vaults'

export default function VaultsPage() {
  const [vaults, setVaults] = useState<Vault[]>([]), [roots, setRoots] = useState<string[]>([]), [selected, setSelected] = useState<Vault | null>(null), [notes, setNotes] = useState<Note[]>([]), [note, setNote] = useState<Note | null>(null)
  const [name, setName] = useState(''), [path, setPath] = useState(''), [notePath, setNotePath] = useState(''), [content, setContent] = useState(''), [query, setQuery] = useState('')
  const [error, setError] = useState(''), [busy, setBusy] = useState(false), [status, setStatus] = useState('')
  const requestId = useRef(crypto.randomUUID())
  async function load() { const data = await requestJson<{ items: Vault[]; allowed_roots: string[] }>(root); setVaults(data.items); setRoots(data.allowed_roots); setSelected(current => current ? data.items.find(item => item.id === current.id) ?? null : current) }
  useEffect(() => { load().catch(e => setError(e.message)) }, [])
  async function act(fn: () => Promise<void>) { setBusy(true); setError(''); try { await fn() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  async function register() { await act(async () => { const value = await requestJson<Vault>(root + '/register', 'POST', { name, path }); await load(); setSelected(value); setStatus('Vault registered') }) }
  async function scan() { if (!selected) return; await act(async () => { const result = await requestJson<{ notes: Note[]; deleted_refs: number }>(`${root}/${selected.id}/scan`, 'POST'); setNotes(result.notes); setStatus(`${result.notes.length} notes indexed · ${result.deleted_refs} missing references archived`) }) }
  async function open(path: string) { if (!selected) return; await act(async () => { const value = await requestJson<Note>(`${root}/${selected.id}/read`, 'POST', { path }); setNote(value); setNotePath(value.path); setContent(value.content); requestId.current = crypto.randomUUID() }) }
  async function save() { if (!selected) return; await act(async () => { const value = await requestJson<Note>(`${root}/${selected.id}/write`, 'POST', { request_id: requestId.current, path: notePath, content, expected_hash: note?.current_hash || '' }); setNote(value); setStatus(value.path + ' saved atomically'); requestId.current = crypto.randomUUID(); await scan() }) }
  async function removeNote() { if (!selected || !note) return; await act(async () => { await requestJson(`${root}/${selected.id}/delete`, 'POST', { request_id: requestId.current, path: note.path, expected_hash: note.current_hash }); setNote(null); setContent(''); setStatus('Note deleted; canonical reference archived'); requestId.current = crypto.randomUUID(); await scan() }) }
  async function search() { if (!selected) return; await act(async () => { const result = await requestJson<{ results: Note[] }>(`${root}/${selected.id}/search`, 'POST', { query }); setNotes(result.results) }) }
  return <main className="h-full"><ListScaffold title="External knowledge vaults" bodyClassName="mx-auto px-l py-l"><div className="flex flex-col gap-xl"><p data-type="body-m" className="max-w-[42rem] text-on-surface-var">Register an explicitly allowed Markdown vault, index canonical Knowledge references, and edit with conflict protection.</p>{error && <p role="alert" className="border-l-2 border-danger/40 pl-s text-danger">{error}</p>}{status && <p role="status" className="text-on-surface-var">{status}</p>}
    <details open={!vaults.length} className="rounded-lg bg-surface-container"><summary data-type="label-l" className="cursor-pointer px-l py-m">Register vault</summary><section aria-label="Vault registration" className="grid gap-m border-t border-outline-variant/20 p-l sm:grid-cols-2"><p className="sm:col-span-2 text-on-surface-var">Allowed roots: {roots.join(', ') || 'None configured'}</p><Field label="Vault name"><TextInput ariaLabel="Vault name" value={name} surface="high" onChange={setName} /></Field><Field label="Vault path"><TextInput ariaLabel="Vault path" value={path} surface="high" mono onChange={setPath} /></Field><Button className="sm:col-span-2 sm:w-fit" disabled={busy || !name || !path || roots.length === 0} onClick={() => void register()}>Register vault</Button></section></details>
    <div className="grid gap-l lg:grid-cols-[minmax(16rem,0.72fr)_minmax(0,1.6fr)]"><aside className="flex min-w-0 flex-col gap-m rounded-lg bg-surface-container p-l"><h2 data-type="title-m">Vaults</h2><nav aria-label="External vaults" className="flex flex-col gap-s">{vaults.map(item => <Button variant={selected?.id===item.id?'primary':'ghost'} className="justify-start" key={item.id} disabled={busy || !item.enabled} onClick={() => { setSelected(item); setNotes([]); setNote(null) }}>{item.name} · {item.note_count}</Button>)}</nav>
    {selected && <section aria-label="Selected vault" className="flex flex-col gap-m border-t border-outline-variant/20 pt-m"><h2 data-type="label-l">{selected.name}</h2><p className="break-all font-mono text-on-surface-var">{selected.spec.path}</p><Button variant="secondary" disabled={busy} onClick={() => void scan()}>Scan vault</Button><Field label="Search notes"><TextInput ariaLabel="Search notes" value={query} surface="high" onChange={setQuery} /></Field><Button disabled={busy || !query} onClick={() => void search()}>Search</Button><ul className="flex flex-col gap-xs">{notes.map(item => <li key={item.path}><Button variant={note?.path===item.path?'primary':'ghost'} className="w-full justify-start" disabled={busy} onClick={() => void open(item.path)}>{item.path}</Button></li>)}</ul></section>}</aside>
    <section aria-label="Vault note editor" className="flex min-h-96 min-w-0 flex-col gap-m rounded-lg bg-surface-container p-l">{selected?<><Field label="Note path"><TextInput ariaLabel="Note path" value={notePath} surface="high" mono onChange={value => { setNotePath(value); setNote(null); requestId.current = crypto.randomUUID() }} /></Field><Field label="Markdown content"><TextArea ariaLabel="Markdown content" rows={14} surface="high" mono value={content} onChange={value => { setContent(value); requestId.current = crypto.randomUUID() }} /></Field><div className="flex flex-wrap gap-s"><Button disabled={busy || !notePath} onClick={() => void save()}>{note ? 'Save note' : 'Create note'}</Button>{note && <><a className="self-center text-primary underline" href={note.source_link}>Open canonical reference</a><Button variant="secondary" disabled={busy} onClick={() => void removeNote()}>Delete note</Button></>}</div></>:<p className="m-auto text-center text-on-surface-var">Select a vault to edit its notes.</p>}</section></div>
  </div></ListScaffold></main>
}
