import { useEffect, useRef, useState } from 'react'
import { requestJson } from '../../../shared/data/gatewayRequest'
import { Button } from '../../../shared/ui/Button'
import { ListScaffold } from '../../../shared/ui/ListScaffold'
import { Field, Select, TextArea, TextInput } from '../../../shared/ui/forms'

type Segment = { start: number; end: number; text: string; source_link: string }
type Preview = { preview_id: string; title: string; video_id: string; url: string; format: string; language: string; segments: Segment[]; text: string }
type Event = { sequence: number; stage: string; status: string; detail: string; happened_at: string }
type Job = { id: string; video_id: string; url: string; title: string; status: string; stage: string; error: string; source_id?: string; transcript_id?: string; artifacts: { kind: string; bytes: number; sha256: string }[]; events: Event[] }
const root = '/api/capabilities/knowledge/videos'

export default function VideosPage() {
  const [jobs, setJobs] = useState<Job[]>([]), [selected, setSelected] = useState<Job | null>(null)
  const [url, setUrl] = useState(''), [title, setTitle] = useState(''), [language, setLanguage] = useState('en')
  const [format, setFormat] = useState('vtt'), [content, setContent] = useState('')
  const [wantTranscript, setWantTranscript] = useState(true), [wantVideo, setWantVideo] = useState(false), [wantAudio, setWantAudio] = useState(false)
  const [review, setReview] = useState<Preview | null>(null), [availability, setAvailability] = useState({ caption_retrieval: false, reason: '' })
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [transcript, setTranscript] = useState('')
  const requestId = useRef(crypto.randomUUID())
  async function load() { const data = await requestJson<{ items: Job[]; availability: typeof availability }>(root); setJobs(data.items); setAvailability(data.availability); setSelected(current => current ? data.items.find(job => job.id === current.id) ?? current : current) }
  useEffect(() => { load().catch(e => setError(e.message)) }, [])
  async function act(action: () => Promise<void>) { setBusy(true); setError(''); try { await action() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  function changed() { setReview(null); requestId.current = crypto.randomUUID() }
  async function preview() { await act(async () => setReview(await requestJson<Preview>(root + '/preview', 'POST', { url, title, format, content, language }))) }
  async function importTranscript() { if (!review) return; await act(async () => { const job = await requestJson<Job>(root + '/import', 'POST', { request_id: requestId.current, url, title, format, content, language, preview_id: review.preview_id }); setSelected(job); await load(); setReview(null); requestId.current = crypto.randomUUID() }) }
  async function fetchVideo() { await act(async () => { const job = await requestJson<Job>(root + '/fetch', 'POST', { request_id: requestId.current, url, language, transcript: wantTranscript, video: wantVideo, audio: wantAudio }); setSelected(job); await load(); requestId.current = crypto.randomUUID() }) }
  async function refresh(job: Job) { await act(async () => { const current = await requestJson<Job>(`${root}/${job.id}`); setSelected(current); await load() }) }
  async function cancel(job: Job) { await act(async () => { setSelected(await requestJson<Job>(`${root}/${job.id}/cancel`, 'POST')); await load() }) }
  async function openTranscript(job: Job) { await act(async () => setTranscript((await requestJson<{ content: string }>(`${root}/${job.id}/transcript`)).content)) }
  return <main className="h-full"><ListScaffold title="Video sources" right={<Button variant="secondary" disabled={busy} onClick={() => void load()}>Refresh</Button>} bodyClassName="mx-auto px-l py-l"><div className="flex flex-col gap-xl"><p data-type="body-m" className="max-w-[42rem] text-on-surface-var">Review supplied captions or acquire selected artifacts from one public YouTube video. Every caption keeps its timestamp and provenance.</p>{error && <p role="alert" className="border-l-2 border-danger/40 pl-s text-danger">{error}</p>}{!availability.caption_retrieval && availability.reason && <p role="status" className="text-on-surface-var">{availability.reason}</p>}
    <div className="grid gap-l lg:grid-cols-[minmax(16rem,0.72fr)_minmax(0,1.6fr)]"><nav aria-label="Video ingests" className="flex min-w-0 flex-col gap-s rounded-lg bg-surface-container p-l"><h2 data-type="title-m">Video ingests</h2>{jobs.length === 0 ? <p className="py-xl text-center text-on-surface-var">No video ingests yet.</p> : jobs.map(job => <Button variant={selected?.id===job.id?'primary':'ghost'} className="h-auto justify-start whitespace-normal text-start" key={job.id} disabled={busy} onClick={() => setSelected(job)}>{job.title} · {job.status}</Button>)}</nav>
    <div className="flex min-w-0 flex-col gap-l"><section className="grid gap-m rounded-lg bg-surface-container p-l sm:grid-cols-2"><Field label="Video URL"><TextInput ariaLabel="Video URL" value={url} surface="high" disabled={busy} onChange={value => { setUrl(value); changed() }} /></Field><Field label="Language"><TextInput ariaLabel="Caption language" value={language} surface="high" disabled={busy} onChange={value => { setLanguage(value); changed() }} /></Field>
    <section aria-label="Supplied transcript" className="flex flex-col gap-m border-t border-outline-variant/20 pt-m sm:col-span-2"><h2 data-type="title-m">Review supplied captions</h2><Field label="Title"><TextInput ariaLabel="Video title" value={title} surface="high" disabled={busy} onChange={value => { setTitle(value); changed() }} /></Field><Field label="Format"><Select ariaLabel="Transcript format" value={format} surface="high" disabled={busy} onChange={value => { setFormat(value); changed() }} options={[{value:'vtt',label:'WebVTT'},{value:'srt',label:'SRT'},{value:'json',label:'Timed JSON'}]} /></Field><Field label="Caption content"><TextArea ariaLabel="Caption content" rows={10} surface="high" value={content} disabled={busy} onChange={value => { setContent(value); changed() }} /></Field><Button className="w-fit" disabled={busy || !url || !title || !content} onClick={() => void preview()}>Preview captions</Button>{review && <section aria-label="Caption review" className="rounded-lg bg-surface-high p-m"><p>{review.segments.length} timed segments · {review.language}</p><a className="text-primary underline" href={review.segments[0]?.source_link}>Open first timestamp</a><pre className="whitespace-pre-wrap break-words">{review.text}</pre><Button disabled={busy} onClick={() => void importTranscript()}>Save reviewed transcript</Button></section>}</section>
    <section aria-label="Public acquisition" className="flex flex-wrap items-center gap-m border-t border-outline-variant/20 pt-m sm:col-span-2"><h2 data-type="label-l" className="w-full">Acquire public source</h2>{[[wantTranscript,setWantTranscript,'Retrieve captions','Captions'],[wantVideo,setWantVideo,'Download video','Video'],[wantAudio,setWantAudio,'Download audio','Audio']].map(([checked,setter,label,text]) => <label key={String(label)} className="inline-flex min-h-10 items-center gap-s"><input className="size-4 accent-primary" type="checkbox" aria-label={String(label)} checked={Boolean(checked)} disabled={busy} onChange={e => { (setter as (value:boolean)=>void)(e.target.checked); changed() }} />{String(text)}</label>)}<Button disabled={busy || !url || (!wantTranscript && !wantVideo && !wantAudio)} onClick={() => void fetchVideo()}>Start acquisition</Button></section></section>
    {selected && <section aria-label="Selected video ingest" className="flex flex-col gap-m rounded-lg bg-surface-container p-l"><h2 data-type="title-m">{selected.title}</h2><p>Status: {selected.status} · {selected.stage}</p>{selected.error && <p role="alert" className="text-danger">{selected.error}</p>}<div className="flex flex-wrap gap-m"><a className="text-primary underline" href={selected.url}>Original video</a>{selected.source_id && <a className="text-primary underline" href={`#/knowledge/item/${selected.source_id}`}>Open source record</a>}</div><div className="flex flex-wrap gap-s">{selected.transcript_id && <Button onClick={() => void openTranscript(selected)}>Read transcript</Button>}<Button variant="secondary" disabled={busy} onClick={() => void refresh(selected)}>Refresh status</Button>{['pending', 'running', 'cancelling'].includes(selected.status) && <Button variant="secondary" disabled={busy} onClick={() => void cancel(selected)}>Cancel acquisition</Button>}</div><ul>{selected.events.map(event => <li className="border-t border-outline-variant/20 py-s" key={event.sequence}>{event.stage} · {event.status} · {event.detail}</li>)}</ul>{selected.artifacts.map(item => <p className="text-on-surface-var" key={item.sha256}>{item.kind} · {item.bytes} bytes · verified {item.sha256.slice(0, 12)}</p>)}</section>}
    {transcript && <section aria-label="Stored transcript" className="rounded-lg bg-surface-container p-l"><h2 data-type="title-m" className="mb-m">Stored transcript</h2><pre className="whitespace-pre-wrap break-words">{transcript}</pre></section>}</div></div>
  </div></ListScaffold></main>
}
